// m_boss32.rs -- Makron (Final Boss)
// Converted from: myq2-original/game/m_boss32.c
// Frame definitions from: myq2-original/game/m_boss32.h

use crate::g_local::*;
use crate::game::*;
use myq2_common::common::frand as random;
use myq2_common::q_shared::{vector_set, vector_normalize};

// ============================================================
// Frame definitions (from m_boss32.h)
// This file generated by ModelGen - Do NOT Modify
// G:\quake2\baseq2\models/monsters/boss3/rider
// ============================================================

pub const FRAME_ATTAK101: i32 = 0;
pub const FRAME_ATTAK102: i32 = 1;
pub const FRAME_ATTAK103: i32 = 2;
pub const FRAME_ATTAK104: i32 = 3;
pub const FRAME_ATTAK105: i32 = 4;
pub const FRAME_ATTAK106: i32 = 5;
pub const FRAME_ATTAK107: i32 = 6;
pub const FRAME_ATTAK108: i32 = 7;
pub const FRAME_ATTAK109: i32 = 8;
pub const FRAME_ATTAK110: i32 = 9;
pub const FRAME_ATTAK111: i32 = 10;
pub const FRAME_ATTAK112: i32 = 11;
pub const FRAME_ATTAK113: i32 = 12;
pub const FRAME_ATTAK114: i32 = 13;
pub const FRAME_ATTAK115: i32 = 14;
pub const FRAME_ATTAK116: i32 = 15;
pub const FRAME_ATTAK117: i32 = 16;
pub const FRAME_ATTAK118: i32 = 17;
pub const FRAME_ATTAK201: i32 = 18;
pub const FRAME_ATTAK202: i32 = 19;
pub const FRAME_ATTAK203: i32 = 20;
pub const FRAME_ATTAK204: i32 = 21;
pub const FRAME_ATTAK205: i32 = 22;
pub const FRAME_ATTAK206: i32 = 23;
pub const FRAME_ATTAK207: i32 = 24;
pub const FRAME_ATTAK208: i32 = 25;
pub const FRAME_ATTAK209: i32 = 26;
pub const FRAME_ATTAK210: i32 = 27;
pub const FRAME_ATTAK211: i32 = 28;
pub const FRAME_ATTAK212: i32 = 29;
pub const FRAME_ATTAK213: i32 = 30;
pub const FRAME_DEATH01: i32 = 31;
pub const FRAME_DEATH02: i32 = 32;
pub const FRAME_DEATH03: i32 = 33;
pub const FRAME_DEATH04: i32 = 34;
pub const FRAME_DEATH05: i32 = 35;
pub const FRAME_DEATH06: i32 = 36;
pub const FRAME_DEATH07: i32 = 37;
pub const FRAME_DEATH08: i32 = 38;
pub const FRAME_DEATH09: i32 = 39;
pub const FRAME_DEATH10: i32 = 40;
pub const FRAME_DEATH11: i32 = 41;
pub const FRAME_DEATH12: i32 = 42;
pub const FRAME_DEATH13: i32 = 43;
pub const FRAME_DEATH14: i32 = 44;
pub const FRAME_DEATH15: i32 = 45;
pub const FRAME_DEATH16: i32 = 46;
pub const FRAME_DEATH17: i32 = 47;
pub const FRAME_DEATH18: i32 = 48;
pub const FRAME_DEATH19: i32 = 49;
pub const FRAME_DEATH20: i32 = 50;
pub const FRAME_DEATH21: i32 = 51;
pub const FRAME_DEATH22: i32 = 52;
pub const FRAME_DEATH23: i32 = 53;
pub const FRAME_DEATH24: i32 = 54;
pub const FRAME_DEATH25: i32 = 55;
pub const FRAME_DEATH26: i32 = 56;
pub const FRAME_DEATH27: i32 = 57;
pub const FRAME_DEATH28: i32 = 58;
pub const FRAME_DEATH29: i32 = 59;
pub const FRAME_DEATH30: i32 = 60;
pub const FRAME_DEATH31: i32 = 61;
pub const FRAME_DEATH32: i32 = 62;
pub const FRAME_DEATH33: i32 = 63;
pub const FRAME_DEATH34: i32 = 64;
pub const FRAME_DEATH35: i32 = 65;
pub const FRAME_DEATH36: i32 = 66;
pub const FRAME_DEATH37: i32 = 67;
pub const FRAME_DEATH38: i32 = 68;
pub const FRAME_DEATH39: i32 = 69;
pub const FRAME_DEATH40: i32 = 70;
pub const FRAME_DEATH41: i32 = 71;
pub const FRAME_DEATH42: i32 = 72;
pub const FRAME_DEATH43: i32 = 73;
pub const FRAME_DEATH44: i32 = 74;
pub const FRAME_DEATH45: i32 = 75;
pub const FRAME_DEATH46: i32 = 76;
pub const FRAME_DEATH47: i32 = 77;
pub const FRAME_DEATH48: i32 = 78;
pub const FRAME_DEATH49: i32 = 79;
pub const FRAME_DEATH50: i32 = 80;
pub const FRAME_PAIN101: i32 = 81;
pub const FRAME_PAIN102: i32 = 82;
pub const FRAME_PAIN103: i32 = 83;
pub const FRAME_PAIN201: i32 = 84;
pub const FRAME_PAIN202: i32 = 85;
pub const FRAME_PAIN203: i32 = 86;
pub const FRAME_PAIN301: i32 = 87;
pub const FRAME_PAIN302: i32 = 88;
pub const FRAME_PAIN303: i32 = 89;
pub const FRAME_PAIN304: i32 = 90;
pub const FRAME_PAIN305: i32 = 91;
pub const FRAME_PAIN306: i32 = 92;
pub const FRAME_PAIN307: i32 = 93;
pub const FRAME_PAIN308: i32 = 94;
pub const FRAME_PAIN309: i32 = 95;
pub const FRAME_PAIN310: i32 = 96;
pub const FRAME_PAIN311: i32 = 97;
pub const FRAME_PAIN312: i32 = 98;
pub const FRAME_PAIN313: i32 = 99;
pub const FRAME_PAIN314: i32 = 100;
pub const FRAME_PAIN315: i32 = 101;
pub const FRAME_PAIN316: i32 = 102;
pub const FRAME_PAIN317: i32 = 103;
pub const FRAME_PAIN318: i32 = 104;
pub const FRAME_PAIN319: i32 = 105;
pub const FRAME_PAIN320: i32 = 106;
pub const FRAME_PAIN321: i32 = 107;
pub const FRAME_PAIN322: i32 = 108;
pub const FRAME_PAIN323: i32 = 109;
pub const FRAME_PAIN324: i32 = 110;
pub const FRAME_PAIN325: i32 = 111;
pub const FRAME_STAND01: i32 = 112;
pub const FRAME_STAND02: i32 = 113;
pub const FRAME_STAND03: i32 = 114;
pub const FRAME_STAND04: i32 = 115;
pub const FRAME_STAND05: i32 = 116;
pub const FRAME_STAND06: i32 = 117;
pub const FRAME_STAND07: i32 = 118;
pub const FRAME_STAND08: i32 = 119;
pub const FRAME_STAND09: i32 = 120;
pub const FRAME_STAND10: i32 = 121;
pub const FRAME_STAND11: i32 = 122;
pub const FRAME_STAND12: i32 = 123;
pub const FRAME_STAND13: i32 = 124;
pub const FRAME_STAND14: i32 = 125;
pub const FRAME_STAND15: i32 = 126;
pub const FRAME_STAND16: i32 = 127;
pub const FRAME_STAND17: i32 = 128;
pub const FRAME_STAND18: i32 = 129;
pub const FRAME_STAND19: i32 = 130;
pub const FRAME_STAND20: i32 = 131;
pub const FRAME_STAND21: i32 = 132;
pub const FRAME_STAND22: i32 = 133;
pub const FRAME_STAND23: i32 = 134;
pub const FRAME_STAND24: i32 = 135;
pub const FRAME_STAND25: i32 = 136;
pub const FRAME_STAND26: i32 = 137;
pub const FRAME_STAND27: i32 = 138;
pub const FRAME_STAND28: i32 = 139;
pub const FRAME_STAND29: i32 = 140;
pub const FRAME_STAND30: i32 = 141;
pub const FRAME_STAND31: i32 = 142;
pub const FRAME_STAND32: i32 = 143;
pub const FRAME_STAND33: i32 = 144;
pub const FRAME_STAND34: i32 = 145;
pub const FRAME_STAND35: i32 = 146;
pub const FRAME_STAND36: i32 = 147;
pub const FRAME_STAND37: i32 = 148;
pub const FRAME_STAND38: i32 = 149;
pub const FRAME_STAND39: i32 = 150;
pub const FRAME_STAND40: i32 = 151;
pub const FRAME_STAND41: i32 = 152;
pub const FRAME_STAND42: i32 = 153;
pub const FRAME_STAND43: i32 = 154;
pub const FRAME_STAND44: i32 = 155;
pub const FRAME_STAND45: i32 = 156;
pub const FRAME_STAND46: i32 = 157;
pub const FRAME_STAND47: i32 = 158;
pub const FRAME_STAND48: i32 = 159;
pub const FRAME_STAND49: i32 = 160;
pub const FRAME_STAND50: i32 = 161;
pub const FRAME_STAND51: i32 = 162;
pub const FRAME_WALK01: i32 = 163;
pub const FRAME_WALK02: i32 = 164;
pub const FRAME_WALK03: i32 = 165;
pub const FRAME_WALK04: i32 = 166;
pub const FRAME_WALK05: i32 = 167;
pub const FRAME_WALK06: i32 = 168;
pub const FRAME_WALK07: i32 = 169;
pub const FRAME_WALK08: i32 = 170;
pub const FRAME_WALK09: i32 = 171;
pub const FRAME_WALK10: i32 = 172;
pub const FRAME_WALK11: i32 = 173;
pub const FRAME_WALK12: i32 = 174;
pub const FRAME_WALK13: i32 = 175;
pub const FRAME_WALK14: i32 = 176;
pub const FRAME_WALK15: i32 = 177;
pub const FRAME_WALK16: i32 = 178;
pub const FRAME_WALK17: i32 = 179;
pub const FRAME_WALK18: i32 = 180;
pub const FRAME_WALK19: i32 = 181;
pub const FRAME_WALK20: i32 = 182;
pub const FRAME_WALK21: i32 = 183;
pub const FRAME_WALK22: i32 = 184;
pub const FRAME_WALK23: i32 = 185;
pub const FRAME_WALK24: i32 = 186;
pub const FRAME_WALK25: i32 = 187;
pub const FRAME_ACTIVE01: i32 = 188;
pub const FRAME_ACTIVE02: i32 = 189;
pub const FRAME_ACTIVE03: i32 = 190;
pub const FRAME_ACTIVE04: i32 = 191;
pub const FRAME_ACTIVE05: i32 = 192;
pub const FRAME_ACTIVE06: i32 = 193;
pub const FRAME_ACTIVE07: i32 = 194;
pub const FRAME_ACTIVE08: i32 = 195;
pub const FRAME_ACTIVE09: i32 = 196;
pub const FRAME_ACTIVE10: i32 = 197;
pub const FRAME_ACTIVE11: i32 = 198;
pub const FRAME_ACTIVE12: i32 = 199;
pub const FRAME_ACTIVE13: i32 = 200;
pub const FRAME_ATTAK301: i32 = 201;
pub const FRAME_ATTAK302: i32 = 202;
pub const FRAME_ATTAK303: i32 = 203;
pub const FRAME_ATTAK304: i32 = 204;
pub const FRAME_ATTAK305: i32 = 205;
pub const FRAME_ATTAK306: i32 = 206;
pub const FRAME_ATTAK307: i32 = 207;
pub const FRAME_ATTAK308: i32 = 208;
pub const FRAME_ATTAK401: i32 = 209;
pub const FRAME_ATTAK402: i32 = 210;
pub const FRAME_ATTAK403: i32 = 211;
pub const FRAME_ATTAK404: i32 = 212;
pub const FRAME_ATTAK405: i32 = 213;
pub const FRAME_ATTAK406: i32 = 214;
pub const FRAME_ATTAK407: i32 = 215;
pub const FRAME_ATTAK408: i32 = 216;
pub const FRAME_ATTAK409: i32 = 217;
pub const FRAME_ATTAK410: i32 = 218;
pub const FRAME_ATTAK411: i32 = 219;
pub const FRAME_ATTAK412: i32 = 220;
pub const FRAME_ATTAK413: i32 = 221;
pub const FRAME_ATTAK414: i32 = 222;
pub const FRAME_ATTAK415: i32 = 223;
pub const FRAME_ATTAK416: i32 = 224;
pub const FRAME_ATTAK417: i32 = 225;
pub const FRAME_ATTAK418: i32 = 226;
pub const FRAME_ATTAK419: i32 = 227;
pub const FRAME_ATTAK420: i32 = 228;
pub const FRAME_ATTAK421: i32 = 229;
pub const FRAME_ATTAK422: i32 = 230;
pub const FRAME_ATTAK423: i32 = 231;
pub const FRAME_ATTAK424: i32 = 232;
pub const FRAME_ATTAK425: i32 = 233;
pub const FRAME_ATTAK426: i32 = 234;
pub const FRAME_ATTAK501: i32 = 235;
pub const FRAME_ATTAK502: i32 = 236;
pub const FRAME_ATTAK503: i32 = 237;
pub const FRAME_ATTAK504: i32 = 238;
pub const FRAME_ATTAK505: i32 = 239;
pub const FRAME_ATTAK506: i32 = 240;
pub const FRAME_ATTAK507: i32 = 241;
pub const FRAME_ATTAK508: i32 = 242;
pub const FRAME_ATTAK509: i32 = 243;
pub const FRAME_ATTAK510: i32 = 244;
pub const FRAME_ATTAK511: i32 = 245;
pub const FRAME_ATTAK512: i32 = 246;
pub const FRAME_ATTAK513: i32 = 247;
pub const FRAME_ATTAK514: i32 = 248;
pub const FRAME_ATTAK515: i32 = 249;
pub const FRAME_ATTAK516: i32 = 250;
pub const FRAME_DEATH201: i32 = 251;
pub const FRAME_DEATH202: i32 = 252;
pub const FRAME_DEATH203: i32 = 253;
pub const FRAME_DEATH204: i32 = 254;
pub const FRAME_DEATH205: i32 = 255;
pub const FRAME_DEATH206: i32 = 256;
pub const FRAME_DEATH207: i32 = 257;
pub const FRAME_DEATH208: i32 = 258;
pub const FRAME_DEATH209: i32 = 259;
pub const FRAME_DEATH210: i32 = 260;
pub const FRAME_DEATH211: i32 = 261;
pub const FRAME_DEATH212: i32 = 262;
pub const FRAME_DEATH213: i32 = 263;
pub const FRAME_DEATH214: i32 = 264;
pub const FRAME_DEATH215: i32 = 265;
pub const FRAME_DEATH216: i32 = 266;
pub const FRAME_DEATH217: i32 = 267;
pub const FRAME_DEATH218: i32 = 268;
pub const FRAME_DEATH219: i32 = 269;
pub const FRAME_DEATH220: i32 = 270;
pub const FRAME_DEATH221: i32 = 271;
pub const FRAME_DEATH222: i32 = 272;
pub const FRAME_DEATH223: i32 = 273;
pub const FRAME_DEATH224: i32 = 274;
pub const FRAME_DEATH225: i32 = 275;
pub const FRAME_DEATH226: i32 = 276;
pub const FRAME_DEATH227: i32 = 277;
pub const FRAME_DEATH228: i32 = 278;
pub const FRAME_DEATH229: i32 = 279;
pub const FRAME_DEATH230: i32 = 280;
pub const FRAME_DEATH231: i32 = 281;
pub const FRAME_DEATH232: i32 = 282;
pub const FRAME_DEATH233: i32 = 283;
pub const FRAME_DEATH234: i32 = 284;
pub const FRAME_DEATH235: i32 = 285;
pub const FRAME_DEATH236: i32 = 286;
pub const FRAME_DEATH237: i32 = 287;
pub const FRAME_DEATH238: i32 = 288;
pub const FRAME_DEATH239: i32 = 289;
pub const FRAME_DEATH240: i32 = 290;
pub const FRAME_DEATH241: i32 = 291;
pub const FRAME_DEATH242: i32 = 292;
pub const FRAME_DEATH243: i32 = 293;
pub const FRAME_DEATH244: i32 = 294;
pub const FRAME_DEATH245: i32 = 295;
pub const FRAME_DEATH246: i32 = 296;
pub const FRAME_DEATH247: i32 = 297;
pub const FRAME_DEATH248: i32 = 298;
pub const FRAME_DEATH249: i32 = 299;
pub const FRAME_DEATH250: i32 = 300;
pub const FRAME_DEATH251: i32 = 301;
pub const FRAME_DEATH252: i32 = 302;
pub const FRAME_DEATH253: i32 = 303;
pub const FRAME_DEATH254: i32 = 304;
pub const FRAME_DEATH255: i32 = 305;
pub const FRAME_DEATH256: i32 = 306;
pub const FRAME_DEATH257: i32 = 307;
pub const FRAME_DEATH258: i32 = 308;
pub const FRAME_DEATH259: i32 = 309;
pub const FRAME_DEATH260: i32 = 310;
pub const FRAME_DEATH261: i32 = 311;
pub const FRAME_DEATH262: i32 = 312;
pub const FRAME_DEATH263: i32 = 313;
pub const FRAME_DEATH264: i32 = 314;
pub const FRAME_DEATH265: i32 = 315;
pub const FRAME_DEATH266: i32 = 316;
pub const FRAME_DEATH267: i32 = 317;
pub const FRAME_DEATH268: i32 = 318;
pub const FRAME_DEATH269: i32 = 319;
pub const FRAME_DEATH270: i32 = 320;
pub const FRAME_DEATH271: i32 = 321;
pub const FRAME_DEATH272: i32 = 322;
pub const FRAME_DEATH273: i32 = 323;
pub const FRAME_DEATH274: i32 = 324;
pub const FRAME_DEATH275: i32 = 325;
pub const FRAME_DEATH276: i32 = 326;
pub const FRAME_DEATH277: i32 = 327;
pub const FRAME_DEATH278: i32 = 328;
pub const FRAME_DEATH279: i32 = 329;
pub const FRAME_DEATH280: i32 = 330;
pub const FRAME_DEATH281: i32 = 331;
pub const FRAME_DEATH282: i32 = 332;
pub const FRAME_DEATH283: i32 = 333;
pub const FRAME_DEATH284: i32 = 334;
pub const FRAME_DEATH285: i32 = 335;
pub const FRAME_DEATH286: i32 = 336;
pub const FRAME_DEATH287: i32 = 337;
pub const FRAME_DEATH288: i32 = 338;
pub const FRAME_DEATH289: i32 = 339;
pub const FRAME_DEATH290: i32 = 340;
pub const FRAME_DEATH291: i32 = 341;
pub const FRAME_DEATH292: i32 = 342;
pub const FRAME_DEATH293: i32 = 343;
pub const FRAME_DEATH294: i32 = 344;
pub const FRAME_DEATH295: i32 = 345;
pub const FRAME_DEATH301: i32 = 346;
pub const FRAME_DEATH302: i32 = 347;
pub const FRAME_DEATH303: i32 = 348;
pub const FRAME_DEATH304: i32 = 349;
pub const FRAME_DEATH305: i32 = 350;
pub const FRAME_DEATH306: i32 = 351;
pub const FRAME_DEATH307: i32 = 352;
pub const FRAME_DEATH308: i32 = 353;
pub const FRAME_DEATH309: i32 = 354;
pub const FRAME_DEATH310: i32 = 355;
pub const FRAME_DEATH311: i32 = 356;
pub const FRAME_DEATH312: i32 = 357;
pub const FRAME_DEATH313: i32 = 358;
pub const FRAME_DEATH314: i32 = 359;
pub const FRAME_DEATH315: i32 = 360;
pub const FRAME_DEATH316: i32 = 361;
pub const FRAME_DEATH317: i32 = 362;
pub const FRAME_DEATH318: i32 = 363;
pub const FRAME_DEATH319: i32 = 364;
pub const FRAME_DEATH320: i32 = 365;
pub const FRAME_JUMP01: i32 = 366;
pub const FRAME_JUMP02: i32 = 367;
pub const FRAME_JUMP03: i32 = 368;
pub const FRAME_JUMP04: i32 = 369;
pub const FRAME_JUMP05: i32 = 370;
pub const FRAME_JUMP06: i32 = 371;
pub const FRAME_JUMP07: i32 = 372;
pub const FRAME_JUMP08: i32 = 373;
pub const FRAME_JUMP09: i32 = 374;
pub const FRAME_JUMP10: i32 = 375;
pub const FRAME_JUMP11: i32 = 376;
pub const FRAME_JUMP12: i32 = 377;
pub const FRAME_JUMP13: i32 = 378;
pub const FRAME_PAIN401: i32 = 379;
pub const FRAME_PAIN402: i32 = 380;
pub const FRAME_PAIN403: i32 = 381;
pub const FRAME_PAIN404: i32 = 382;
pub const FRAME_PAIN501: i32 = 383;
pub const FRAME_PAIN502: i32 = 384;
pub const FRAME_PAIN503: i32 = 385;
pub const FRAME_PAIN504: i32 = 386;
pub const FRAME_PAIN601: i32 = 387;
pub const FRAME_PAIN602: i32 = 388;
pub const FRAME_PAIN603: i32 = 389;
pub const FRAME_PAIN604: i32 = 390;
pub const FRAME_PAIN605: i32 = 391;
pub const FRAME_PAIN606: i32 = 392;
pub const FRAME_PAIN607: i32 = 393;
pub const FRAME_PAIN608: i32 = 394;
pub const FRAME_PAIN609: i32 = 395;
pub const FRAME_PAIN610: i32 = 396;
pub const FRAME_PAIN611: i32 = 397;
pub const FRAME_PAIN612: i32 = 398;
pub const FRAME_PAIN613: i32 = 399;
pub const FRAME_PAIN614: i32 = 400;
pub const FRAME_PAIN615: i32 = 401;
pub const FRAME_PAIN616: i32 = 402;
pub const FRAME_PAIN617: i32 = 403;
pub const FRAME_PAIN618: i32 = 404;
pub const FRAME_PAIN619: i32 = 405;
pub const FRAME_PAIN620: i32 = 406;
pub const FRAME_PAIN621: i32 = 407;
pub const FRAME_PAIN622: i32 = 408;
pub const FRAME_PAIN623: i32 = 409;
pub const FRAME_PAIN624: i32 = 410;
pub const FRAME_PAIN625: i32 = 411;
pub const FRAME_PAIN626: i32 = 412;
pub const FRAME_PAIN627: i32 = 413;
pub const FRAME_STAND201: i32 = 414;
pub const FRAME_STAND202: i32 = 415;
pub const FRAME_STAND203: i32 = 416;
pub const FRAME_STAND204: i32 = 417;
pub const FRAME_STAND205: i32 = 418;
pub const FRAME_STAND206: i32 = 419;
pub const FRAME_STAND207: i32 = 420;
pub const FRAME_STAND208: i32 = 421;
pub const FRAME_STAND209: i32 = 422;
pub const FRAME_STAND210: i32 = 423;
pub const FRAME_STAND211: i32 = 424;
pub const FRAME_STAND212: i32 = 425;
pub const FRAME_STAND213: i32 = 426;
pub const FRAME_STAND214: i32 = 427;
pub const FRAME_STAND215: i32 = 428;
pub const FRAME_STAND216: i32 = 429;
pub const FRAME_STAND217: i32 = 430;
pub const FRAME_STAND218: i32 = 431;
pub const FRAME_STAND219: i32 = 432;
pub const FRAME_STAND220: i32 = 433;
pub const FRAME_STAND221: i32 = 434;
pub const FRAME_STAND222: i32 = 435;
pub const FRAME_STAND223: i32 = 436;
pub const FRAME_STAND224: i32 = 437;
pub const FRAME_STAND225: i32 = 438;
pub const FRAME_STAND226: i32 = 439;
pub const FRAME_STAND227: i32 = 440;
pub const FRAME_STAND228: i32 = 441;
pub const FRAME_STAND229: i32 = 442;
pub const FRAME_STAND230: i32 = 443;
pub const FRAME_STAND231: i32 = 444;
pub const FRAME_STAND232: i32 = 445;
pub const FRAME_STAND233: i32 = 446;
pub const FRAME_STAND234: i32 = 447;
pub const FRAME_STAND235: i32 = 448;
pub const FRAME_STAND236: i32 = 449;
pub const FRAME_STAND237: i32 = 450;
pub const FRAME_STAND238: i32 = 451;
pub const FRAME_STAND239: i32 = 452;
pub const FRAME_STAND240: i32 = 453;
pub const FRAME_STAND241: i32 = 454;
pub const FRAME_STAND242: i32 = 455;
pub const FRAME_STAND243: i32 = 456;
pub const FRAME_STAND244: i32 = 457;
pub const FRAME_STAND245: i32 = 458;
pub const FRAME_STAND246: i32 = 459;
pub const FRAME_STAND247: i32 = 460;
pub const FRAME_STAND248: i32 = 461;
pub const FRAME_STAND249: i32 = 462;
pub const FRAME_STAND250: i32 = 463;
pub const FRAME_STAND251: i32 = 464;
pub const FRAME_STAND252: i32 = 465;
pub const FRAME_STAND253: i32 = 466;
pub const FRAME_STAND254: i32 = 467;
pub const FRAME_STAND255: i32 = 468;
pub const FRAME_STAND256: i32 = 469;
pub const FRAME_STAND257: i32 = 470;
pub const FRAME_STAND258: i32 = 471;
pub const FRAME_STAND259: i32 = 472;
pub const FRAME_STAND260: i32 = 473;
pub const FRAME_WALK201: i32 = 474;
pub const FRAME_WALK202: i32 = 475;
pub const FRAME_WALK203: i32 = 476;
pub const FRAME_WALK204: i32 = 477;
pub const FRAME_WALK205: i32 = 478;
pub const FRAME_WALK206: i32 = 479;
pub const FRAME_WALK207: i32 = 480;
pub const FRAME_WALK208: i32 = 481;
pub const FRAME_WALK209: i32 = 482;
pub const FRAME_WALK210: i32 = 483;
pub const FRAME_WALK211: i32 = 484;
pub const FRAME_WALK212: i32 = 485;
pub const FRAME_WALK213: i32 = 486;
pub const FRAME_WALK214: i32 = 487;
pub const FRAME_WALK215: i32 = 488;
pub const FRAME_WALK216: i32 = 489;
pub const FRAME_WALK217: i32 = 490;

pub const MODEL_SCALE: f32 = 1.0;

// ============================================================
// Sound channel / attenuation / content constants (mirrors C defines)
// ============================================================

// CHAN_*, ATTN_*, EF_*, YAW come from g_local::* re-export (myq2_common::q_shared)

use myq2_common::q_shared::{CONTENTS_SOLID, CONTENTS_MONSTER, CONTENTS_SLIME, CONTENTS_LAVA};

// MZ2 flash indices (from q_shared.h)
const MZ2_MAKRON_BFG: usize = 96;
const MZ2_MAKRON_BLASTER_1: usize = 97;
const MZ2_MAKRON_RAILGUN_1: usize = 114;

// AS_* attack state constants come from g_local::*

// ============================================================
// Animation frame type and move type (reuse from m_berserk pattern)
// ============================================================

// MFrame and MMove are defined in g_local via m_berserk pattern; reuse those.
// If not yet centralized, we define local aliases. The types come from g_local::*.

use crate::ai_wrappers::{ai_stand, ai_run, ai_charge, ai_move};
use crate::entity_adapters::{
    gi_sound, gi_soundindex, gi_modelindex, gi_linkentity,
    g_free_edict, walkmonster_start,
    throw_gib, throw_head,
    infront, range,
    monster_fire_bfg, monster_fire_railgun, monster_fire_blaster,
};

// ============================================================
// Sound indices (module-level state, replaces C statics)
// ============================================================

#[derive(Default)]
pub struct MakronSounds {
    pub pain4: i32,
    pub pain5: i32,
    pub pain6: i32,
    pub death: i32,
    pub step_left: i32,
    pub step_right: i32,
    pub attack_bfg: i32,
    pub brainsplorch: i32,
    pub prerailgun: i32,
    pub popup: i32,
    pub taunt1: i32,
    pub taunt2: i32,
    pub taunt3: i32,
    pub hit: i32,
}

static SOUNDS: std::sync::OnceLock<MakronSounds> = std::sync::OnceLock::new();

// ============================================================
// Placeholder helpers (will be wired to gi.* and game functions)
// ============================================================






use crate::g_utils::{vectoyaw, vectoangles};

use myq2_common::q_shared::angle_vectors;


use myq2_common::q_shared::{
    vector_copy_to as vector_copy, vector_subtract, vector_ma,
};


// ============================================================
// Makron behavior functions
// ============================================================

pub fn makron_taunt(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let r = random();
    let (s1, s2, s3) = SOUNDS.get().map_or((0, 0, 0), |s| (s.taunt1, s.taunt2, s.taunt3));
    if r <= 0.3 {
        gi_sound(self_ent, CHAN_AUTO, s1, 1.0, ATTN_NONE, 0.0);
    } else if r <= 0.6 {
        gi_sound(self_ent, CHAN_AUTO, s2, 1.0, ATTN_NONE, 0.0);
    } else {
        gi_sound(self_ent, CHAN_AUTO, s3, 1.0, ATTN_NONE, 0.0);
    }
}

pub fn makron_hit(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let snd = SOUNDS.get().map_or(0, |s| s.hit);
    gi_sound(self_ent, CHAN_AUTO, snd, 1.0, ATTN_NONE, 0.0);
}

pub fn makron_popup(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let snd = SOUNDS.get().map_or(0, |s| s.popup);
    gi_sound(self_ent, CHAN_BODY, snd, 1.0, ATTN_NONE, 0.0);
}

pub fn makron_step_left(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let snd = SOUNDS.get().map_or(0, |s| s.step_left);
    gi_sound(self_ent, CHAN_BODY, snd, 1.0, ATTN_NORM, 0.0);
}

pub fn makron_step_right(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let snd = SOUNDS.get().map_or(0, |s| s.step_right);
    gi_sound(self_ent, CHAN_BODY, snd, 1.0, ATTN_NORM, 0.0);
}

pub fn makron_brainsplorch(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let snd = SOUNDS.get().map_or(0, |s| s.brainsplorch);
    gi_sound(self_ent, CHAN_VOICE, snd, 1.0, ATTN_NORM, 0.0);
}

pub fn makron_prerailgun(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let snd = SOUNDS.get().map_or(0, |s| s.prerailgun);
    gi_sound(self_ent, CHAN_WEAPON, snd, 1.0, ATTN_NORM, 0.0);
}

// ============================================================
// Stand animation
// ============================================================

static MAKRON_FRAMES_STAND: &[MFrame] = &[
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None }, // 10
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None }, // 20
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None }, // 30
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None }, // 40
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None }, // 50
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None }, // 60
];

// Move table index constants
pub const MAKRON_MOVE_STAND_IDX: usize = 0;
pub const MAKRON_MOVE_WALK_IDX: usize = 1;
pub const MAKRON_MOVE_RUN_IDX: usize = 2;
pub const MAKRON_MOVE_ATTACK3_IDX: usize = 3;
pub const MAKRON_MOVE_ATTACK4_IDX: usize = 4;
pub const MAKRON_MOVE_ATTACK5_IDX: usize = 5;
pub const MAKRON_MOVE_SIGHT_IDX: usize = 6;
pub const MAKRON_MOVE_PAIN4_IDX: usize = 7;
pub const MAKRON_MOVE_PAIN5_IDX: usize = 8;
pub const MAKRON_MOVE_PAIN6_IDX: usize = 9;
pub const MAKRON_MOVE_DEATH2_IDX: usize = 10;

pub static MAKRON_MOVE_STAND: MMove = MMove {
    firstframe: FRAME_STAND201,
    lastframe: FRAME_STAND260,
    frames: MAKRON_FRAMES_STAND,
    endfunc: None,
};

pub fn makron_stand(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MAKRON_MOVE_STAND_IDX);
}

// ============================================================
// Run animation
// ============================================================

static MAKRON_FRAMES_RUN: &[MFrame] = &[
    MFrame { ai_fn: ai_run, dist: 3.0,  think_fn: Some(makron_step_left) },
    MFrame { ai_fn: ai_run, dist: 12.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 8.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: 8.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: 8.0,  think_fn: Some(makron_step_right) },
    MFrame { ai_fn: ai_run, dist: 6.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: 12.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 9.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: 6.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: 12.0, think_fn: None },
];

pub static MAKRON_MOVE_RUN: MMove = MMove {
    firstframe: FRAME_WALK204,
    lastframe: FRAME_WALK213,
    frames: MAKRON_FRAMES_RUN,
    endfunc: None,
};

// ============================================================
// Walk animation
// Note: C original uses makron_frames_run for walk move (likely intentional/bug preserved)
// ============================================================

// NOTE: The original C code assigns makron_frames_run (not makron_frames_walk) to makron_move_walk.
// This is faithfully reproduced here.
pub static MAKRON_MOVE_WALK: MMove = MMove {
    firstframe: FRAME_WALK204,
    lastframe: FRAME_WALK213,
    frames: MAKRON_FRAMES_RUN,
    endfunc: None,
};

pub fn makron_walk(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MAKRON_MOVE_WALK_IDX);
}

pub fn makron_run(self_ent: &mut Edict, _ctx: &mut GameContext) {
    if self_ent.monsterinfo.aiflags.intersects(AI_STAND_GROUND) {
        self_ent.monsterinfo.currentmove = Some(MAKRON_MOVE_STAND_IDX);
    } else {
        self_ent.monsterinfo.currentmove = Some(MAKRON_MOVE_RUN_IDX);
    }
}

// ============================================================
// Pain animations
// ============================================================

static MAKRON_FRAMES_PAIN6: &[MFrame] = &[
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None }, // 10
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: Some(makron_popup) },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None }, // 20
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: Some(makron_taunt) },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static MAKRON_MOVE_PAIN6: MMove = MMove {
    firstframe: FRAME_PAIN601,
    lastframe: FRAME_PAIN627,
    frames: MAKRON_FRAMES_PAIN6,
    endfunc: Some(makron_run),
};

static MAKRON_FRAMES_PAIN5: &[MFrame] = &[
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static MAKRON_MOVE_PAIN5: MMove = MMove {
    firstframe: FRAME_PAIN501,
    lastframe: FRAME_PAIN504,
    frames: MAKRON_FRAMES_PAIN5,
    endfunc: Some(makron_run),
};

static MAKRON_FRAMES_PAIN4: &[MFrame] = &[
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static MAKRON_MOVE_PAIN4: MMove = MMove {
    firstframe: FRAME_PAIN401,
    lastframe: FRAME_PAIN404,
    frames: MAKRON_FRAMES_PAIN4,
    endfunc: Some(makron_run),
};

// ============================================================
// Death animations
// ============================================================

static MAKRON_FRAMES_DEATH2: &[MFrame] = &[
    MFrame { ai_fn: ai_move, dist: -15.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 3.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: -12.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: Some(makron_step_left) },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None }, // 10
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 11.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 12.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 11.0,  think_fn: Some(makron_step_right) },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None }, // 20
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None }, // 30
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 5.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 7.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 6.0,   think_fn: Some(makron_step_left) },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: -1.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0,   think_fn: None }, // 40
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None }, // 50
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: -6.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: -4.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: -6.0,  think_fn: Some(makron_step_right) },
    MFrame { ai_fn: ai_move, dist: -4.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: -4.0,  think_fn: Some(makron_step_left) },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None }, // 60
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: -2.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: -5.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: -3.0,  think_fn: Some(makron_step_right) },
    MFrame { ai_fn: ai_move, dist: -8.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: -3.0,  think_fn: Some(makron_step_left) },
    MFrame { ai_fn: ai_move, dist: -7.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: -4.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: -4.0,  think_fn: Some(makron_step_right) }, // 70
    MFrame { ai_fn: ai_move, dist: -6.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: -7.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: Some(makron_step_left) },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None }, // 80
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: -2.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None }, // 90
    MFrame { ai_fn: ai_move, dist: 27.0,  think_fn: Some(makron_hit) },
    MFrame { ai_fn: ai_move, dist: 26.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: Some(makron_brainsplorch) },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,   think_fn: None }, // 95
];

pub static MAKRON_MOVE_DEATH2: MMove = MMove {
    firstframe: FRAME_DEATH201,
    lastframe: FRAME_DEATH295,
    frames: MAKRON_FRAMES_DEATH2,
    endfunc: Some(makron_dead),
};

static MAKRON_FRAMES_DEATH3: &[MFrame] = &[
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static MAKRON_MOVE_DEATH3: MMove = MMove {
    firstframe: FRAME_DEATH301,
    lastframe: FRAME_DEATH320,
    frames: MAKRON_FRAMES_DEATH3,
    endfunc: None,
};

// ============================================================
// Sight animation
// ============================================================

static MAKRON_FRAMES_SIGHT: &[MFrame] = &[
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static MAKRON_MOVE_SIGHT: MMove = MMove {
    firstframe: FRAME_ACTIVE01,
    lastframe: FRAME_ACTIVE13,
    frames: MAKRON_FRAMES_SIGHT,
    endfunc: Some(makron_run),
};

// ============================================================
// Attack functions
// ============================================================

pub fn makron_bfg(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let mut forward = [0.0f32; 3];
    let mut right = [0.0f32; 3];
    let mut start = [0.0f32; 3];
    let mut dir: [f32; 3];
    let mut vec = [0.0f32; 3];

    angle_vectors(&self_ent.s.angles, Some(&mut forward), Some(&mut right), None);
    crate::entity_adapters::g_project_source(&self_ent.s.origin, &crate::entity_adapters::monster_flash_offset(MZ2_MAKRON_BFG as i32), &forward, &right, &mut start);

    // self->enemy->s.origin
    if self_ent.enemy >= 0 {
        let enemy = &_ctx.edicts[self_ent.enemy as usize];
        vector_copy(&enemy.s.origin, &mut vec);
        vec[2] += enemy.viewheight as f32;
    }
    dir = vector_subtract(&vec, &start);
    vector_normalize(&mut dir);
    let snd = SOUNDS.get().map_or(0, |s| s.attack_bfg);
    gi_sound(self_ent, CHAN_VOICE, snd, 1.0, ATTN_NORM, 0.0);
    monster_fire_bfg(self_ent, start, dir, 50, 300, 100, 300.0, MZ2_MAKRON_BFG as i32);
}

pub fn makron_saveloc(self_ent: &mut Edict, _ctx: &mut GameContext) {
    // VectorCopy(self->enemy->s.origin, self->pos1); // save for aiming the shot
    // self->pos1[2] += self->enemy->viewheight;
    if self_ent.enemy >= 0 {
        let enemy = &_ctx.edicts[self_ent.enemy as usize];
        vector_copy(&enemy.s.origin, &mut self_ent.pos1);
        self_ent.pos1[2] += enemy.viewheight as f32;
    }
}

/// NOTE: Known issue from original Q2 - Makron fires from incorrect Z position
pub fn makron_railgun(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let mut start = [0.0f32; 3];
    let mut dir: [f32; 3];
    let mut forward = [0.0f32; 3];
    let mut right = [0.0f32; 3];

    angle_vectors(&self_ent.s.angles, Some(&mut forward), Some(&mut right), None);
    crate::entity_adapters::g_project_source(&self_ent.s.origin, &crate::entity_adapters::monster_flash_offset(MZ2_MAKRON_RAILGUN_1 as i32), &forward, &right, &mut start);

    // calc direction to where we targeted
    dir = vector_subtract(&self_ent.pos1, &start);
    vector_normalize(&mut dir);

    monster_fire_railgun(self_ent, start, dir, 50, 100, MZ2_MAKRON_RAILGUN_1 as i32);
}

/// NOTE: Known issue from original Q2 - Makron hyperblaster fires at incorrect angles
pub fn makron_hyperblaster(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let mut dir = [0.0f32; 3];
    let mut vec = [0.0f32; 3];
    let mut start = [0.0f32; 3];
    let mut forward = [0.0f32; 3];
    let mut right = [0.0f32; 3];

    let flash_number = MZ2_MAKRON_BLASTER_1 + (self_ent.s.frame - FRAME_ATTAK405) as usize;

    angle_vectors(&self_ent.s.angles, Some(&mut forward), Some(&mut right), None);
    crate::entity_adapters::g_project_source(&self_ent.s.origin, &crate::entity_adapters::monster_flash_offset(flash_number as i32), &forward, &right, &mut start);

    if self_ent.enemy > 0 {
        let enemy = &_ctx.edicts[self_ent.enemy as usize];
        vector_copy(&enemy.s.origin, &mut vec);
        vec[2] += enemy.viewheight as f32;
        let temp = vector_subtract(&vec, &start);
        vectoangles(&temp, &mut vec);
        dir[0] = vec[0];
    } else {
        dir[0] = 0.0;
    }

    if self_ent.s.frame <= FRAME_ATTAK413 {
        dir[1] = self_ent.s.angles[1] - 10.0 * (self_ent.s.frame - FRAME_ATTAK413) as f32;
    } else {
        dir[1] = self_ent.s.angles[1] + 10.0 * (self_ent.s.frame - FRAME_ATTAK421) as f32;
    }
    dir[2] = 0.0;

    angle_vectors(&dir, Some(&mut forward), None, None);

    monster_fire_blaster(self_ent, start, forward, 15, 1000, MZ2_MAKRON_BLASTER_1 as i32, EF_BLASTER as i32);
}

// ============================================================
// Attack animations
// ============================================================

static MAKRON_FRAMES_ATTACK3: &[MFrame] = &[
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(makron_bfg) }, // BFG attack frame
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: None },
];

pub static MAKRON_MOVE_ATTACK3: MMove = MMove {
    firstframe: FRAME_ATTAK301,
    lastframe: FRAME_ATTAK308,
    frames: MAKRON_FRAMES_ATTACK3,
    endfunc: Some(makron_run),
};

static MAKRON_FRAMES_ATTACK4: &[MFrame] = &[
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: Some(makron_hyperblaster) }, // fire
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: Some(makron_hyperblaster) }, // fire
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: Some(makron_hyperblaster) }, // fire
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: Some(makron_hyperblaster) }, // fire
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: Some(makron_hyperblaster) }, // fire
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: Some(makron_hyperblaster) }, // fire
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: Some(makron_hyperblaster) }, // fire
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: Some(makron_hyperblaster) }, // fire
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: Some(makron_hyperblaster) }, // fire
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: Some(makron_hyperblaster) }, // fire
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: Some(makron_hyperblaster) }, // fire
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: Some(makron_hyperblaster) }, // fire
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: Some(makron_hyperblaster) }, // fire
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: Some(makron_hyperblaster) }, // fire
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: Some(makron_hyperblaster) }, // fire
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: Some(makron_hyperblaster) }, // fire
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: Some(makron_hyperblaster) }, // fire
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: None },
];

pub static MAKRON_MOVE_ATTACK4: MMove = MMove {
    firstframe: FRAME_ATTAK401,
    lastframe: FRAME_ATTAK426,
    frames: MAKRON_FRAMES_ATTACK4,
    endfunc: Some(makron_run),
};

static MAKRON_FRAMES_ATTACK5: &[MFrame] = &[
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(makron_prerailgun) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(makron_saveloc) },
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: Some(makron_railgun) }, // Fire railgun
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move,   dist: 0.0, think_fn: None },
];

pub static MAKRON_MOVE_ATTACK5: MMove = MMove {
    firstframe: FRAME_ATTAK501,
    lastframe: FRAME_ATTAK516,
    frames: MAKRON_FRAMES_ATTACK5,
    endfunc: Some(makron_run),
};

// ============================================================
// Pain
// ============================================================

pub fn makron_pain(self_ent: &mut Edict, _other_idx: Option<usize>, _kick: f32, damage: i32, ctx: &mut GameContext) {
    if self_ent.health < (self_ent.max_health / 2) {
        self_ent.s.skinnum = 1;
    }

    if ctx.level.time < self_ent.pain_debounce_time {
        return;
    }

    // Lessen the chance of him going into his pain frames
    if damage <= 25
        && random() < 0.2 {
            return;
        }

    self_ent.pain_debounce_time = ctx.level.time + 3.0;
    if ctx.skill == 3.0 {
        return; // no pain anims in nightmare
    }

    if damage <= 40 {
        let snd = SOUNDS.get().map_or(0, |s| s.pain4);
        gi_sound(self_ent, CHAN_VOICE, snd, 1.0, ATTN_NONE, 0.0);
        self_ent.monsterinfo.currentmove = Some(MAKRON_MOVE_PAIN4_IDX);
    } else if damage <= 110 {
        let snd = SOUNDS.get().map_or(0, |s| s.pain5);
        gi_sound(self_ent, CHAN_VOICE, snd, 1.0, ATTN_NONE, 0.0);
        self_ent.monsterinfo.currentmove = Some(MAKRON_MOVE_PAIN5_IDX);
    } else {
        // NOTE: The original C code has a subtle indentation bug here where
        // the else clause binds to the inner if when damage <= 150.
        // We preserve the exact same behavior.
        if damage <= 150 {
            if random() <= 0.45 {
                let snd = SOUNDS.get().map_or(0, |s| s.pain6);
                gi_sound(self_ent, CHAN_VOICE, snd, 1.0, ATTN_NONE, 0.0);
                self_ent.monsterinfo.currentmove = Some(MAKRON_MOVE_PAIN6_IDX);
            }
        } else if random() <= 0.35 {
            let snd = SOUNDS.get().map_or(0, |s| s.pain6);
            gi_sound(self_ent, CHAN_VOICE, snd, 1.0, ATTN_NONE, 0.0);
            self_ent.monsterinfo.currentmove = Some(MAKRON_MOVE_PAIN6_IDX);
        }
    }
}

// ============================================================
// Sight
// ============================================================

pub fn makron_sight(self_ent: &mut Edict, _other_idx: Option<usize>, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MAKRON_MOVE_SIGHT_IDX);
}

// ============================================================
// Attack
// ============================================================

pub fn makron_attack(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let r = random();

    // vec3_t vec; float range;
    // VectorSubtract(self->enemy->s.origin, self->s.origin, vec);
    // range = VectorLength(vec);
    // range is computed but unused in the original C code

    if r <= 0.3 {
        self_ent.monsterinfo.currentmove = Some(MAKRON_MOVE_ATTACK3_IDX);
    } else if r <= 0.6 {
        self_ent.monsterinfo.currentmove = Some(MAKRON_MOVE_ATTACK4_IDX);
    } else {
        self_ent.monsterinfo.currentmove = Some(MAKRON_MOVE_ATTACK5_IDX);
    }
}

// ============================================================
// Torso (spawned on death)
// ============================================================

pub fn makron_torso_think(self_ent: &mut Edict, ctx: &mut GameContext) {
    self_ent.s.frame += 1;
    if self_ent.s.frame < 365 {
        self_ent.nextthink = ctx.level.time + FRAMETIME;
    } else {
        self_ent.s.frame = 346;
        self_ent.nextthink = ctx.level.time + FRAMETIME;
    }
}

pub fn makron_torso(ent: &mut Edict, level_time: f32) {
    ent.movetype = MoveType::None;
    ent.solid = Solid::Not;
    vector_set(&mut ent.mins, -8.0, -8.0, 0.0);
    vector_set(&mut ent.maxs, 8.0, 8.0, 8.0);
    ent.s.frame = 346;
    ent.s.modelindex = gi_modelindex("models/monsters/boss3/rider/tris.md2");
    // ent->think = makron_torso_think;
    ent.nextthink = level_time + 2.0 * FRAMETIME;
    ent.s.sound = gi_soundindex("makron/spine.wav");
    gi_linkentity(ent);
}

// ============================================================
// Death
// ============================================================

pub fn makron_dead(self_ent: &mut Edict, _ctx: &mut GameContext) {
    vector_set(&mut self_ent.mins, -60.0, -60.0, 0.0);
    vector_set(&mut self_ent.maxs, 60.0, 60.0, 72.0);
    self_ent.movetype = MoveType::Toss;
    self_ent.svflags |= SVF_DEADMONSTER;
    self_ent.nextthink = 0.0;
    gi_linkentity(self_ent);
}

pub fn makron_die(self_ent: &mut Edict, _inflictor_idx: Option<usize>, _attacker_idx: Option<usize>, damage: i32, _point: [f32; 3], _ctx: &mut GameContext) {
    self_ent.s.sound = 0;

    // check for gib
    if self_ent.health <= self_ent.gib_health {
        gi_sound(self_ent, CHAN_VOICE, gi_soundindex("misc/udeath.wav"), 1.0, ATTN_NORM, 0.0);
        for _n in 0..1 /* 4 */ {
            throw_gib(self_ent, "models/objects/gibs/sm_meat/tris.md2", damage, GIB_ORGANIC);
        }
        for _n in 0..4 {
            throw_gib(self_ent, "models/objects/gibs/sm_metal/tris.md2", damage, GIB_METALLIC);
        }
        throw_head(self_ent, "models/objects/gibs/gear/tris.md2", damage, GIB_METALLIC);
        self_ent.deadflag = DEAD_DEAD;
        return;
    }

    if self_ent.deadflag == DEAD_DEAD {
        return;
    }

    // regular death
    let snd = SOUNDS.get().map_or(0, |s| s.death);
    gi_sound(self_ent, CHAN_VOICE, snd, 1.0, ATTN_NONE, 0.0);
    self_ent.deadflag = DEAD_DEAD;
    self_ent.takedamage = Damage::Yes as i32;

    // Spawn torso entity
    let tempent_idx = crate::g_utils::g_spawn(_ctx);
    _ctx.edicts[tempent_idx].s.origin = self_ent.s.origin;
    _ctx.edicts[tempent_idx].s.angles = self_ent.s.angles;
    _ctx.edicts[tempent_idx].s.origin[1] -= 84.0;
    makron_torso(&mut _ctx.edicts[tempent_idx], _ctx.level.time);

    self_ent.monsterinfo.currentmove = Some(MAKRON_MOVE_DEATH2_IDX);
}

// ============================================================
// Makron_CheckAttack
// ============================================================

pub fn makron_check_attack(self_ent: &mut Edict, ctx: &mut GameContext) -> bool {
    let mut spot1 = [0.0f32; 3];
    let mut spot2 = [0.0f32; 3];
    
    let chance: f32;
    
    
    

    let enemy_idx = self_ent.enemy;
    if enemy_idx <= 0 {
        return false;
    }
    let enemy = &ctx.edicts[enemy_idx as usize];

    if enemy.health > 0 {
        // see if any entities are in the way of the shot
        vector_copy(&self_ent.s.origin, &mut spot1);
        spot1[2] += self_ent.viewheight as f32;
        vector_copy(&enemy.s.origin, &mut spot2);
        spot2[2] += enemy.viewheight as f32;

        let self_idx = self_ent.s.number as usize;
        let tr = crate::game_import::gi_trace(&spot1, &[0.0; 3], &[0.0; 3], &spot2, self_idx as i32, CONTENTS_SOLID | CONTENTS_MONSTER | CONTENTS_SLIME | CONTENTS_LAVA);

        // do we have a clear shot?
        if tr.ent_index >= 0 && tr.ent_index != enemy_idx as i32 {
            return false;
        }
    }

    let enemy_infront: bool = infront(self_ent, enemy);
    let enemy_range: i32 = range(self_ent, enemy);
    let temp = vector_subtract(&enemy.s.origin, &self_ent.s.origin);
    let enemy_yaw: f32 = vectoyaw(&temp);

    self_ent.ideal_yaw = enemy_yaw;

    // melee attack
    if enemy_range == RANGE_MELEE {
        if self_ent.monsterinfo.melee_fn.is_some() {
            self_ent.monsterinfo.attack_state = AS_MELEE;
        } else {
            self_ent.monsterinfo.attack_state = AS_MISSILE;
        }
        return true;
    }

    // missile attack
    if self_ent.monsterinfo.attack_fn.is_none() {
        return false;
    }

    if ctx.level.time < self_ent.monsterinfo.attack_finished {
        return false;
    }

    if enemy_range == RANGE_FAR {
        return false;
    }

    if self_ent.monsterinfo.aiflags.intersects(AI_STAND_GROUND) {
        chance = 0.4;
    } else if enemy_range == RANGE_MELEE {
        chance = 0.8;
    } else if enemy_range == RANGE_NEAR {
        chance = 0.4;
    } else if enemy_range == RANGE_MID {
        chance = 0.2;
    } else {
        return false;
    }

    if random() < chance {
        self_ent.monsterinfo.attack_state = AS_MISSILE;
        self_ent.monsterinfo.attack_finished = ctx.level.time + 2.0 * random();
        return true;
    }

    if self_ent.flags.intersects(FL_FLY) {
        if random() < 0.3 {
            self_ent.monsterinfo.attack_state = AS_SLIDING;
        } else {
            self_ent.monsterinfo.attack_state = AS_STRAIGHT;
        }
    }

    false
}

// ============================================================
// Precache
// ============================================================

pub fn makron_precache() {
    SOUNDS.get_or_init(|| MakronSounds {
        pain4: gi_soundindex("makron/pain3.wav"),
        pain5: gi_soundindex("makron/pain2.wav"),
        pain6: gi_soundindex("makron/pain1.wav"),
        death: gi_soundindex("makron/death.wav"),
        step_left: gi_soundindex("makron/step1.wav"),
        step_right: gi_soundindex("makron/step2.wav"),
        attack_bfg: gi_soundindex("makron/bfg_fire.wav"),
        brainsplorch: gi_soundindex("makron/brain1.wav"),
        prerailgun: gi_soundindex("makron/rail_up.wav"),
        popup: gi_soundindex("makron/popup.wav"),
        taunt1: gi_soundindex("makron/voice4.wav"),
        taunt2: gi_soundindex("makron/voice3.wav"),
        taunt3: gi_soundindex("makron/voice.wav"),
        hit: gi_soundindex("makron/bhit.wav"),
    });

    gi_modelindex("models/monsters/boss3/rider/tris.md2");
}

// ============================================================
// SP_monster_makron
// ============================================================

/// QUAKED monster_makron (1 .5 0) (-30 -30 0) (30 30 90) Ambush Trigger_Spawn Sight
pub fn sp_monster_makron(self_ent: &mut Edict, ctx: &mut GameContext) {
    if ctx.deathmatch != 0.0 {
        g_free_edict(self_ent);
        return;
    }

    makron_precache();

    self_ent.movetype = MoveType::Step;
    self_ent.solid = Solid::Bbox;
    self_ent.s.modelindex = gi_modelindex("models/monsters/boss3/rider/tris.md2");
    vector_set(&mut self_ent.mins, -30.0, -30.0, 0.0);
    vector_set(&mut self_ent.maxs, 30.0, 30.0, 90.0);

    self_ent.health = 3000;
    self_ent.gib_health = -2000;
    self_ent.mass = 500;

    self_ent.pain_fn = Some(crate::dispatch::PAIN_MAKRON);
    self_ent.die_fn = Some(crate::dispatch::DIE_MAKRON);

    self_ent.monsterinfo.stand_fn = Some(crate::dispatch::MSTAND_MAKRON);
    self_ent.monsterinfo.walk_fn = Some(crate::dispatch::MWALK_MAKRON);
    self_ent.monsterinfo.run_fn = Some(crate::dispatch::MRUN_MAKRON);
    self_ent.monsterinfo.dodge_fn = None;
    self_ent.monsterinfo.attack_fn = Some(crate::dispatch::MATTACK_MAKRON);
    self_ent.monsterinfo.melee_fn = None;
    self_ent.monsterinfo.sight_fn = Some(crate::dispatch::MSIGHT_MAKRON);
    self_ent.monsterinfo.checkattack_fn = Some(crate::dispatch::MCHECKATTACK_MAKRON);

    gi_linkentity(self_ent);

    // self->monsterinfo.currentmove = &makron_move_stand;
    self_ent.monsterinfo.currentmove = Some(MAKRON_MOVE_SIGHT_IDX);
    self_ent.monsterinfo.scale = MODEL_SCALE;

    walkmonster_start(self_ent);
}

// ============================================================
// MakronSpawn — called when Jorg dies to spawn the Makron
// ============================================================

pub fn makron_spawn(self_ent: &mut Edict, _ctx: &mut GameContext) {
    sp_monster_makron(self_ent, _ctx);

    // jump at player
    let sight_client = _ctx.level.sight_client;
    if sight_client >= 0 {
        let player_origin = _ctx.edicts[sight_client as usize].s.origin;
        let mut vec = vector_subtract(&player_origin, &self_ent.s.origin);
        self_ent.s.angles[YAW] = vectoyaw(&vec);
        vector_normalize(&mut vec);
        self_ent.velocity = vector_ma(&[0.0; 3], 400.0, &vec);
        self_ent.velocity[2] = 200.0;
        self_ent.groundentity = -1;
    }
}

// ============================================================
// MakronToss — Jorg is about dead, set up to launch Makron out
// ============================================================

pub fn makron_toss(_self_ent: &mut Edict, _ctx: &mut GameContext) {
    // Find a free edict slot for the spawned Makron
    let mut ent_idx = 0;
    for i in 1.._ctx.edicts.len() {
        if !_ctx.edicts[i].inuse {
            ent_idx = i;
            break;
        }
    }
    if ent_idx == 0 && _ctx.edicts.len() < 1024 {
        _ctx.edicts.push(Edict::default());
        ent_idx = _ctx.edicts.len() - 1;
    }
    if ent_idx > 0 {
        _ctx.edicts[ent_idx].inuse = true;
        _ctx.edicts[ent_idx].nextthink = _ctx.level.time + 0.8;
        // ent->think = MakronSpawn; (will be dispatched by the think system)
        _ctx.edicts[ent_idx].target = _self_ent.target.clone();
        _ctx.edicts[ent_idx].s.origin = _self_ent.s.origin;
    }
}
