// m_brain.rs — Brain monster
// Converted from: myq2-original/game/m_brain.c + m_brain.h

use crate::g_local::{
    Edict, LevelLocals, MoveType, MFrame, MMove, GameContext,
    MELEE_DISTANCE,
    DEAD_DEAD, DAMAGE_YES, DAMAGE_AIM,
    AI_STAND_GROUND, AI_DUCKED, AI_HOLD_FRAME,
    POWER_ARMOR_NONE, POWER_ARMOR_SCREEN,
    GIB_ORGANIC,
};
use crate::game::SVF_DEADMONSTER;
use myq2_common::q_shared::{Vec3, CHAN_AUTO, CHAN_VOICE, CHAN_BODY, CHAN_WEAPON, ATTN_NORM, ATTN_IDLE};
use myq2_common::common::frand;

// ============================================================
// Frame definitions (from m_brain.h — generated by ModelGen)
// ============================================================

pub const FRAME_WALK101: i32 = 0;
pub const FRAME_WALK102: i32 = 1;
pub const FRAME_WALK103: i32 = 2;
pub const FRAME_WALK104: i32 = 3;
pub const FRAME_WALK105: i32 = 4;
pub const FRAME_WALK106: i32 = 5;
pub const FRAME_WALK107: i32 = 6;
pub const FRAME_WALK108: i32 = 7;
pub const FRAME_WALK109: i32 = 8;
pub const FRAME_WALK110: i32 = 9;
pub const FRAME_WALK111: i32 = 10;
pub const FRAME_WALK112: i32 = 11;
pub const FRAME_WALK113: i32 = 12;
pub const FRAME_WALK201: i32 = 13;
pub const FRAME_WALK202: i32 = 14;
pub const FRAME_WALK203: i32 = 15;
pub const FRAME_WALK204: i32 = 16;
pub const FRAME_WALK205: i32 = 17;
pub const FRAME_WALK206: i32 = 18;
pub const FRAME_WALK207: i32 = 19;
pub const FRAME_WALK208: i32 = 20;
pub const FRAME_WALK209: i32 = 21;
pub const FRAME_WALK210: i32 = 22;
pub const FRAME_WALK211: i32 = 23;
pub const FRAME_WALK212: i32 = 24;
pub const FRAME_WALK213: i32 = 25;
pub const FRAME_WALK214: i32 = 26;
pub const FRAME_WALK215: i32 = 27;
pub const FRAME_WALK216: i32 = 28;
pub const FRAME_WALK217: i32 = 29;
pub const FRAME_WALK218: i32 = 30;
pub const FRAME_WALK219: i32 = 31;
pub const FRAME_WALK220: i32 = 32;
pub const FRAME_WALK221: i32 = 33;
pub const FRAME_WALK222: i32 = 34;
pub const FRAME_WALK223: i32 = 35;
pub const FRAME_WALK224: i32 = 36;
pub const FRAME_WALK225: i32 = 37;
pub const FRAME_WALK226: i32 = 38;
pub const FRAME_WALK227: i32 = 39;
pub const FRAME_WALK228: i32 = 40;
pub const FRAME_WALK229: i32 = 41;
pub const FRAME_WALK230: i32 = 42;
pub const FRAME_WALK231: i32 = 43;
pub const FRAME_WALK232: i32 = 44;
pub const FRAME_WALK233: i32 = 45;
pub const FRAME_WALK234: i32 = 46;
pub const FRAME_WALK235: i32 = 47;
pub const FRAME_WALK236: i32 = 48;
pub const FRAME_WALK237: i32 = 49;
pub const FRAME_WALK238: i32 = 50;
pub const FRAME_WALK239: i32 = 51;
pub const FRAME_WALK240: i32 = 52;
pub const FRAME_ATTAK101: i32 = 53;
pub const FRAME_ATTAK102: i32 = 54;
pub const FRAME_ATTAK103: i32 = 55;
pub const FRAME_ATTAK104: i32 = 56;
pub const FRAME_ATTAK105: i32 = 57;
pub const FRAME_ATTAK106: i32 = 58;
pub const FRAME_ATTAK107: i32 = 59;
pub const FRAME_ATTAK108: i32 = 60;
pub const FRAME_ATTAK109: i32 = 61;
pub const FRAME_ATTAK110: i32 = 62;
pub const FRAME_ATTAK111: i32 = 63;
pub const FRAME_ATTAK112: i32 = 64;
pub const FRAME_ATTAK113: i32 = 65;
pub const FRAME_ATTAK114: i32 = 66;
pub const FRAME_ATTAK115: i32 = 67;
pub const FRAME_ATTAK116: i32 = 68;
pub const FRAME_ATTAK117: i32 = 69;
pub const FRAME_ATTAK118: i32 = 70;
pub const FRAME_ATTAK201: i32 = 71;
pub const FRAME_ATTAK202: i32 = 72;
pub const FRAME_ATTAK203: i32 = 73;
pub const FRAME_ATTAK204: i32 = 74;
pub const FRAME_ATTAK205: i32 = 75;
pub const FRAME_ATTAK206: i32 = 76;
pub const FRAME_ATTAK207: i32 = 77;
pub const FRAME_ATTAK208: i32 = 78;
pub const FRAME_ATTAK209: i32 = 79;
pub const FRAME_ATTAK210: i32 = 80;
pub const FRAME_ATTAK211: i32 = 81;
pub const FRAME_ATTAK212: i32 = 82;
pub const FRAME_ATTAK213: i32 = 83;
pub const FRAME_ATTAK214: i32 = 84;
pub const FRAME_ATTAK215: i32 = 85;
pub const FRAME_ATTAK216: i32 = 86;
pub const FRAME_ATTAK217: i32 = 87;
pub const FRAME_PAIN101: i32 = 88;
pub const FRAME_PAIN102: i32 = 89;
pub const FRAME_PAIN103: i32 = 90;
pub const FRAME_PAIN104: i32 = 91;
pub const FRAME_PAIN105: i32 = 92;
pub const FRAME_PAIN106: i32 = 93;
pub const FRAME_PAIN107: i32 = 94;
pub const FRAME_PAIN108: i32 = 95;
pub const FRAME_PAIN109: i32 = 96;
pub const FRAME_PAIN110: i32 = 97;
pub const FRAME_PAIN111: i32 = 98;
pub const FRAME_PAIN112: i32 = 99;
pub const FRAME_PAIN113: i32 = 100;
pub const FRAME_PAIN114: i32 = 101;
pub const FRAME_PAIN115: i32 = 102;
pub const FRAME_PAIN116: i32 = 103;
pub const FRAME_PAIN117: i32 = 104;
pub const FRAME_PAIN118: i32 = 105;
pub const FRAME_PAIN119: i32 = 106;
pub const FRAME_PAIN120: i32 = 107;
pub const FRAME_PAIN121: i32 = 108;
pub const FRAME_PAIN201: i32 = 109;
pub const FRAME_PAIN202: i32 = 110;
pub const FRAME_PAIN203: i32 = 111;
pub const FRAME_PAIN204: i32 = 112;
pub const FRAME_PAIN205: i32 = 113;
pub const FRAME_PAIN206: i32 = 114;
pub const FRAME_PAIN207: i32 = 115;
pub const FRAME_PAIN208: i32 = 116;
pub const FRAME_PAIN301: i32 = 117;
pub const FRAME_PAIN302: i32 = 118;
pub const FRAME_PAIN303: i32 = 119;
pub const FRAME_PAIN304: i32 = 120;
pub const FRAME_PAIN305: i32 = 121;
pub const FRAME_PAIN306: i32 = 122;
pub const FRAME_DEATH101: i32 = 123;
pub const FRAME_DEATH102: i32 = 124;
pub const FRAME_DEATH103: i32 = 125;
pub const FRAME_DEATH104: i32 = 126;
pub const FRAME_DEATH105: i32 = 127;
pub const FRAME_DEATH106: i32 = 128;
pub const FRAME_DEATH107: i32 = 129;
pub const FRAME_DEATH108: i32 = 130;
pub const FRAME_DEATH109: i32 = 131;
pub const FRAME_DEATH110: i32 = 132;
pub const FRAME_DEATH111: i32 = 133;
pub const FRAME_DEATH112: i32 = 134;
pub const FRAME_DEATH113: i32 = 135;
pub const FRAME_DEATH114: i32 = 136;
pub const FRAME_DEATH115: i32 = 137;
pub const FRAME_DEATH116: i32 = 138;
pub const FRAME_DEATH117: i32 = 139;
pub const FRAME_DEATH118: i32 = 140;
pub const FRAME_DEATH201: i32 = 141;
pub const FRAME_DEATH202: i32 = 142;
pub const FRAME_DEATH203: i32 = 143;
pub const FRAME_DEATH204: i32 = 144;
pub const FRAME_DEATH205: i32 = 145;
pub const FRAME_DUCK01: i32 = 146;
pub const FRAME_DUCK02: i32 = 147;
pub const FRAME_DUCK03: i32 = 148;
pub const FRAME_DUCK04: i32 = 149;
pub const FRAME_DUCK05: i32 = 150;
pub const FRAME_DUCK06: i32 = 151;
pub const FRAME_DUCK07: i32 = 152;
pub const FRAME_DUCK08: i32 = 153;
pub const FRAME_DEFENS01: i32 = 154;
pub const FRAME_DEFENS02: i32 = 155;
pub const FRAME_DEFENS03: i32 = 156;
pub const FRAME_DEFENS04: i32 = 157;
pub const FRAME_DEFENS05: i32 = 158;
pub const FRAME_DEFENS06: i32 = 159;
pub const FRAME_DEFENS07: i32 = 160;
pub const FRAME_DEFENS08: i32 = 161;
pub const FRAME_STAND01: i32 = 162;
pub const FRAME_STAND02: i32 = 163;
pub const FRAME_STAND03: i32 = 164;
pub const FRAME_STAND04: i32 = 165;
pub const FRAME_STAND05: i32 = 166;
pub const FRAME_STAND06: i32 = 167;
pub const FRAME_STAND07: i32 = 168;
pub const FRAME_STAND08: i32 = 169;
pub const FRAME_STAND09: i32 = 170;
pub const FRAME_STAND10: i32 = 171;
pub const FRAME_STAND11: i32 = 172;
pub const FRAME_STAND12: i32 = 173;
pub const FRAME_STAND13: i32 = 174;
pub const FRAME_STAND14: i32 = 175;
pub const FRAME_STAND15: i32 = 176;
pub const FRAME_STAND16: i32 = 177;
pub const FRAME_STAND17: i32 = 178;
pub const FRAME_STAND18: i32 = 179;
pub const FRAME_STAND19: i32 = 180;
pub const FRAME_STAND20: i32 = 181;
pub const FRAME_STAND21: i32 = 182;
pub const FRAME_STAND22: i32 = 183;
pub const FRAME_STAND23: i32 = 184;
pub const FRAME_STAND24: i32 = 185;
pub const FRAME_STAND25: i32 = 186;
pub const FRAME_STAND26: i32 = 187;
pub const FRAME_STAND27: i32 = 188;
pub const FRAME_STAND28: i32 = 189;
pub const FRAME_STAND29: i32 = 190;
pub const FRAME_STAND30: i32 = 191;
pub const FRAME_STAND31: i32 = 192;
pub const FRAME_STAND32: i32 = 193;
pub const FRAME_STAND33: i32 = 194;
pub const FRAME_STAND34: i32 = 195;
pub const FRAME_STAND35: i32 = 196;
pub const FRAME_STAND36: i32 = 197;
pub const FRAME_STAND37: i32 = 198;
pub const FRAME_STAND38: i32 = 199;
pub const FRAME_STAND39: i32 = 200;
pub const FRAME_STAND40: i32 = 201;
pub const FRAME_STAND41: i32 = 202;
pub const FRAME_STAND42: i32 = 203;
pub const FRAME_STAND43: i32 = 204;
pub const FRAME_STAND44: i32 = 205;
pub const FRAME_STAND45: i32 = 206;
pub const FRAME_STAND46: i32 = 207;
pub const FRAME_STAND47: i32 = 208;
pub const FRAME_STAND48: i32 = 209;
pub const FRAME_STAND49: i32 = 210;
pub const FRAME_STAND50: i32 = 211;
pub const FRAME_STAND51: i32 = 212;
pub const FRAME_STAND52: i32 = 213;
pub const FRAME_STAND53: i32 = 214;
pub const FRAME_STAND54: i32 = 215;
pub const FRAME_STAND55: i32 = 216;
pub const FRAME_STAND56: i32 = 217;
pub const FRAME_STAND57: i32 = 218;
pub const FRAME_STAND58: i32 = 219;
pub const FRAME_STAND59: i32 = 220;
pub const FRAME_STAND60: i32 = 221;

pub const MODEL_SCALE: f32 = 1.0;

// MFrame and MMove are imported from g_local via `use crate::g_local::*`

// ============================================================
// Sound indices (module-level statics, mirrors C statics)
// ============================================================

/// Brain monster sound cache. Populated by `sp_monster_brain`.
#[derive(Debug, Clone, Default)]
pub struct BrainSounds {
    pub chest_open: i32,
    pub tentacles_extend: i32,
    pub tentacles_retract: i32,
    pub death: i32,
    pub idle1: i32,
    pub idle2: i32,
    pub idle3: i32,
    pub pain1: i32,
    pub pain2: i32,
    pub sight: i32,
    pub search: i32,
    pub melee1: i32,
    pub melee2: i32,
    pub melee3: i32,
}

/// Global brain sounds instance, initialized once on first brain spawn.
static BRAIN_SOUNDS: std::sync::OnceLock<BrainSounds> = std::sync::OnceLock::new();

// ============================================================
// Engine interface / cross-module adapter imports
// ============================================================

use crate::entity_adapters::{
    fire_hit, gi_sound, gi_soundindex, gi_modelindex, gi_linkentity,
    throw_gib, throw_head, walkmonster_start,
};


use crate::ai_wrappers::{ai_stand, ai_walk, ai_run, ai_charge, ai_move};

// ============================================================
// Move table indices — used by MonsterInfo.currentmove
// ============================================================

pub const BRAIN_MOVE_STAND: usize = 0;
pub const BRAIN_MOVE_IDLE: usize = 1;
pub const BRAIN_MOVE_WALK1: usize = 2;
pub const BRAIN_MOVE_DEFENSE: usize = 3;
pub const BRAIN_MOVE_PAIN3: usize = 4;
pub const BRAIN_MOVE_PAIN2: usize = 5;
pub const BRAIN_MOVE_PAIN1: usize = 6;
pub const BRAIN_MOVE_DUCK: usize = 7;
pub const BRAIN_MOVE_DEATH2: usize = 8;
pub const BRAIN_MOVE_DEATH1: usize = 9;
pub const BRAIN_MOVE_ATTACK1: usize = 10;
pub const BRAIN_MOVE_ATTACK2: usize = 11;
pub const BRAIN_MOVE_RUN: usize = 12;

// ============================================================
// STAND
// ============================================================

static BRAIN_FRAMES_STAND: [MFrame; 30] = [
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
];

pub static BRAIN_MOVE_STAND_DATA: MMove = MMove {
    firstframe: FRAME_STAND01,
    lastframe: FRAME_STAND30,
    frames: &BRAIN_FRAMES_STAND,
    endfunc: None,
};

pub fn brain_stand(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(BRAIN_MOVE_STAND);
}

// ============================================================
// IDLE
// ============================================================

static BRAIN_FRAMES_IDLE: [MFrame; 30] = [
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
];

pub static BRAIN_MOVE_IDLE_DATA: MMove = MMove {
    firstframe: FRAME_STAND31,
    lastframe: FRAME_STAND60,
    frames: &BRAIN_FRAMES_IDLE,
    endfunc: Some(brain_stand),
};

pub fn brain_idle(self_ent: &mut Edict, _ctx: &mut GameContext) {
    gi_sound(self_ent, CHAN_AUTO, BRAIN_SOUNDS.get().map_or(0, |s| s.idle3), 1.0, ATTN_IDLE, 0.0);
    self_ent.monsterinfo.currentmove = Some(BRAIN_MOVE_IDLE);
}

// ============================================================
// WALK
// ============================================================

static BRAIN_FRAMES_WALK1: [MFrame; 11] = [
    MFrame { ai_fn: ai_walk, dist: 7.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 3.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 3.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 9.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: -4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: -1.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 2.0, think_fn: None },
];

pub static BRAIN_MOVE_WALK1_DATA: MMove = MMove {
    firstframe: FRAME_WALK101,
    lastframe: FRAME_WALK111,
    frames: &BRAIN_FRAMES_WALK1,
    endfunc: None,
};

// walk2 is FUBAR, do not use (matches original C comment)

pub fn brain_walk(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(BRAIN_MOVE_WALK1);
}

// ============================================================
// DEFENSE
// ============================================================

static BRAIN_FRAMES_DEFENSE: [MFrame; 9] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static BRAIN_MOVE_DEFENSE_DATA: MMove = MMove {
    firstframe: FRAME_DEFENS01,
    lastframe: FRAME_DEFENS08,
    frames: &BRAIN_FRAMES_DEFENSE,
    endfunc: None,
};

// ============================================================
// PAIN
// ============================================================

static BRAIN_FRAMES_PAIN3: [MFrame; 6] = [
    MFrame { ai_fn: ai_move, dist: -2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 3.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -4.0, think_fn: None },
];

pub static BRAIN_MOVE_PAIN3_DATA: MMove = MMove {
    firstframe: FRAME_PAIN301,
    lastframe: FRAME_PAIN306,
    frames: &BRAIN_FRAMES_PAIN3,
    endfunc: Some(brain_run),
};

static BRAIN_FRAMES_PAIN2: [MFrame; 8] = [
    MFrame { ai_fn: ai_move, dist: -2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 3.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -2.0, think_fn: None },
];

pub static BRAIN_MOVE_PAIN2_DATA: MMove = MMove {
    firstframe: FRAME_PAIN201,
    lastframe: FRAME_PAIN208,
    frames: &BRAIN_FRAMES_PAIN2,
    endfunc: Some(brain_run),
};

static BRAIN_FRAMES_PAIN1: [MFrame; 21] = [
    MFrame { ai_fn: ai_move, dist: -6.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -6.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 7.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 3.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -1.0, think_fn: None },
];

pub static BRAIN_MOVE_PAIN1_DATA: MMove = MMove {
    firstframe: FRAME_PAIN101,
    lastframe: FRAME_PAIN121,
    frames: &BRAIN_FRAMES_PAIN1,
    endfunc: Some(brain_run),
};

// ============================================================
// DUCK
// ============================================================

pub fn brain_duck_down(self_ent: &mut Edict, _ctx: &mut GameContext) {
    if self_ent.monsterinfo.aiflags.intersects(AI_DUCKED) {
        return;
    }
    self_ent.monsterinfo.aiflags |= AI_DUCKED;
    self_ent.maxs[2] -= 32.0;
    self_ent.takedamage = DAMAGE_YES;
    gi_linkentity(self_ent);
}

pub fn brain_duck_hold(self_ent: &mut Edict, ctx: &mut GameContext) {
    if ctx.level.time >= self_ent.monsterinfo.pausetime {
        self_ent.monsterinfo.aiflags &= !AI_HOLD_FRAME;
    } else {
        self_ent.monsterinfo.aiflags |= AI_HOLD_FRAME;
    }
}

pub fn brain_duck_up(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.aiflags &= !AI_DUCKED;
    self_ent.maxs[2] += 32.0;
    self_ent.takedamage = DAMAGE_AIM;
    gi_linkentity(self_ent);
}

static BRAIN_FRAMES_DUCK: [MFrame; 8] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -2.0, think_fn: Some(brain_duck_down) },
    MFrame { ai_fn: ai_move, dist: 17.0, think_fn: Some(brain_duck_hold) },
    MFrame { ai_fn: ai_move, dist: -3.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -1.0, think_fn: Some(brain_duck_up) },
    MFrame { ai_fn: ai_move, dist: -5.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -6.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -6.0, think_fn: None },
];

pub static BRAIN_MOVE_DUCK_DATA: MMove = MMove {
    firstframe: FRAME_DUCK01,
    lastframe: FRAME_DUCK08,
    frames: &BRAIN_FRAMES_DUCK,
    endfunc: Some(brain_run),
};

pub fn brain_dodge(self_ent: &mut Edict, attacker_idx: i32, eta: f32, level: &mut LevelLocals) {
    if frand() > 0.25 {
        return;
    }

    if self_ent.enemy == -1 {
        self_ent.enemy = attacker_idx;
    }

    self_ent.monsterinfo.pausetime = level.time + eta + 0.5;
    self_ent.monsterinfo.currentmove = Some(BRAIN_MOVE_DUCK);
}

// ============================================================
// DEATH
// ============================================================

static BRAIN_FRAMES_DEATH2: [MFrame; 5] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 9.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static BRAIN_MOVE_DEATH2_DATA: MMove = MMove {
    firstframe: FRAME_DEATH201,
    lastframe: FRAME_DEATH205,
    frames: &BRAIN_FRAMES_DEATH2,
    endfunc: Some(brain_dead),
};

static BRAIN_FRAMES_DEATH1: [MFrame; 18] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 9.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static BRAIN_MOVE_DEATH1_DATA: MMove = MMove {
    firstframe: FRAME_DEATH101,
    lastframe: FRAME_DEATH118,
    frames: &BRAIN_FRAMES_DEATH1,
    endfunc: Some(brain_dead),
};

// ============================================================
// MELEE
// ============================================================

pub fn brain_swing_right(self_ent: &mut Edict, _ctx: &mut GameContext) {
    gi_sound(self_ent, CHAN_BODY, BRAIN_SOUNDS.get().map_or(0, |s| s.melee1), 1.0, ATTN_NORM, 0.0);
}

pub fn brain_hit_right(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let aim: Vec3 = [MELEE_DISTANCE, self_ent.maxs[0], 8.0];
    let damage = 15 + (rand_int() % 5);
    if fire_hit(self_ent, &aim, damage, 40) {
        gi_sound(self_ent, CHAN_WEAPON, BRAIN_SOUNDS.get().map_or(0, |s| s.melee3), 1.0, ATTN_NORM, 0.0);
    }
}

pub fn brain_swing_left(self_ent: &mut Edict, _ctx: &mut GameContext) {
    gi_sound(self_ent, CHAN_BODY, BRAIN_SOUNDS.get().map_or(0, |s| s.melee2), 1.0, ATTN_NORM, 0.0);
}

pub fn brain_hit_left(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let aim: Vec3 = [MELEE_DISTANCE, self_ent.mins[0], 8.0];
    let damage = 15 + (rand_int() % 5);
    if fire_hit(self_ent, &aim, damage, 40) {
        gi_sound(self_ent, CHAN_WEAPON, BRAIN_SOUNDS.get().map_or(0, |s| s.melee3), 1.0, ATTN_NORM, 0.0);
    }
}

use myq2_common::common::rand_i32 as rand_int;

static BRAIN_FRAMES_ATTACK1: [MFrame; 18] = [
    MFrame { ai_fn: ai_charge, dist: 8.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 3.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -3.0, think_fn: Some(brain_swing_right) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -5.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -7.0, think_fn: Some(brain_hit_right) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 6.0, think_fn: Some(brain_swing_left) },
    MFrame { ai_fn: ai_charge, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 2.0, think_fn: Some(brain_hit_left) },
    MFrame { ai_fn: ai_charge, dist: -3.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 6.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -1.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -3.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -11.0, think_fn: None },
];

pub static BRAIN_MOVE_ATTACK1_DATA: MMove = MMove {
    firstframe: FRAME_ATTAK101,
    lastframe: FRAME_ATTAK118,
    frames: &BRAIN_FRAMES_ATTACK1,
    endfunc: Some(brain_run),
};

pub fn brain_chest_open(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.spawnflags &= !65536;
    self_ent.monsterinfo.power_armor_type = POWER_ARMOR_NONE;
    gi_sound(self_ent, CHAN_BODY, BRAIN_SOUNDS.get().map_or(0, |s| s.chest_open), 1.0, ATTN_NORM, 0.0);
}

pub fn brain_tentacle_attack(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let aim: Vec3 = [MELEE_DISTANCE, 0.0, 8.0];
    let damage = 10 + (rand_int() % 5);
    if fire_hit(self_ent, &aim, damage, -600) {
        if _ctx.skill > 0.0 {
            self_ent.spawnflags |= 65536;
        }
    }
    gi_sound(self_ent, CHAN_WEAPON, BRAIN_SOUNDS.get().map_or(0, |s| s.tentacles_retract), 1.0, ATTN_NORM, 0.0);
}

pub fn brain_chest_closed(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.power_armor_type = POWER_ARMOR_SCREEN;
    if self_ent.spawnflags & 65536 != 0 {
        self_ent.spawnflags &= !65536;
        self_ent.monsterinfo.currentmove = Some(BRAIN_MOVE_ATTACK1);
    }
}

static BRAIN_FRAMES_ATTACK2: [MFrame; 17] = [
    MFrame { ai_fn: ai_charge, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -4.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -4.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -3.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(brain_chest_open) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 13.0, think_fn: Some(brain_tentacle_attack) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -9.0, think_fn: Some(brain_chest_closed) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 3.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -3.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -6.0, think_fn: None },
];

pub static BRAIN_MOVE_ATTACK2_DATA: MMove = MMove {
    firstframe: FRAME_ATTAK201,
    lastframe: FRAME_ATTAK217,
    frames: &BRAIN_FRAMES_ATTACK2,
    endfunc: Some(brain_run),
};

pub fn brain_melee(self_ent: &mut Edict, _ctx: &mut GameContext) {
    if frand() <= 0.5 {
        self_ent.monsterinfo.currentmove = Some(BRAIN_MOVE_ATTACK1);
    } else {
        self_ent.monsterinfo.currentmove = Some(BRAIN_MOVE_ATTACK2);
    }
}

// ============================================================
// RUN
// ============================================================

static BRAIN_FRAMES_RUN: [MFrame; 11] = [
    MFrame { ai_fn: ai_run, dist: 9.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 3.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 3.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: -4.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: -1.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 2.0, think_fn: None },
];

pub static BRAIN_MOVE_RUN_DATA: MMove = MMove {
    firstframe: FRAME_WALK101,
    lastframe: FRAME_WALK111,
    frames: &BRAIN_FRAMES_RUN,
    endfunc: None,
};

pub fn brain_run(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.power_armor_type = POWER_ARMOR_SCREEN;
    if self_ent.monsterinfo.aiflags.intersects(AI_STAND_GROUND) {
        self_ent.monsterinfo.currentmove = Some(BRAIN_MOVE_STAND);
    } else {
        self_ent.monsterinfo.currentmove = Some(BRAIN_MOVE_RUN);
    }
}

// ============================================================
// SIGHT / SEARCH
// ============================================================

pub fn brain_sight(self_ent: &mut Edict, _other_idx: i32, _level: &mut LevelLocals) {
    gi_sound(self_ent, CHAN_VOICE, BRAIN_SOUNDS.get().map_or(0, |s| s.sight), 1.0, ATTN_NORM, 0.0);
}

pub fn brain_search(self_ent: &mut Edict, _ctx: &mut GameContext) {
    gi_sound(self_ent, CHAN_VOICE, BRAIN_SOUNDS.get().map_or(0, |s| s.search), 1.0, ATTN_NORM, 0.0);
}

// ============================================================
// PAIN
// ============================================================

pub fn brain_pain(self_ent: &mut Edict, _other_idx: i32, _kick: f32, _damage: i32, level: &mut LevelLocals) {
    if self_ent.health < (self_ent.max_health / 2) {
        self_ent.s.skinnum = 1;
    }

    if level.time < self_ent.pain_debounce_time {
        return;
    }

    self_ent.pain_debounce_time = level.time + 3.0;

    // In nightmare (skill == 3), no pain animations
    let skill_val = crate::g_local::with_global_game_ctx(|ctx| ctx.skill).unwrap_or(0.0);
    if skill_val >= 3.0 {
        return;
    }

    let r = frand();
    if r < 0.33 {
        gi_sound(self_ent, CHAN_VOICE, BRAIN_SOUNDS.get().map_or(0, |s| s.pain1), 1.0, ATTN_NORM, 0.0);
        self_ent.monsterinfo.currentmove = Some(BRAIN_MOVE_PAIN1);
    } else if r < 0.66 {
        gi_sound(self_ent, CHAN_VOICE, BRAIN_SOUNDS.get().map_or(0, |s| s.pain2), 1.0, ATTN_NORM, 0.0);
        self_ent.monsterinfo.currentmove = Some(BRAIN_MOVE_PAIN2);
    } else {
        gi_sound(self_ent, CHAN_VOICE, BRAIN_SOUNDS.get().map_or(0, |s| s.pain1), 1.0, ATTN_NORM, 0.0);
        self_ent.monsterinfo.currentmove = Some(BRAIN_MOVE_PAIN3);
    }
}

// ============================================================
// DEAD
// ============================================================

pub fn brain_dead(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.mins = [-16.0, -16.0, -24.0];
    self_ent.maxs = [16.0, 16.0, -8.0];
    self_ent.movetype = MoveType::Toss;
    self_ent.svflags |= SVF_DEADMONSTER;
    self_ent.nextthink = 0.0;
    gi_linkentity(self_ent);
}

// ============================================================
// DIE
// ============================================================

pub fn brain_die(
    self_ent: &mut Edict,
    _inflictor_idx: i32,
    _attacker_idx: i32,
    damage: i32,
    _point: Vec3,
    _level: &mut LevelLocals,
) {
    self_ent.s.effects = 0;
    self_ent.monsterinfo.power_armor_type = POWER_ARMOR_NONE;

    // check for gib
    if self_ent.health <= self_ent.gib_health {
        gi_sound(self_ent, CHAN_VOICE, gi_soundindex("misc/udeath.wav"), 1.0, ATTN_NORM, 0.0);
        for _ in 0..2 {
            throw_gib(self_ent, "models/objects/gibs/bone/tris.md2", damage, GIB_ORGANIC);
        }
        for _ in 0..4 {
            throw_gib(self_ent, "models/objects/gibs/sm_meat/tris.md2", damage, GIB_ORGANIC);
        }
        throw_head(self_ent, "models/objects/gibs/head2/tris.md2", damage, GIB_ORGANIC);
        self_ent.deadflag = DEAD_DEAD;
        return;
    }

    if self_ent.deadflag == DEAD_DEAD {
        return;
    }

    // regular death
    gi_sound(self_ent, CHAN_VOICE, BRAIN_SOUNDS.get().map_or(0, |s| s.death), 1.0, ATTN_NORM, 0.0);
    self_ent.deadflag = DEAD_DEAD;
    self_ent.takedamage = DAMAGE_YES;
    if frand() <= 0.5 {
        self_ent.monsterinfo.currentmove = Some(BRAIN_MOVE_DEATH1);
    } else {
        self_ent.monsterinfo.currentmove = Some(BRAIN_MOVE_DEATH2);
    }
}

// ============================================================
// SPAWN
// ============================================================

/// `SP_monster_brain` — Spawn function for monster_brain entity.
///
/// QUAKED monster_brain (1 .5 0) (-16 -16 -24) (16 16 32) Ambush Trigger_Spawn Sight
pub fn sp_monster_brain(self_ent: &mut Edict, _ctx: &mut GameContext) {
    if _ctx.deathmatch != 0.0 {
        let self_idx = self_ent.s.number as usize;
        crate::g_local::with_global_game_ctx(|ctx| {
            crate::g_utils::g_free_edict(ctx, self_idx);
        });
        return;
    }

    BRAIN_SOUNDS.get_or_init(|| BrainSounds {
        chest_open: gi_soundindex("brain/brnatck1.wav"),
        tentacles_extend: gi_soundindex("brain/brnatck2.wav"),
        tentacles_retract: gi_soundindex("brain/brnatck3.wav"),
        death: gi_soundindex("brain/brndeth1.wav"),
        idle1: gi_soundindex("brain/brnidle1.wav"),
        idle2: gi_soundindex("brain/brnidle2.wav"),
        idle3: gi_soundindex("brain/brnlens1.wav"),
        pain1: gi_soundindex("brain/brnpain1.wav"),
        pain2: gi_soundindex("brain/brnpain2.wav"),
        sight: gi_soundindex("brain/brnsght1.wav"),
        search: gi_soundindex("brain/brnsrch1.wav"),
        melee1: gi_soundindex("brain/melee1.wav"),
        melee2: gi_soundindex("brain/melee2.wav"),
        melee3: gi_soundindex("brain/melee3.wav"),
    });

    self_ent.movetype = MoveType::Step;
    self_ent.solid = crate::game::Solid::Bbox;
    self_ent.s.modelindex = gi_modelindex("models/monsters/brain/tris.md2");
    self_ent.mins = [-16.0, -16.0, -24.0];
    self_ent.maxs = [16.0, 16.0, 32.0];

    self_ent.health = 300;
    self_ent.gib_health = -150;
    self_ent.mass = 400;

    self_ent.pain_fn = Some(crate::dispatch::PAIN_BRAIN);
    self_ent.die_fn = Some(crate::dispatch::DIE_BRAIN);

    self_ent.monsterinfo.stand_fn = Some(crate::dispatch::MSTAND_BRAIN);
    self_ent.monsterinfo.walk_fn = Some(crate::dispatch::MWALK_BRAIN);
    self_ent.monsterinfo.run_fn = Some(crate::dispatch::MRUN_BRAIN);
    self_ent.monsterinfo.dodge_fn = Some(crate::dispatch::MDODGE_BRAIN);
    self_ent.monsterinfo.melee_fn = Some(crate::dispatch::MMELEE_BRAIN);
    self_ent.monsterinfo.sight_fn = Some(crate::dispatch::MSIGHT_BRAIN);
    self_ent.monsterinfo.search_fn = Some(crate::dispatch::MSEARCH_BRAIN);
    self_ent.monsterinfo.idle_fn = Some(crate::dispatch::MIDLE_BRAIN);

    self_ent.monsterinfo.power_armor_type = POWER_ARMOR_SCREEN;
    self_ent.monsterinfo.power_armor_power = 100;

    gi_linkentity(self_ent);

    self_ent.monsterinfo.currentmove = Some(BRAIN_MOVE_STAND);
    self_ent.monsterinfo.scale = MODEL_SCALE;

    walkmonster_start(self_ent);
}

// ============================================================
// Move table accessor
// ============================================================

/// Returns a reference to the `MMove` for the given brain move index.
pub fn brain_get_move(index: usize) -> &'static MMove {
    match index {
        BRAIN_MOVE_STAND => &BRAIN_MOVE_STAND_DATA,
        BRAIN_MOVE_IDLE => &BRAIN_MOVE_IDLE_DATA,
        BRAIN_MOVE_WALK1 => &BRAIN_MOVE_WALK1_DATA,
        BRAIN_MOVE_DEFENSE => &BRAIN_MOVE_DEFENSE_DATA,
        BRAIN_MOVE_PAIN3 => &BRAIN_MOVE_PAIN3_DATA,
        BRAIN_MOVE_PAIN2 => &BRAIN_MOVE_PAIN2_DATA,
        BRAIN_MOVE_PAIN1 => &BRAIN_MOVE_PAIN1_DATA,
        BRAIN_MOVE_DUCK => &BRAIN_MOVE_DUCK_DATA,
        BRAIN_MOVE_DEATH2 => &BRAIN_MOVE_DEATH2_DATA,
        BRAIN_MOVE_DEATH1 => &BRAIN_MOVE_DEATH1_DATA,
        BRAIN_MOVE_ATTACK1 => &BRAIN_MOVE_ATTACK1_DATA,
        BRAIN_MOVE_ATTACK2 => &BRAIN_MOVE_ATTACK2_DATA,
        BRAIN_MOVE_RUN => &BRAIN_MOVE_RUN_DATA,
        _ => panic!("brain_get_move: invalid move index {}", index),
    }
}
