// m_chick.rs — Iron Maiden (chick) monster
// Converted from: myq2-original/game/m_chick.c + m_chick.h
//
// Copyright (C) 1997-2001 Id Software, Inc.
// Licensed under the GNU General Public License v2.

use crate::g_local::*;
use crate::game::*;
use myq2_common::common::{frand as random, rand_i32};
use crate::entity_adapters::{
    gi_sound, gi_soundindex, gi_modelindex, gi_linkentity,
    g_free_edict, walkmonster_start, throw_gib, throw_head,
    visible, range, fire_hit,
};
use crate::game_import::skill_value;

// ============================================================
// Frame definitions (from m_chick.h)
// Generated by qdata — Do NOT Modify
// ============================================================

pub const FRAME_ATTAK101: i32 = 0;
pub const FRAME_ATTAK102: i32 = 1;
pub const FRAME_ATTAK103: i32 = 2;
pub const FRAME_ATTAK104: i32 = 3;
pub const FRAME_ATTAK105: i32 = 4;
pub const FRAME_ATTAK106: i32 = 5;
pub const FRAME_ATTAK107: i32 = 6;
pub const FRAME_ATTAK108: i32 = 7;
pub const FRAME_ATTAK109: i32 = 8;
pub const FRAME_ATTAK110: i32 = 9;
pub const FRAME_ATTAK111: i32 = 10;
pub const FRAME_ATTAK112: i32 = 11;
pub const FRAME_ATTAK113: i32 = 12;
pub const FRAME_ATTAK114: i32 = 13;
pub const FRAME_ATTAK115: i32 = 14;
pub const FRAME_ATTAK116: i32 = 15;
pub const FRAME_ATTAK117: i32 = 16;
pub const FRAME_ATTAK118: i32 = 17;
pub const FRAME_ATTAK119: i32 = 18;
pub const FRAME_ATTAK120: i32 = 19;
pub const FRAME_ATTAK121: i32 = 20;
pub const FRAME_ATTAK122: i32 = 21;
pub const FRAME_ATTAK123: i32 = 22;
pub const FRAME_ATTAK124: i32 = 23;
pub const FRAME_ATTAK125: i32 = 24;
pub const FRAME_ATTAK126: i32 = 25;
pub const FRAME_ATTAK127: i32 = 26;
pub const FRAME_ATTAK128: i32 = 27;
pub const FRAME_ATTAK129: i32 = 28;
pub const FRAME_ATTAK130: i32 = 29;
pub const FRAME_ATTAK131: i32 = 30;
pub const FRAME_ATTAK132: i32 = 31;
pub const FRAME_ATTAK201: i32 = 32;
pub const FRAME_ATTAK202: i32 = 33;
pub const FRAME_ATTAK203: i32 = 34;
pub const FRAME_ATTAK204: i32 = 35;
pub const FRAME_ATTAK205: i32 = 36;
pub const FRAME_ATTAK206: i32 = 37;
pub const FRAME_ATTAK207: i32 = 38;
pub const FRAME_ATTAK208: i32 = 39;
pub const FRAME_ATTAK209: i32 = 40;
pub const FRAME_ATTAK210: i32 = 41;
pub const FRAME_ATTAK211: i32 = 42;
pub const FRAME_ATTAK212: i32 = 43;
pub const FRAME_ATTAK213: i32 = 44;
pub const FRAME_ATTAK214: i32 = 45;
pub const FRAME_ATTAK215: i32 = 46;
pub const FRAME_ATTAK216: i32 = 47;
pub const FRAME_DEATH101: i32 = 48;
pub const FRAME_DEATH102: i32 = 49;
pub const FRAME_DEATH103: i32 = 50;
pub const FRAME_DEATH104: i32 = 51;
pub const FRAME_DEATH105: i32 = 52;
pub const FRAME_DEATH106: i32 = 53;
pub const FRAME_DEATH107: i32 = 54;
pub const FRAME_DEATH108: i32 = 55;
pub const FRAME_DEATH109: i32 = 56;
pub const FRAME_DEATH110: i32 = 57;
pub const FRAME_DEATH111: i32 = 58;
pub const FRAME_DEATH112: i32 = 59;
pub const FRAME_DEATH201: i32 = 60;
pub const FRAME_DEATH202: i32 = 61;
pub const FRAME_DEATH203: i32 = 62;
pub const FRAME_DEATH204: i32 = 63;
pub const FRAME_DEATH205: i32 = 64;
pub const FRAME_DEATH206: i32 = 65;
pub const FRAME_DEATH207: i32 = 66;
pub const FRAME_DEATH208: i32 = 67;
pub const FRAME_DEATH209: i32 = 68;
pub const FRAME_DEATH210: i32 = 69;
pub const FRAME_DEATH211: i32 = 70;
pub const FRAME_DEATH212: i32 = 71;
pub const FRAME_DEATH213: i32 = 72;
pub const FRAME_DEATH214: i32 = 73;
pub const FRAME_DEATH215: i32 = 74;
pub const FRAME_DEATH216: i32 = 75;
pub const FRAME_DEATH217: i32 = 76;
pub const FRAME_DEATH218: i32 = 77;
pub const FRAME_DEATH219: i32 = 78;
pub const FRAME_DEATH220: i32 = 79;
pub const FRAME_DEATH221: i32 = 80;
pub const FRAME_DEATH222: i32 = 81;
pub const FRAME_DEATH223: i32 = 82;
pub const FRAME_DUCK01: i32 = 83;
pub const FRAME_DUCK02: i32 = 84;
pub const FRAME_DUCK03: i32 = 85;
pub const FRAME_DUCK04: i32 = 86;
pub const FRAME_DUCK05: i32 = 87;
pub const FRAME_DUCK06: i32 = 88;
pub const FRAME_DUCK07: i32 = 89;
pub const FRAME_PAIN101: i32 = 90;
pub const FRAME_PAIN102: i32 = 91;
pub const FRAME_PAIN103: i32 = 92;
pub const FRAME_PAIN104: i32 = 93;
pub const FRAME_PAIN105: i32 = 94;
pub const FRAME_PAIN201: i32 = 95;
pub const FRAME_PAIN202: i32 = 96;
pub const FRAME_PAIN203: i32 = 97;
pub const FRAME_PAIN204: i32 = 98;
pub const FRAME_PAIN205: i32 = 99;
pub const FRAME_PAIN301: i32 = 100;
pub const FRAME_PAIN302: i32 = 101;
pub const FRAME_PAIN303: i32 = 102;
pub const FRAME_PAIN304: i32 = 103;
pub const FRAME_PAIN305: i32 = 104;
pub const FRAME_PAIN306: i32 = 105;
pub const FRAME_PAIN307: i32 = 106;
pub const FRAME_PAIN308: i32 = 107;
pub const FRAME_PAIN309: i32 = 108;
pub const FRAME_PAIN310: i32 = 109;
pub const FRAME_PAIN311: i32 = 110;
pub const FRAME_PAIN312: i32 = 111;
pub const FRAME_PAIN313: i32 = 112;
pub const FRAME_PAIN314: i32 = 113;
pub const FRAME_PAIN315: i32 = 114;
pub const FRAME_PAIN316: i32 = 115;
pub const FRAME_PAIN317: i32 = 116;
pub const FRAME_PAIN318: i32 = 117;
pub const FRAME_PAIN319: i32 = 118;
pub const FRAME_PAIN320: i32 = 119;
pub const FRAME_PAIN321: i32 = 120;
pub const FRAME_STAND101: i32 = 121;
pub const FRAME_STAND102: i32 = 122;
pub const FRAME_STAND103: i32 = 123;
pub const FRAME_STAND104: i32 = 124;
pub const FRAME_STAND105: i32 = 125;
pub const FRAME_STAND106: i32 = 126;
pub const FRAME_STAND107: i32 = 127;
pub const FRAME_STAND108: i32 = 128;
pub const FRAME_STAND109: i32 = 129;
pub const FRAME_STAND110: i32 = 130;
pub const FRAME_STAND111: i32 = 131;
pub const FRAME_STAND112: i32 = 132;
pub const FRAME_STAND113: i32 = 133;
pub const FRAME_STAND114: i32 = 134;
pub const FRAME_STAND115: i32 = 135;
pub const FRAME_STAND116: i32 = 136;
pub const FRAME_STAND117: i32 = 137;
pub const FRAME_STAND118: i32 = 138;
pub const FRAME_STAND119: i32 = 139;
pub const FRAME_STAND120: i32 = 140;
pub const FRAME_STAND121: i32 = 141;
pub const FRAME_STAND122: i32 = 142;
pub const FRAME_STAND123: i32 = 143;
pub const FRAME_STAND124: i32 = 144;
pub const FRAME_STAND125: i32 = 145;
pub const FRAME_STAND126: i32 = 146;
pub const FRAME_STAND127: i32 = 147;
pub const FRAME_STAND128: i32 = 148;
pub const FRAME_STAND129: i32 = 149;
pub const FRAME_STAND130: i32 = 150;
pub const FRAME_STAND201: i32 = 151;
pub const FRAME_STAND202: i32 = 152;
pub const FRAME_STAND203: i32 = 153;
pub const FRAME_STAND204: i32 = 154;
pub const FRAME_STAND205: i32 = 155;
pub const FRAME_STAND206: i32 = 156;
pub const FRAME_STAND207: i32 = 157;
pub const FRAME_STAND208: i32 = 158;
pub const FRAME_STAND209: i32 = 159;
pub const FRAME_STAND210: i32 = 160;
pub const FRAME_STAND211: i32 = 161;
pub const FRAME_STAND212: i32 = 162;
pub const FRAME_STAND213: i32 = 163;
pub const FRAME_STAND214: i32 = 164;
pub const FRAME_STAND215: i32 = 165;
pub const FRAME_STAND216: i32 = 166;
pub const FRAME_STAND217: i32 = 167;
pub const FRAME_STAND218: i32 = 168;
pub const FRAME_STAND219: i32 = 169;
pub const FRAME_STAND220: i32 = 170;
pub const FRAME_STAND221: i32 = 171;
pub const FRAME_STAND222: i32 = 172;
pub const FRAME_STAND223: i32 = 173;
pub const FRAME_STAND224: i32 = 174;
pub const FRAME_STAND225: i32 = 175;
pub const FRAME_STAND226: i32 = 176;
pub const FRAME_STAND227: i32 = 177;
pub const FRAME_STAND228: i32 = 178;
pub const FRAME_STAND229: i32 = 179;
pub const FRAME_STAND230: i32 = 180;
pub const FRAME_WALK01: i32 = 181;
pub const FRAME_WALK02: i32 = 182;
pub const FRAME_WALK03: i32 = 183;
pub const FRAME_WALK04: i32 = 184;
pub const FRAME_WALK05: i32 = 185;
pub const FRAME_WALK06: i32 = 186;
pub const FRAME_WALK07: i32 = 187;
pub const FRAME_WALK08: i32 = 188;
pub const FRAME_WALK09: i32 = 189;
pub const FRAME_WALK10: i32 = 190;
pub const FRAME_WALK11: i32 = 191;
pub const FRAME_WALK12: i32 = 192;
pub const FRAME_WALK13: i32 = 193;
pub const FRAME_WALK14: i32 = 194;
pub const FRAME_WALK15: i32 = 195;
pub const FRAME_WALK16: i32 = 196;
pub const FRAME_WALK17: i32 = 197;
pub const FRAME_WALK18: i32 = 198;
pub const FRAME_WALK19: i32 = 199;
pub const FRAME_WALK20: i32 = 200;
pub const FRAME_WALK21: i32 = 201;
pub const FRAME_WALK22: i32 = 202;
pub const FRAME_WALK23: i32 = 203;
pub const FRAME_WALK24: i32 = 204;
pub const FRAME_WALK25: i32 = 205;
pub const FRAME_WALK26: i32 = 206;
pub const FRAME_WALK27: i32 = 207;
pub const FRAME_RECLN201: i32 = 208;
pub const FRAME_RECLN202: i32 = 209;
pub const FRAME_RECLN203: i32 = 210;
pub const FRAME_RECLN204: i32 = 211;
pub const FRAME_RECLN205: i32 = 212;
pub const FRAME_RECLN206: i32 = 213;
pub const FRAME_RECLN207: i32 = 214;
pub const FRAME_RECLN208: i32 = 215;
pub const FRAME_RECLN209: i32 = 216;
pub const FRAME_RECLN210: i32 = 217;
pub const FRAME_RECLN211: i32 = 218;
pub const FRAME_RECLN212: i32 = 219;
pub const FRAME_RECLN213: i32 = 220;
pub const FRAME_RECLN214: i32 = 221;
pub const FRAME_RECLN215: i32 = 222;
pub const FRAME_RECLN216: i32 = 223;
pub const FRAME_RECLN217: i32 = 224;
pub const FRAME_RECLN218: i32 = 225;
pub const FRAME_RECLN219: i32 = 226;
pub const FRAME_RECLN220: i32 = 227;
pub const FRAME_RECLN221: i32 = 228;
pub const FRAME_RECLN222: i32 = 229;
pub const FRAME_RECLN223: i32 = 230;
pub const FRAME_RECLN224: i32 = 231;
pub const FRAME_RECLN225: i32 = 232;
pub const FRAME_RECLN226: i32 = 233;
pub const FRAME_RECLN227: i32 = 234;
pub const FRAME_RECLN228: i32 = 235;
pub const FRAME_RECLN229: i32 = 236;
pub const FRAME_RECLN230: i32 = 237;
pub const FRAME_RECLN231: i32 = 238;
pub const FRAME_RECLN232: i32 = 239;
pub const FRAME_RECLN233: i32 = 240;
pub const FRAME_RECLN234: i32 = 241;
pub const FRAME_RECLN235: i32 = 242;
pub const FRAME_RECLN236: i32 = 243;
pub const FRAME_RECLN237: i32 = 244;
pub const FRAME_RECLN238: i32 = 245;
pub const FRAME_RECLN239: i32 = 246;
pub const FRAME_RECLN240: i32 = 247;
pub const FRAME_RECLN101: i32 = 248;
pub const FRAME_RECLN102: i32 = 249;
pub const FRAME_RECLN103: i32 = 250;
pub const FRAME_RECLN104: i32 = 251;
pub const FRAME_RECLN105: i32 = 252;
pub const FRAME_RECLN106: i32 = 253;
pub const FRAME_RECLN107: i32 = 254;
pub const FRAME_RECLN108: i32 = 255;
pub const FRAME_RECLN109: i32 = 256;
pub const FRAME_RECLN110: i32 = 257;
pub const FRAME_RECLN111: i32 = 258;
pub const FRAME_RECLN112: i32 = 259;
pub const FRAME_RECLN113: i32 = 260;
pub const FRAME_RECLN114: i32 = 261;
pub const FRAME_RECLN115: i32 = 262;
pub const FRAME_RECLN116: i32 = 263;
pub const FRAME_RECLN117: i32 = 264;
pub const FRAME_RECLN118: i32 = 265;
pub const FRAME_RECLN119: i32 = 266;
pub const FRAME_RECLN120: i32 = 267;
pub const FRAME_RECLN121: i32 = 268;
pub const FRAME_RECLN122: i32 = 269;
pub const FRAME_RECLN123: i32 = 270;
pub const FRAME_RECLN124: i32 = 271;
pub const FRAME_RECLN125: i32 = 272;
pub const FRAME_RECLN126: i32 = 273;
pub const FRAME_RECLN127: i32 = 274;
pub const FRAME_RECLN128: i32 = 275;
pub const FRAME_RECLN129: i32 = 276;
pub const FRAME_RECLN130: i32 = 277;
pub const FRAME_RECLN131: i32 = 278;
pub const FRAME_RECLN132: i32 = 279;
pub const FRAME_RECLN133: i32 = 280;
pub const FRAME_RECLN134: i32 = 281;
pub const FRAME_RECLN135: i32 = 282;
pub const FRAME_RECLN136: i32 = 283;
pub const FRAME_RECLN137: i32 = 284;
pub const FRAME_RECLN138: i32 = 285;
pub const FRAME_RECLN139: i32 = 286;
pub const FRAME_RECLN140: i32 = 287;

pub const MODEL_SCALE: f32 = 1.0;

// ============================================================
// Local constants
// ============================================================

// CHAN_*, ATTN_* come from g_local::* re-export (myq2_common::q_shared)

use crate::ai_wrappers::{ai_stand, ai_walk, ai_run, ai_charge, ai_move};


// ============================================================
// Sound indices (module-level state, replaces C statics)
// ============================================================

#[derive(Default)]
pub struct ChickSounds {
    pub missile_prelaunch: i32,
    pub missile_launch: i32,
    pub melee_swing: i32,
    pub melee_hit: i32,
    pub missile_reload: i32,
    pub death1: i32,
    pub death2: i32,
    pub fall_down: i32,
    pub idle1: i32,
    pub idle2: i32,
    pub pain1: i32,
    pub pain2: i32,
    pub pain3: i32,
    pub sight: i32,
    pub search: i32,
}

static SOUNDS: std::sync::OnceLock<ChickSounds> = std::sync::OnceLock::new();

// ============================================================
// Move indices — identifiers for each MMove
// ============================================================

pub const MOVE_FIDGET: usize = 0;
pub const MOVE_STAND: usize = 1;
pub const MOVE_START_RUN: usize = 2;
pub const MOVE_RUN: usize = 3;
pub const MOVE_WALK: usize = 4;
pub const MOVE_PAIN1: usize = 5;
pub const MOVE_PAIN2: usize = 6;
pub const MOVE_PAIN3: usize = 7;
pub const MOVE_DEATH1: usize = 8;
pub const MOVE_DEATH2: usize = 9;
pub const MOVE_DUCK: usize = 10;
pub const MOVE_START_ATTACK1: usize = 11;
pub const MOVE_ATTACK1: usize = 12;
pub const MOVE_END_ATTACK1: usize = 13;
pub const MOVE_SLASH: usize = 14;
pub const MOVE_END_SLASH: usize = 15;
pub const MOVE_START_SLASH: usize = 16;

// ============================================================
// Behavior functions
// ============================================================

fn chick_moan(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let (s1, s2) = SOUNDS.get().map_or((0, 0), |s| (s.idle1, s.idle2));
    if random() < 0.5 {
        gi_sound(self_ent, CHAN_VOICE, s1, 1.0, ATTN_IDLE, 0.0);
    } else {
        gi_sound(self_ent, CHAN_VOICE, s2, 1.0, ATTN_IDLE, 0.0);
    }
}

fn chick_fidget(self_ent: &mut Edict, _ctx: &mut GameContext) {
    if self_ent.monsterinfo.aiflags.intersects(AI_STAND_GROUND) {
        return;
    }
    if random() <= 0.3 {
        self_ent.monsterinfo.currentmove = Some(MOVE_FIDGET);
    }
}

pub fn chick_stand(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_STAND);
}

pub fn chick_run(self_ent: &mut Edict, _ctx: &mut GameContext) {
    if self_ent.monsterinfo.aiflags.intersects(AI_STAND_GROUND) {
        self_ent.monsterinfo.currentmove = Some(MOVE_STAND);
        return;
    }

    let cur = self_ent.monsterinfo.currentmove;
    if cur == Some(MOVE_WALK) || cur == Some(MOVE_START_RUN) {
        self_ent.monsterinfo.currentmove = Some(MOVE_RUN);
    } else {
        self_ent.monsterinfo.currentmove = Some(MOVE_START_RUN);
    }
}

pub fn chick_walk(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_WALK);
}

pub fn chick_pain(self_ent: &mut Edict, _other: &mut Edict, _kick: f32, damage: i32, ctx: &mut GameContext) {
    if self_ent.health < (self_ent.max_health / 2) {
        self_ent.s.skinnum = 1;
    }

    if ctx.level.time < self_ent.pain_debounce_time {
        return;
    }

    self_ent.pain_debounce_time = ctx.level.time + 3.0;

    let r = random();
    let (sp1, sp2, sp3) = SOUNDS.get().map_or((0, 0, 0), |s| (s.pain1, s.pain2, s.pain3));
    if r < 0.33 {
        gi_sound(self_ent, CHAN_VOICE, sp1, 1.0, ATTN_NORM, 0.0);
    } else if r < 0.66 {
        gi_sound(self_ent, CHAN_VOICE, sp2, 1.0, ATTN_NORM, 0.0);
    } else {
        gi_sound(self_ent, CHAN_VOICE, sp3, 1.0, ATTN_NORM, 0.0);
    }

    // skill->value == 3 means nightmare: no pain anims
    if skill_value() == 3.0 {
        return; // no pain anims in nightmare
    }

    if damage <= 10 {
        self_ent.monsterinfo.currentmove = Some(MOVE_PAIN1);
    } else if damage <= 25 {
        self_ent.monsterinfo.currentmove = Some(MOVE_PAIN2);
    } else {
        self_ent.monsterinfo.currentmove = Some(MOVE_PAIN3);
    }
}

fn chick_dead(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.mins = [-16.0, -16.0, 0.0];
    self_ent.maxs = [16.0, 16.0, 16.0];
    self_ent.movetype = MoveType::Toss;
    self_ent.svflags |= SVF_DEADMONSTER;
    self_ent.nextthink = 0.0;
    gi_linkentity(self_ent);
}

pub fn chick_die(self_ent: &mut Edict, _inflictor: &mut Edict, _attacker: &mut Edict, damage: i32, _point: [f32; 3], _ctx: &mut GameContext) {
    // check for gib
    if self_ent.health <= self_ent.gib_health {
        gi_sound(self_ent, CHAN_VOICE, gi_soundindex("misc/udeath.wav"), 1.0, ATTN_NORM, 0.0);
        for _ in 0..2 {
            throw_gib(self_ent, "models/objects/gibs/bone/tris.md2", damage, GIB_ORGANIC);
        }
        for _ in 0..4 {
            throw_gib(self_ent, "models/objects/gibs/sm_meat/tris.md2", damage, GIB_ORGANIC);
        }
        throw_head(self_ent, "models/objects/gibs/head2/tris.md2", damage, GIB_ORGANIC);
        self_ent.deadflag = DEAD_DEAD;
        return;
    }

    if self_ent.deadflag == DEAD_DEAD {
        return;
    }

    // regular death
    self_ent.deadflag = DEAD_DEAD;
    self_ent.takedamage = Damage::Yes as i32;

    let (sd1, sd2) = SOUNDS.get().map_or((0, 0), |s| (s.death1, s.death2));
    let n = rand_i32() % 2;
    if n == 0 {
        self_ent.monsterinfo.currentmove = Some(MOVE_DEATH1);
        gi_sound(self_ent, CHAN_VOICE, sd1, 1.0, ATTN_NORM, 0.0);
    } else {
        self_ent.monsterinfo.currentmove = Some(MOVE_DEATH2);
        gi_sound(self_ent, CHAN_VOICE, sd2, 1.0, ATTN_NORM, 0.0);
    }
}

fn chick_duck_down(self_ent: &mut Edict, ctx: &mut GameContext) {
    if self_ent.monsterinfo.aiflags.intersects(AI_DUCKED) {
        return;
    }
    self_ent.monsterinfo.aiflags |= AI_DUCKED;
    self_ent.maxs[2] -= 32.0;
    self_ent.takedamage = Damage::Yes as i32;
    self_ent.monsterinfo.pausetime = ctx.level.time + 1.0;
    gi_linkentity(self_ent);
}

fn chick_duck_hold(self_ent: &mut Edict, ctx: &mut GameContext) {
    if ctx.level.time >= self_ent.monsterinfo.pausetime {
        self_ent.monsterinfo.aiflags &= !AI_HOLD_FRAME;
    } else {
        self_ent.monsterinfo.aiflags |= AI_HOLD_FRAME;
    }
}

fn chick_duck_up(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.aiflags &= !AI_DUCKED;
    self_ent.maxs[2] += 32.0;
    self_ent.takedamage = Damage::Aim as i32;
    gi_linkentity(self_ent);
}

pub fn chick_dodge(self_ent: &mut Edict, _attacker: &mut Edict, _eta: f32, _ctx: &mut GameContext) {
    if random() > 0.25 {
        return;
    }

    // if (!self->enemy) self->enemy = attacker;
    if self_ent.enemy < 0 {
        self_ent.enemy = _attacker.s.number;
    }

    self_ent.monsterinfo.currentmove = Some(MOVE_DUCK);
}

fn chick_slash_attack(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let aim: [f32; 3] = [MELEE_DISTANCE, self_ent.mins[0], 10.0];
    let snd = SOUNDS.get().map_or(0, |s| s.melee_swing);
    gi_sound(self_ent, CHAN_WEAPON, snd, 1.0, ATTN_NORM, 0.0);
    fire_hit(self_ent, &aim, 10 + (rand_i32() % 6), 100);
}

fn chick_rocket(self_ent: &mut Edict, ctx: &mut GameContext) {
    let mut forward = [0.0_f32; 3];
    let mut right = [0.0_f32; 3];
    angle_vectors(&self_ent.s.angles, Some(&mut forward), Some(&mut right), None);

    let offset = crate::m_flash::MONSTER_FLASH_OFFSET[MZ2_CHICK_ROCKET_1 as usize];
    let start = crate::g_utils::g_project_source(&self_ent.s.origin, &offset, &forward, &right);

    let enemy_idx = self_ent.enemy;
    let mut vec = [0.0_f32; 3];
    if enemy_idx > 0 && (enemy_idx as usize) < ctx.edicts.len() {
        let enemy = &ctx.edicts[enemy_idx as usize];
        vec = enemy.s.origin;
        vec[2] += enemy.viewheight as f32;
    }
    let mut dir = vector_subtract(&vec, &start);
    vector_normalize(&mut dir);

    let self_idx = self_ent.s.number;
    crate::g_monster::monster_fire_rocket(ctx, self_idx, start, dir, 50, 500, MZ2_CHICK_ROCKET_1);
}

fn chick_pre_attack1(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let snd = SOUNDS.get().map_or(0, |s| s.missile_prelaunch);
    gi_sound(self_ent, CHAN_VOICE, snd, 1.0, ATTN_NORM, 0.0);
}

fn chick_reload(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let snd = SOUNDS.get().map_or(0, |s| s.missile_reload);
    gi_sound(self_ent, CHAN_VOICE, snd, 1.0, ATTN_NORM, 0.0);
}

fn chick_attack1(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_ATTACK1);
}

fn chick_rerocket(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let enemy_idx = self_ent.enemy;
    if enemy_idx > 0 && (enemy_idx as usize) < _ctx.edicts.len() {
        let enemy = &_ctx.edicts[enemy_idx as usize];
        if enemy.health > 0
            && range(self_ent, enemy) > RANGE_MELEE
            && visible(self_ent, enemy)
            && random() <= 0.6
        {
            self_ent.monsterinfo.currentmove = Some(MOVE_ATTACK1);
            return;
        }
    }
    self_ent.monsterinfo.currentmove = Some(MOVE_END_ATTACK1);
}

fn chick_reslash(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let enemy_idx = self_ent.enemy;
    if enemy_idx > 0 && (enemy_idx as usize) < _ctx.edicts.len() {
        let enemy = &_ctx.edicts[enemy_idx as usize];
        if enemy.health > 0 {
            if range(self_ent, enemy) == RANGE_MELEE {
                if random() <= 0.9 {
                    self_ent.monsterinfo.currentmove = Some(MOVE_SLASH);
                    return;
                } else {
                    self_ent.monsterinfo.currentmove = Some(MOVE_END_SLASH);
                    return;
                }
            }
        }
    }
    self_ent.monsterinfo.currentmove = Some(MOVE_END_SLASH);
}

fn chick_slash_begin(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_SLASH);
}

pub fn chick_melee(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_START_SLASH);
}

pub fn chick_attack(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_START_ATTACK1);
}

pub fn chick_sight(self_ent: &mut Edict, _other: &mut Edict) {
    let snd = SOUNDS.get().map_or(0, |s| s.sight);
    gi_sound(self_ent, CHAN_VOICE, snd, 1.0, ATTN_NORM, 0.0);
}

// ============================================================
// Animation tables
// ============================================================

// --- Fidget: FRAME_stand201..FRAME_stand230, 30 frames ---
static CHICK_FRAMES_FIDGET: [MFrame; 30] = [
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: Some(chick_moan) },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
];

pub static CHICK_MOVE_FIDGET: MMove = MMove {
    firstframe: FRAME_STAND201,
    lastframe: FRAME_STAND230,
    frames: &CHICK_FRAMES_FIDGET,
    endfunc: Some(chick_stand),
};

// --- Stand: FRAME_stand101..FRAME_stand130, 30 frames ---
static CHICK_FRAMES_STAND: [MFrame; 30] = [
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: Some(chick_fidget) },
];

pub static CHICK_MOVE_STAND: MMove = MMove {
    firstframe: FRAME_STAND101,
    lastframe: FRAME_STAND130,
    frames: &CHICK_FRAMES_STAND,
    endfunc: None,
};

// --- Start Run: FRAME_walk01..FRAME_walk10, 10 frames ---
static CHICK_FRAMES_START_RUN: [MFrame; 10] = [
    MFrame { ai_fn: ai_run, dist: 1.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: -1.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: -1.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: 1.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: 3.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: 6.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: 3.0,  think_fn: None },
];

pub static CHICK_MOVE_START_RUN: MMove = MMove {
    firstframe: FRAME_WALK01,
    lastframe: FRAME_WALK10,
    frames: &CHICK_FRAMES_START_RUN,
    endfunc: Some(chick_run),
};

// --- Run: FRAME_walk11..FRAME_walk20, 10 frames ---
static CHICK_FRAMES_RUN: [MFrame; 10] = [
    MFrame { ai_fn: ai_run, dist: 6.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: 8.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: 13.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 5.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: 7.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: 4.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: 11.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 5.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: 9.0,  think_fn: None },
    MFrame { ai_fn: ai_run, dist: 7.0,  think_fn: None },
];

pub static CHICK_MOVE_RUN: MMove = MMove {
    firstframe: FRAME_WALK11,
    lastframe: FRAME_WALK20,
    frames: &CHICK_FRAMES_RUN,
    endfunc: None,
};

// --- Walk: FRAME_walk11..FRAME_walk20, 10 frames ---
static CHICK_FRAMES_WALK: [MFrame; 10] = [
    MFrame { ai_fn: ai_walk, dist: 6.0,  think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 8.0,  think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 13.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0,  think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 7.0,  think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0,  think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 11.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0,  think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 9.0,  think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 7.0,  think_fn: None },
];

pub static CHICK_MOVE_WALK: MMove = MMove {
    firstframe: FRAME_WALK11,
    lastframe: FRAME_WALK20,
    frames: &CHICK_FRAMES_WALK,
    endfunc: None,
};

// --- Pain1: FRAME_pain101..FRAME_pain105, 5 frames ---
static CHICK_FRAMES_PAIN1: [MFrame; 5] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static CHICK_MOVE_PAIN1: MMove = MMove {
    firstframe: FRAME_PAIN101,
    lastframe: FRAME_PAIN105,
    frames: &CHICK_FRAMES_PAIN1,
    endfunc: Some(chick_run),
};

// --- Pain2: FRAME_pain201..FRAME_pain205, 5 frames ---
static CHICK_FRAMES_PAIN2: [MFrame; 5] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static CHICK_MOVE_PAIN2: MMove = MMove {
    firstframe: FRAME_PAIN201,
    lastframe: FRAME_PAIN205,
    frames: &CHICK_FRAMES_PAIN2,
    endfunc: Some(chick_run),
};

// --- Pain3: FRAME_pain301..FRAME_pain321, 21 frames ---
static CHICK_FRAMES_PAIN3: [MFrame; 21] = [
    MFrame { ai_fn: ai_move, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: -6.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 3.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 11.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 3.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 4.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: -3.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -4.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 5.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 7.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: -2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 3.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: -5.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -8.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0,  think_fn: None },
];

pub static CHICK_MOVE_PAIN3: MMove = MMove {
    firstframe: FRAME_PAIN301,
    lastframe: FRAME_PAIN321,
    frames: &CHICK_FRAMES_PAIN3,
    endfunc: Some(chick_run),
};

// --- Death1: FRAME_death101..FRAME_death112, 12 frames ---
static CHICK_FRAMES_DEATH1: [MFrame; 12] = [
    MFrame { ai_fn: ai_move, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: -7.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 4.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 11.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,  think_fn: None },
];

pub static CHICK_MOVE_DEATH1: MMove = MMove {
    firstframe: FRAME_DEATH101,
    lastframe: FRAME_DEATH112,
    frames: &CHICK_FRAMES_DEATH1,
    endfunc: Some(chick_dead),
};

// --- Death2: FRAME_death201..FRAME_death223, 23 frames ---
static CHICK_FRAMES_DEATH2: [MFrame; 23] = [
    MFrame { ai_fn: ai_move, dist: -6.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: -1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -5.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: -1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 3.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 3.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 3.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: -3.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -5.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 4.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 15.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 14.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0,  think_fn: None },
];

pub static CHICK_MOVE_DEATH2: MMove = MMove {
    firstframe: FRAME_DEATH201,
    lastframe: FRAME_DEATH223,
    frames: &CHICK_FRAMES_DEATH2,
    endfunc: Some(chick_dead),
};

// --- Duck: FRAME_duck01..FRAME_duck07, 7 frames ---
static CHICK_FRAMES_DUCK: [MFrame; 7] = [
    MFrame { ai_fn: ai_move, dist: 0.0,  think_fn: Some(chick_duck_down) },
    MFrame { ai_fn: ai_move, dist: 1.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 4.0,  think_fn: Some(chick_duck_hold) },
    MFrame { ai_fn: ai_move, dist: -4.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -5.0, think_fn: Some(chick_duck_up) },
    MFrame { ai_fn: ai_move, dist: 3.0,  think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0,  think_fn: None },
];

pub static CHICK_MOVE_DUCK: MMove = MMove {
    firstframe: FRAME_DUCK01,
    lastframe: FRAME_DUCK07,
    frames: &CHICK_FRAMES_DUCK,
    endfunc: Some(chick_run),
};

// --- Start Attack1: FRAME_attak101..FRAME_attak113, 13 frames ---
static CHICK_FRAMES_START_ATTACK1: [MFrame; 13] = [
    MFrame { ai_fn: ai_charge, dist: 0.0,  think_fn: Some(chick_pre_attack1) },
    MFrame { ai_fn: ai_charge, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 4.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -3.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 3.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 5.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 7.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0,  think_fn: Some(chick_attack1) },
];

pub static CHICK_MOVE_START_ATTACK1: MMove = MMove {
    firstframe: FRAME_ATTAK101,
    lastframe: FRAME_ATTAK113,
    frames: &CHICK_FRAMES_START_ATTACK1,
    endfunc: None,
};

// --- Attack1: FRAME_attak114..FRAME_attak127, 14 frames ---
static CHICK_FRAMES_ATTACK1: [MFrame; 14] = [
    MFrame { ai_fn: ai_charge, dist: 19.0, think_fn: Some(chick_rocket) },
    MFrame { ai_fn: ai_charge, dist: -6.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -5.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -2.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -7.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 1.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 10.0, think_fn: Some(chick_reload) },
    MFrame { ai_fn: ai_charge, dist: 4.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 5.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 6.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 6.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 4.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 3.0,  think_fn: Some(chick_rerocket) },
];

pub static CHICK_MOVE_ATTACK1: MMove = MMove {
    firstframe: FRAME_ATTAK114,
    lastframe: FRAME_ATTAK127,
    frames: &CHICK_FRAMES_ATTACK1,
    endfunc: None,
};

// --- End Attack1: FRAME_attak128..FRAME_attak132, 5 frames ---
static CHICK_FRAMES_END_ATTACK1: [MFrame; 5] = [
    MFrame { ai_fn: ai_charge, dist: -3.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -6.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -4.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -2.0, think_fn: None },
];

pub static CHICK_MOVE_END_ATTACK1: MMove = MMove {
    firstframe: FRAME_ATTAK128,
    lastframe: FRAME_ATTAK132,
    frames: &CHICK_FRAMES_END_ATTACK1,
    endfunc: Some(chick_run),
};

// --- Slash: FRAME_attak204..FRAME_attak212, 9 frames ---
static CHICK_FRAMES_SLASH: [MFrame; 9] = [
    MFrame { ai_fn: ai_charge, dist: 1.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 7.0,  think_fn: Some(chick_slash_attack) },
    MFrame { ai_fn: ai_charge, dist: -7.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 1.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -1.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 1.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 1.0,  think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -2.0, think_fn: Some(chick_reslash) },
];

pub static CHICK_MOVE_SLASH: MMove = MMove {
    firstframe: FRAME_ATTAK204,
    lastframe: FRAME_ATTAK212,
    frames: &CHICK_FRAMES_SLASH,
    endfunc: None,
};

// --- End Slash: FRAME_attak213..FRAME_attak216, 4 frames ---
static CHICK_FRAMES_END_SLASH: [MFrame; 4] = [
    MFrame { ai_fn: ai_charge, dist: -6.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -1.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -6.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0,  think_fn: None },
];

pub static CHICK_MOVE_END_SLASH: MMove = MMove {
    firstframe: FRAME_ATTAK213,
    lastframe: FRAME_ATTAK216,
    frames: &CHICK_FRAMES_END_SLASH,
    endfunc: Some(chick_run),
};

// --- Start Slash: FRAME_attak201..FRAME_attak203, 3 frames ---
static CHICK_FRAMES_START_SLASH: [MFrame; 3] = [
    MFrame { ai_fn: ai_charge, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 8.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 3.0, think_fn: None },
];

pub static CHICK_MOVE_START_SLASH: MMove = MMove {
    firstframe: FRAME_ATTAK201,
    lastframe: FRAME_ATTAK203,
    frames: &CHICK_FRAMES_START_SLASH,
    endfunc: Some(chick_slash_begin),
};

// ============================================================
// Spawn function
// ============================================================

/// QUAKED monster_chick (1 .5 0) (-16 -16 -24) (16 16 32) Ambush Trigger_Spawn Sight
pub fn sp_monster_chick(self_ent: &mut Edict, ctx: &mut GameContext) {
    if ctx.deathmatch != 0.0 {
        g_free_edict(self_ent);
        return;
    }

    // Pre-cache sounds
    SOUNDS.get_or_init(|| ChickSounds {
        missile_prelaunch: gi_soundindex("chick/chkatck1.wav"),
        missile_launch:    gi_soundindex("chick/chkatck2.wav"),
        melee_swing:       gi_soundindex("chick/chkatck3.wav"),
        melee_hit:         gi_soundindex("chick/chkatck4.wav"),
        missile_reload:    gi_soundindex("chick/chkatck5.wav"),
        death1:            gi_soundindex("chick/chkdeth1.wav"),
        death2:            gi_soundindex("chick/chkdeth2.wav"),
        fall_down:         gi_soundindex("chick/chkfall1.wav"),
        idle1:             gi_soundindex("chick/chkidle1.wav"),
        idle2:             gi_soundindex("chick/chkidle2.wav"),
        pain1:             gi_soundindex("chick/chkpain1.wav"),
        pain2:             gi_soundindex("chick/chkpain2.wav"),
        pain3:             gi_soundindex("chick/chkpain3.wav"),
        sight:             gi_soundindex("chick/chksght1.wav"),
        search:            gi_soundindex("chick/chksrch1.wav"),
    });

    self_ent.movetype = MoveType::Step;
    self_ent.solid = Solid::Bbox;
    self_ent.s.modelindex = gi_modelindex("models/monsters/bitch/tris.md2");
    self_ent.mins = [-16.0, -16.0, 0.0];
    self_ent.maxs = [16.0, 16.0, 56.0];

    self_ent.health = 175;
    self_ent.gib_health = -70;
    self_ent.mass = 200;

    // Function callbacks stored as indices into dispatch tables
    self_ent.pain_fn = Some(crate::dispatch::PAIN_CHICK);
    self_ent.die_fn = Some(crate::dispatch::DIE_CHICK);

    self_ent.monsterinfo.stand_fn = Some(crate::dispatch::MSTAND_CHICK);
    self_ent.monsterinfo.walk_fn = Some(crate::dispatch::MWALK_CHICK);
    self_ent.monsterinfo.run_fn = Some(crate::dispatch::MRUN_CHICK);
    self_ent.monsterinfo.dodge_fn = Some(crate::dispatch::MDODGE_CHICK);
    self_ent.monsterinfo.attack_fn = Some(crate::dispatch::MATTACK_CHICK);
    self_ent.monsterinfo.melee_fn = Some(crate::dispatch::MMELEE_CHICK);
    self_ent.monsterinfo.sight_fn = Some(crate::dispatch::MSIGHT_CHICK);

    gi_linkentity(self_ent);

    self_ent.monsterinfo.currentmove = Some(MOVE_STAND);
    self_ent.monsterinfo.scale = MODEL_SCALE;

    walkmonster_start(self_ent);
}

// ============================================================
// Move table: maps move indices to MMove statics
// ============================================================

/// Returns the MMove for a given chick move index.
pub fn chick_get_move(index: usize) -> Option<&'static MMove> {
    match index {
        MOVE_FIDGET        => Some(&CHICK_MOVE_FIDGET),
        MOVE_STAND         => Some(&CHICK_MOVE_STAND),
        MOVE_START_RUN     => Some(&CHICK_MOVE_START_RUN),
        MOVE_RUN           => Some(&CHICK_MOVE_RUN),
        MOVE_WALK          => Some(&CHICK_MOVE_WALK),
        MOVE_PAIN1         => Some(&CHICK_MOVE_PAIN1),
        MOVE_PAIN2         => Some(&CHICK_MOVE_PAIN2),
        MOVE_PAIN3         => Some(&CHICK_MOVE_PAIN3),
        MOVE_DEATH1        => Some(&CHICK_MOVE_DEATH1),
        MOVE_DEATH2        => Some(&CHICK_MOVE_DEATH2),
        MOVE_DUCK          => Some(&CHICK_MOVE_DUCK),
        MOVE_START_ATTACK1 => Some(&CHICK_MOVE_START_ATTACK1),
        MOVE_ATTACK1       => Some(&CHICK_MOVE_ATTACK1),
        MOVE_END_ATTACK1   => Some(&CHICK_MOVE_END_ATTACK1),
        MOVE_SLASH         => Some(&CHICK_MOVE_SLASH),
        MOVE_END_SLASH     => Some(&CHICK_MOVE_END_SLASH),
        MOVE_START_SLASH   => Some(&CHICK_MOVE_START_SLASH),
        _ => None,
    }
}
