// m_flyer.rs — Flyer monster
// Converted from: myq2-original/game/m_flyer.c
// Frame definitions from: myq2-original/game/m_flyer.h

use crate::g_local::*;
use crate::game::*;
use crate::entity_adapters::{
    gi_sound, gi_soundindex, gi_modelindex, gi_linkentity,
    g_free_edict, flymonster_start, range,
    monster_flash_offset, g_project_source,
    fire_hit, monster_fire_blaster,
};
use crate::game_import::skill_value;
use myq2_common::common::{frand as random, rand_i32};
use myq2_common::q_shared::q_streq_nocase;

// ============================================================
// Frame definitions (from m_flyer.h)
// This file generated by ModelGen - Do NOT Modify
// ============================================================

// Actions
pub const ACTION_NOTHING: i32 = 0;
pub const ACTION_ATTACK1: i32 = 1;
pub const ACTION_ATTACK2: i32 = 2;
pub const ACTION_RUN: i32 = 3;
pub const ACTION_WALK: i32 = 4;

pub const FRAME_START01: i32 = 0;
pub const FRAME_START02: i32 = 1;
pub const FRAME_START03: i32 = 2;
pub const FRAME_START04: i32 = 3;
pub const FRAME_START05: i32 = 4;
pub const FRAME_START06: i32 = 5;
pub const FRAME_STOP01: i32 = 6;
pub const FRAME_STOP02: i32 = 7;
pub const FRAME_STOP03: i32 = 8;
pub const FRAME_STOP04: i32 = 9;
pub const FRAME_STOP05: i32 = 10;
pub const FRAME_STOP06: i32 = 11;
pub const FRAME_STOP07: i32 = 12;
pub const FRAME_STAND01: i32 = 13;
pub const FRAME_STAND02: i32 = 14;
pub const FRAME_STAND03: i32 = 15;
pub const FRAME_STAND04: i32 = 16;
pub const FRAME_STAND05: i32 = 17;
pub const FRAME_STAND06: i32 = 18;
pub const FRAME_STAND07: i32 = 19;
pub const FRAME_STAND08: i32 = 20;
pub const FRAME_STAND09: i32 = 21;
pub const FRAME_STAND10: i32 = 22;
pub const FRAME_STAND11: i32 = 23;
pub const FRAME_STAND12: i32 = 24;
pub const FRAME_STAND13: i32 = 25;
pub const FRAME_STAND14: i32 = 26;
pub const FRAME_STAND15: i32 = 27;
pub const FRAME_STAND16: i32 = 28;
pub const FRAME_STAND17: i32 = 29;
pub const FRAME_STAND18: i32 = 30;
pub const FRAME_STAND19: i32 = 31;
pub const FRAME_STAND20: i32 = 32;
pub const FRAME_STAND21: i32 = 33;
pub const FRAME_STAND22: i32 = 34;
pub const FRAME_STAND23: i32 = 35;
pub const FRAME_STAND24: i32 = 36;
pub const FRAME_STAND25: i32 = 37;
pub const FRAME_STAND26: i32 = 38;
pub const FRAME_STAND27: i32 = 39;
pub const FRAME_STAND28: i32 = 40;
pub const FRAME_STAND29: i32 = 41;
pub const FRAME_STAND30: i32 = 42;
pub const FRAME_STAND31: i32 = 43;
pub const FRAME_STAND32: i32 = 44;
pub const FRAME_STAND33: i32 = 45;
pub const FRAME_STAND34: i32 = 46;
pub const FRAME_STAND35: i32 = 47;
pub const FRAME_STAND36: i32 = 48;
pub const FRAME_STAND37: i32 = 49;
pub const FRAME_STAND38: i32 = 50;
pub const FRAME_STAND39: i32 = 51;
pub const FRAME_STAND40: i32 = 52;
pub const FRAME_STAND41: i32 = 53;
pub const FRAME_STAND42: i32 = 54;
pub const FRAME_STAND43: i32 = 55;
pub const FRAME_STAND44: i32 = 56;
pub const FRAME_STAND45: i32 = 57;
pub const FRAME_ATTAK101: i32 = 58;
pub const FRAME_ATTAK102: i32 = 59;
pub const FRAME_ATTAK103: i32 = 60;
pub const FRAME_ATTAK104: i32 = 61;
pub const FRAME_ATTAK105: i32 = 62;
pub const FRAME_ATTAK106: i32 = 63;
pub const FRAME_ATTAK107: i32 = 64;
pub const FRAME_ATTAK108: i32 = 65;
pub const FRAME_ATTAK109: i32 = 66;
pub const FRAME_ATTAK110: i32 = 67;
pub const FRAME_ATTAK111: i32 = 68;
pub const FRAME_ATTAK112: i32 = 69;
pub const FRAME_ATTAK113: i32 = 70;
pub const FRAME_ATTAK114: i32 = 71;
pub const FRAME_ATTAK115: i32 = 72;
pub const FRAME_ATTAK116: i32 = 73;
pub const FRAME_ATTAK117: i32 = 74;
pub const FRAME_ATTAK118: i32 = 75;
pub const FRAME_ATTAK119: i32 = 76;
pub const FRAME_ATTAK120: i32 = 77;
pub const FRAME_ATTAK121: i32 = 78;
pub const FRAME_ATTAK201: i32 = 79;
pub const FRAME_ATTAK202: i32 = 80;
pub const FRAME_ATTAK203: i32 = 81;
pub const FRAME_ATTAK204: i32 = 82;
pub const FRAME_ATTAK205: i32 = 83;
pub const FRAME_ATTAK206: i32 = 84;
pub const FRAME_ATTAK207: i32 = 85;
pub const FRAME_ATTAK208: i32 = 86;
pub const FRAME_ATTAK209: i32 = 87;
pub const FRAME_ATTAK210: i32 = 88;
pub const FRAME_ATTAK211: i32 = 89;
pub const FRAME_ATTAK212: i32 = 90;
pub const FRAME_ATTAK213: i32 = 91;
pub const FRAME_ATTAK214: i32 = 92;
pub const FRAME_ATTAK215: i32 = 93;
pub const FRAME_ATTAK216: i32 = 94;
pub const FRAME_ATTAK217: i32 = 95;
pub const FRAME_BANKL01: i32 = 96;
pub const FRAME_BANKL02: i32 = 97;
pub const FRAME_BANKL03: i32 = 98;
pub const FRAME_BANKL04: i32 = 99;
pub const FRAME_BANKL05: i32 = 100;
pub const FRAME_BANKL06: i32 = 101;
pub const FRAME_BANKL07: i32 = 102;
pub const FRAME_BANKR01: i32 = 103;
pub const FRAME_BANKR02: i32 = 104;
pub const FRAME_BANKR03: i32 = 105;
pub const FRAME_BANKR04: i32 = 106;
pub const FRAME_BANKR05: i32 = 107;
pub const FRAME_BANKR06: i32 = 108;
pub const FRAME_BANKR07: i32 = 109;
pub const FRAME_ROLLF01: i32 = 110;
pub const FRAME_ROLLF02: i32 = 111;
pub const FRAME_ROLLF03: i32 = 112;
pub const FRAME_ROLLF04: i32 = 113;
pub const FRAME_ROLLF05: i32 = 114;
pub const FRAME_ROLLF06: i32 = 115;
pub const FRAME_ROLLF07: i32 = 116;
pub const FRAME_ROLLF08: i32 = 117;
pub const FRAME_ROLLF09: i32 = 118;
pub const FRAME_ROLLR01: i32 = 119;
pub const FRAME_ROLLR02: i32 = 120;
pub const FRAME_ROLLR03: i32 = 121;
pub const FRAME_ROLLR04: i32 = 122;
pub const FRAME_ROLLR05: i32 = 123;
pub const FRAME_ROLLR06: i32 = 124;
pub const FRAME_ROLLR07: i32 = 125;
pub const FRAME_ROLLR08: i32 = 126;
pub const FRAME_ROLLR09: i32 = 127;
pub const FRAME_DEFENS01: i32 = 128;
pub const FRAME_DEFENS02: i32 = 129;
pub const FRAME_DEFENS03: i32 = 130;
pub const FRAME_DEFENS04: i32 = 131;
pub const FRAME_DEFENS05: i32 = 132;
pub const FRAME_DEFENS06: i32 = 133;
pub const FRAME_PAIN101: i32 = 134;
pub const FRAME_PAIN102: i32 = 135;
pub const FRAME_PAIN103: i32 = 136;
pub const FRAME_PAIN104: i32 = 137;
pub const FRAME_PAIN105: i32 = 138;
pub const FRAME_PAIN106: i32 = 139;
pub const FRAME_PAIN107: i32 = 140;
pub const FRAME_PAIN108: i32 = 141;
pub const FRAME_PAIN109: i32 = 142;
pub const FRAME_PAIN201: i32 = 143;
pub const FRAME_PAIN202: i32 = 144;
pub const FRAME_PAIN203: i32 = 145;
pub const FRAME_PAIN204: i32 = 146;
pub const FRAME_PAIN301: i32 = 147;
pub const FRAME_PAIN302: i32 = 148;
pub const FRAME_PAIN303: i32 = 149;
pub const FRAME_PAIN304: i32 = 150;

pub const MODEL_SCALE: f32 = 1.0;

// ============================================================
// Sound channel / attenuation constants (mirrors C defines)
// ============================================================

// CHAN_*, ATTN_*, EF_* come from g_local::* re-export (myq2_common::q_shared)

// Muzzle flash indices for flyer
const MZ2_FLYER_BLASTER_1: i32 = 58;
const MZ2_FLYER_BLASTER_2: i32 = 59;

use crate::ai_wrappers::{ai_stand, ai_walk, ai_run, ai_charge, ai_move};

// ============================================================
// Sound indices (module-level state, replaces C statics)
// ============================================================

#[derive(Default)]
pub struct FlyerSounds {
    pub sight: i32,
    pub idle: i32,
    pub pain1: i32,
    pub pain2: i32,
    pub slash: i32,
    pub sproing: i32,
    pub die: i32,
}

static SOUNDS: std::sync::OnceLock<FlyerSounds> = std::sync::OnceLock::new();

// NEXTMOVE state is stored per-entity in self_ent.count (was C file-static)

use myq2_common::q_shared::angle_vectors;


use crate::game_import::deathmatch_value;

fn level_time() -> f32 {
    crate::g_local::with_global_game_ctx(|ctx| ctx.level.time).unwrap_or(0.0)
}

fn level_mapname() -> String {
    crate::g_local::with_global_game_ctx(|ctx| ctx.level.mapname.clone()).unwrap_or_default()
}

// ============================================================
// Move table indices (via monsterinfo.currentmove)
// ============================================================

pub const MOVE_STAND: usize = 0;
pub const MOVE_WALK: usize = 1;
pub const MOVE_RUN: usize = 2;
pub const MOVE_START: usize = 3;
pub const MOVE_STOP: usize = 4;
pub const MOVE_ROLLRIGHT: usize = 5;
pub const MOVE_ROLLLEFT: usize = 6;
pub const MOVE_PAIN1: usize = 7;
pub const MOVE_PAIN2: usize = 8;
pub const MOVE_PAIN3: usize = 9;
pub const MOVE_DEFENSE: usize = 10;
pub const MOVE_BANKRIGHT: usize = 11;
pub const MOVE_BANKLEFT: usize = 12;
pub const MOVE_ATTACK2: usize = 13;
pub const MOVE_START_MELEE: usize = 14;
pub const MOVE_END_MELEE: usize = 15;
pub const MOVE_LOOP_MELEE: usize = 16;

// ============================================================
// Flyer behavior functions
// ============================================================

pub fn flyer_sight(self_ent: &mut Edict, _other: &mut Edict) {
    let sound_sight = SOUNDS.get().map_or(0, |s| s.sight);
    gi_sound(self_ent, CHAN_VOICE, sound_sight, 1.0, ATTN_NORM, 0.0);
}

pub fn flyer_idle(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let sound_idle = SOUNDS.get().map_or(0, |s| s.idle);
    gi_sound(self_ent, CHAN_VOICE, sound_idle, 1.0, ATTN_IDLE, 0.0);
}

pub fn flyer_pop_blades(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let sound_sproing = SOUNDS.get().map_or(0, |s| s.sproing);
    gi_sound(self_ent, CHAN_VOICE, sound_sproing, 1.0, ATTN_NORM, 0.0);
}

// ============================================================
// Stand animation
// ============================================================

static FLYER_FRAMES_STAND: [MFrame; 45] = [
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
];

pub static FLYER_MOVE_STAND: MMove = MMove {
    firstframe: FRAME_STAND01,
    lastframe: FRAME_STAND45,
    frames: &FLYER_FRAMES_STAND,
    endfunc: None,
};

// ============================================================
// Walk animation
// ============================================================

static FLYER_FRAMES_WALK: [MFrame; 45] = [
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
];

pub static FLYER_MOVE_WALK: MMove = MMove {
    firstframe: FRAME_STAND01,
    lastframe: FRAME_STAND45,
    frames: &FLYER_FRAMES_WALK,
    endfunc: None,
};

// ============================================================
// Run animation
// ============================================================

static FLYER_FRAMES_RUN: [MFrame; 45] = [
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
];

pub static FLYER_MOVE_RUN: MMove = MMove {
    firstframe: FRAME_STAND01,
    lastframe: FRAME_STAND45,
    frames: &FLYER_FRAMES_RUN,
    endfunc: None,
};

pub fn flyer_run(self_ent: &mut Edict, _ctx: &mut GameContext) {
    if self_ent.monsterinfo.aiflags.intersects(AI_STAND_GROUND) {
        self_ent.monsterinfo.currentmove = Some(MOVE_STAND);
    } else {
        self_ent.monsterinfo.currentmove = Some(MOVE_RUN);
    }
}

pub fn flyer_walk(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_WALK);
}

pub fn flyer_stand(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_STAND);
}

// ============================================================
// Start animation
// ============================================================

fn flyer_nextmove(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let next = self_ent.count;
    if next == ACTION_ATTACK1 {
        self_ent.monsterinfo.currentmove = Some(MOVE_START_MELEE);
    } else if next == ACTION_ATTACK2 {
        self_ent.monsterinfo.currentmove = Some(MOVE_ATTACK2);
    } else if next == ACTION_RUN {
        self_ent.monsterinfo.currentmove = Some(MOVE_RUN);
    }
}

static FLYER_FRAMES_START: [MFrame; 6] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: Some(flyer_nextmove) },
];

pub static FLYER_MOVE_START: MMove = MMove {
    firstframe: FRAME_START01,
    lastframe: FRAME_START06,
    frames: &FLYER_FRAMES_START,
    endfunc: None,
};

// ============================================================
// Stop animation
// ============================================================

static FLYER_FRAMES_STOP: [MFrame; 7] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: Some(flyer_nextmove) },
];

pub static FLYER_MOVE_STOP: MMove = MMove {
    firstframe: FRAME_STOP01,
    lastframe: FRAME_STOP07,
    frames: &FLYER_FRAMES_STOP,
    endfunc: None,
};

pub fn flyer_stop(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_STOP);
}

pub fn flyer_start(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_START);
}

// ============================================================
// Roll right animation
// ============================================================

static FLYER_FRAMES_ROLLRIGHT: [MFrame; 9] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static FLYER_MOVE_ROLLRIGHT: MMove = MMove {
    firstframe: FRAME_ROLLR01,
    lastframe: FRAME_ROLLR09,
    frames: &FLYER_FRAMES_ROLLRIGHT,
    endfunc: None,
};

// ============================================================
// Roll left animation
// ============================================================

static FLYER_FRAMES_ROLLLEFT: [MFrame; 9] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static FLYER_MOVE_ROLLLEFT: MMove = MMove {
    firstframe: FRAME_ROLLF01,
    lastframe: FRAME_ROLLF09,
    frames: &FLYER_FRAMES_ROLLLEFT,
    endfunc: None,
};

// ============================================================
// Pain animations
// ============================================================

static FLYER_FRAMES_PAIN3: [MFrame; 4] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static FLYER_MOVE_PAIN3: MMove = MMove {
    firstframe: FRAME_PAIN301,
    lastframe: FRAME_PAIN304,
    frames: &FLYER_FRAMES_PAIN3,
    endfunc: Some(flyer_run),
};

static FLYER_FRAMES_PAIN2: [MFrame; 4] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static FLYER_MOVE_PAIN2: MMove = MMove {
    firstframe: FRAME_PAIN201,
    lastframe: FRAME_PAIN204,
    frames: &FLYER_FRAMES_PAIN2,
    endfunc: Some(flyer_run),
};

static FLYER_FRAMES_PAIN1: [MFrame; 9] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static FLYER_MOVE_PAIN1: MMove = MMove {
    firstframe: FRAME_PAIN101,
    lastframe: FRAME_PAIN109,
    frames: &FLYER_FRAMES_PAIN1,
    endfunc: Some(flyer_run),
};

// ============================================================
// Defense animation
// ============================================================

static FLYER_FRAMES_DEFENSE: [MFrame; 6] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None }, // Hold this frame
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static FLYER_MOVE_DEFENSE: MMove = MMove {
    firstframe: FRAME_DEFENS01,
    lastframe: FRAME_DEFENS06,
    frames: &FLYER_FRAMES_DEFENSE,
    endfunc: None,
};

// ============================================================
// Bank right animation
// ============================================================

static FLYER_FRAMES_BANKRIGHT: [MFrame; 7] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static FLYER_MOVE_BANKRIGHT: MMove = MMove {
    firstframe: FRAME_BANKR01,
    lastframe: FRAME_BANKR07,
    frames: &FLYER_FRAMES_BANKRIGHT,
    endfunc: None,
};

// ============================================================
// Bank left animation
// ============================================================

static FLYER_FRAMES_BANKLEFT: [MFrame; 7] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static FLYER_MOVE_BANKLEFT: MMove = MMove {
    firstframe: FRAME_BANKL01,
    lastframe: FRAME_BANKL07,
    frames: &FLYER_FRAMES_BANKLEFT,
    endfunc: None,
};

// ============================================================
// Attack (ranged) — flyer_fire, flyer_fireleft, flyer_fireright
// ============================================================

pub fn flyer_fire(self_ent: &mut Edict, flash_number: i32, edicts: &[Edict]) {
    let mut start = [0.0_f32; 3];
    let mut forward = [0.0_f32; 3];
    let mut right = [0.0_f32; 3];
    let mut end = [0.0_f32; 3];
    let mut dir = [0.0_f32; 3];

    let effect = if self_ent.s.frame == FRAME_ATTAK204
        || self_ent.s.frame == FRAME_ATTAK207
        || self_ent.s.frame == FRAME_ATTAK210
    {
        EF_HYPERBLASTER
    } else {
        0
    };

    angle_vectors(&self_ent.s.angles, Some(&mut forward), Some(&mut right), None);

    let offset = monster_flash_offset(flash_number);
    g_project_source(&self_ent.s.origin, &offset, &forward, &right, &mut start);

    // VectorCopy(self->enemy->s.origin, end)
    let enemy_idx = self_ent.enemy;
    if enemy_idx >= 0 && (enemy_idx as usize) < edicts.len() {
        let enemy = &edicts[enemy_idx as usize];
        end[0] = enemy.s.origin[0];
        end[1] = enemy.s.origin[1];
        end[2] = enemy.s.origin[2];
        end[2] += enemy.viewheight as f32;
    }

    // VectorSubtract(end, start, dir)
    dir[0] = end[0] - start[0];
    dir[1] = end[1] - start[1];
    dir[2] = end[2] - start[2];

    monster_fire_blaster(self_ent, start, dir, 1, 1000, flash_number, effect as i32);
}

pub fn flyer_fireleft(self_ent: &mut Edict, ctx: &mut GameContext) {
    flyer_fire(self_ent, MZ2_FLYER_BLASTER_1, &ctx.edicts);
}

pub fn flyer_fireright(self_ent: &mut Edict, ctx: &mut GameContext) {
    flyer_fire(self_ent, MZ2_FLYER_BLASTER_2, &ctx.edicts);
}

// ============================================================
// Attack2 animation (ranged blaster attack)
// ============================================================

static FLYER_FRAMES_ATTACK2: [MFrame; 17] = [
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: -10.0, think_fn: Some(flyer_fireleft) },   // left gun
    MFrame { ai_fn: ai_charge, dist: -10.0, think_fn: Some(flyer_fireright) },  // right gun
    MFrame { ai_fn: ai_charge, dist: -10.0, think_fn: Some(flyer_fireleft) },   // left gun
    MFrame { ai_fn: ai_charge, dist: -10.0, think_fn: Some(flyer_fireright) },  // right gun
    MFrame { ai_fn: ai_charge, dist: -10.0, think_fn: Some(flyer_fireleft) },   // left gun
    MFrame { ai_fn: ai_charge, dist: -10.0, think_fn: Some(flyer_fireright) },  // right gun
    MFrame { ai_fn: ai_charge, dist: -10.0, think_fn: Some(flyer_fireleft) },   // left gun
    MFrame { ai_fn: ai_charge, dist: -10.0, think_fn: Some(flyer_fireright) },  // right gun
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
];

pub static FLYER_MOVE_ATTACK2: MMove = MMove {
    firstframe: FRAME_ATTAK201,
    lastframe: FRAME_ATTAK217,
    frames: &FLYER_FRAMES_ATTACK2,
    endfunc: Some(flyer_run),
};

// ============================================================
// Melee attack — slash left/right
// ============================================================

pub fn flyer_slash_left(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let aim = [MELEE_DISTANCE, self_ent.mins[0], 0.0];
    fire_hit(self_ent, &aim, 5, 0);
    let sound_slash = SOUNDS.get().map_or(0, |s| s.slash);
    gi_sound(self_ent, CHAN_WEAPON, sound_slash, 1.0, ATTN_NORM, 0.0);
}

pub fn flyer_slash_right(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let aim = [MELEE_DISTANCE, self_ent.maxs[0], 0.0];
    fire_hit(self_ent, &aim, 5, 0);
    let sound_slash = SOUNDS.get().map_or(0, |s| s.slash);
    gi_sound(self_ent, CHAN_WEAPON, sound_slash, 1.0, ATTN_NORM, 0.0);
}

// ============================================================
// Start melee animation
// ============================================================

static FLYER_FRAMES_START_MELEE: [MFrame; 6] = [
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(flyer_pop_blades) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
];

pub static FLYER_MOVE_START_MELEE: MMove = MMove {
    firstframe: FRAME_ATTAK101,
    lastframe: FRAME_ATTAK106,
    frames: &FLYER_FRAMES_START_MELEE,
    endfunc: Some(flyer_loop_melee),
};

// ============================================================
// End melee animation
// ============================================================

static FLYER_FRAMES_END_MELEE: [MFrame; 3] = [
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
];

pub static FLYER_MOVE_END_MELEE: MMove = MMove {
    firstframe: FRAME_ATTAK119,
    lastframe: FRAME_ATTAK121,
    frames: &FLYER_FRAMES_END_MELEE,
    endfunc: Some(flyer_run),
};

// ============================================================
// Loop melee animation
// ============================================================

static FLYER_FRAMES_LOOP_MELEE: [MFrame; 12] = [
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },                      // Loop Start
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(flyer_slash_left) },    // Left Wing Strike
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(flyer_slash_right) },   // Right Wing Strike
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },                      // Loop Ends
];

pub static FLYER_MOVE_LOOP_MELEE: MMove = MMove {
    firstframe: FRAME_ATTAK107,
    lastframe: FRAME_ATTAK118,
    frames: &FLYER_FRAMES_LOOP_MELEE,
    endfunc: Some(flyer_check_melee),
};

pub fn flyer_loop_melee(self_ent: &mut Edict, _ctx: &mut GameContext) {
    // Original C had commented-out random branch for attack1
    self_ent.monsterinfo.currentmove = Some(MOVE_LOOP_MELEE);
}

pub fn flyer_attack(self_ent: &mut Edict, _ctx: &mut GameContext) {
    // Original C had commented-out random branch for attack1
    self_ent.monsterinfo.currentmove = Some(MOVE_ATTACK2);
}

pub fn flyer_setstart(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.count = ACTION_RUN;
    self_ent.monsterinfo.currentmove = Some(MOVE_START);
}

pub fn flyer_melee(self_ent: &mut Edict, _ctx: &mut GameContext) {
    // Original C had commented-out nextmove/stop approach
    self_ent.monsterinfo.currentmove = Some(MOVE_START_MELEE);
}

pub fn flyer_check_melee(self_ent: &mut Edict, ctx: &mut GameContext) {
    let enemy_idx = self_ent.enemy;
    if enemy_idx >= 0 && (enemy_idx as usize) < ctx.edicts.len() {
        let enemy = &ctx.edicts[enemy_idx as usize];
        if range(self_ent, enemy) == RANGE_MELEE {
            if random() <= 0.8 {
                self_ent.monsterinfo.currentmove = Some(MOVE_LOOP_MELEE);
            } else {
                self_ent.monsterinfo.currentmove = Some(MOVE_END_MELEE);
            }
        } else {
            self_ent.monsterinfo.currentmove = Some(MOVE_END_MELEE);
        }
    } else {
        self_ent.monsterinfo.currentmove = Some(MOVE_END_MELEE);
    }
}

// ============================================================
// Pain
// ============================================================

pub fn flyer_pain(self_ent: &mut Edict, _other: &mut Edict, _kick: f32, _damage: i32) {
    if self_ent.health < (self_ent.max_health / 2) {
        self_ent.s.skinnum = 1;
    }

    if level_time() < self_ent.pain_debounce_time {
        return;
    }

    self_ent.pain_debounce_time = level_time() + 3.0;
    if skill_value() == 3.0 {
        return; // no pain anims in nightmare
    }

    let n = rand_i32() % 3;
    if n == 0 {
        let sound_pain1 = SOUNDS.get().map_or(0, |s| s.pain1);
        gi_sound(self_ent, CHAN_VOICE, sound_pain1, 1.0, ATTN_NORM, 0.0);
        self_ent.monsterinfo.currentmove = Some(MOVE_PAIN1);
    } else if n == 1 {
        let sound_pain2 = SOUNDS.get().map_or(0, |s| s.pain2);
        gi_sound(self_ent, CHAN_VOICE, sound_pain2, 1.0, ATTN_NORM, 0.0);
        self_ent.monsterinfo.currentmove = Some(MOVE_PAIN2);
    } else {
        let sound_pain1 = SOUNDS.get().map_or(0, |s| s.pain1);
        gi_sound(self_ent, CHAN_VOICE, sound_pain1, 1.0, ATTN_NORM, 0.0);
        self_ent.monsterinfo.currentmove = Some(MOVE_PAIN3);
    }
}

// ============================================================
// Die
// ============================================================

pub fn flyer_die(self_ent: &mut Edict, _inflictor_idx: i32, _attacker_idx: i32, _damage: i32, _point: [f32; 3]) {
    let sound_die = SOUNDS.get().map_or(0, |s| s.die);
    gi_sound(self_ent, CHAN_VOICE, sound_die, 1.0, ATTN_NORM, 0.0);
    let self_idx = self_ent.s.number as usize;
    crate::g_local::with_global_game_ctx(|ctx| {
        crate::g_misc::become_explosion1(ctx, self_idx);
    });
}

// ============================================================
// Spawn function
// ============================================================

/// QUAKED monster_flyer (1 .5 0) (-16 -16 -24) (16 16 32) Ambush Trigger_Spawn Sight
pub fn sp_monster_flyer(self_ent: &mut Edict) {
    if deathmatch_value() != 0.0 {
        g_free_edict(self_ent);
        return;
    }

    // fix a map bug in jail5.bsp
    if q_streq_nocase(&level_mapname(), "jail5") && (self_ent.s.origin[2] == -104.0) {
        self_ent.targetname = self_ent.target.clone();
        self_ent.target = String::new();
    }

    SOUNDS.get_or_init(|| FlyerSounds {
        sight: gi_soundindex("flyer/flysght1.wav"),
        idle: gi_soundindex("flyer/flysrch1.wav"),
        pain1: gi_soundindex("flyer/flypain1.wav"),
        pain2: gi_soundindex("flyer/flypain2.wav"),
        slash: gi_soundindex("flyer/flyatck2.wav"),
        sproing: gi_soundindex("flyer/flyatck1.wav"),
        die: gi_soundindex("flyer/flydeth1.wav"),
    });

    // Precache attack sound
    gi_soundindex("flyer/flyatck3.wav");

    self_ent.s.modelindex = gi_modelindex("models/monsters/flyer/tris.md2");
    self_ent.mins = [-16.0, -16.0, -24.0];
    self_ent.maxs = [16.0, 16.0, 32.0];
    self_ent.movetype = MoveType::Step;
    self_ent.solid = Solid::Bbox;

    self_ent.s.sound = gi_soundindex("flyer/flyidle1.wav");

    self_ent.health = 50;
    self_ent.mass = 50;

    self_ent.pain_fn = Some(crate::dispatch::PAIN_FLYER);
    self_ent.die_fn = Some(crate::dispatch::DIE_FLYER);

    self_ent.monsterinfo.stand_fn = Some(crate::dispatch::MSTAND_FLYER);
    self_ent.monsterinfo.walk_fn = Some(crate::dispatch::MWALK_FLYER);
    self_ent.monsterinfo.run_fn = Some(crate::dispatch::MRUN_FLYER);
    self_ent.monsterinfo.attack_fn = Some(crate::dispatch::MATTACK_FLYER);
    self_ent.monsterinfo.melee_fn = Some(crate::dispatch::MMELEE_FLYER);
    self_ent.monsterinfo.sight_fn = Some(crate::dispatch::MSIGHT_FLYER);
    self_ent.monsterinfo.idle_fn = Some(crate::dispatch::MIDLE_FLYER);

    gi_linkentity(self_ent);

    self_ent.monsterinfo.currentmove = Some(MOVE_STAND);
    self_ent.monsterinfo.scale = MODEL_SCALE;

    flymonster_start(self_ent);
}
