// m_flipper.rs — Flipper (barracuda) monster
// Converted from: myq2-original/game/m_flipper.c
// Frame definitions from: myq2-original/game/m_flipper.h

use crate::g_local::*;
use crate::game::*;
use crate::entity_adapters::{
    gi_sound, gi_soundindex, gi_modelindex, gi_linkentity,
    g_free_edict, throw_gib, throw_head, swimmonster_start,
    fire_hit,
};
use myq2_common::common::rand_i32;

// ============================================================
// Frame definitions (from m_flipper.h)
// This file generated by ModelGen - Do NOT Modify
// ============================================================

pub const FRAME_FLPBIT01: i32 = 0;
pub const FRAME_FLPBIT02: i32 = 1;
pub const FRAME_FLPBIT03: i32 = 2;
pub const FRAME_FLPBIT04: i32 = 3;
pub const FRAME_FLPBIT05: i32 = 4;
pub const FRAME_FLPBIT06: i32 = 5;
pub const FRAME_FLPBIT07: i32 = 6;
pub const FRAME_FLPBIT08: i32 = 7;
pub const FRAME_FLPBIT09: i32 = 8;
pub const FRAME_FLPBIT10: i32 = 9;
pub const FRAME_FLPBIT11: i32 = 10;
pub const FRAME_FLPBIT12: i32 = 11;
pub const FRAME_FLPBIT13: i32 = 12;
pub const FRAME_FLPBIT14: i32 = 13;
pub const FRAME_FLPBIT15: i32 = 14;
pub const FRAME_FLPBIT16: i32 = 15;
pub const FRAME_FLPBIT17: i32 = 16;
pub const FRAME_FLPBIT18: i32 = 17;
pub const FRAME_FLPBIT19: i32 = 18;
pub const FRAME_FLPBIT20: i32 = 19;
pub const FRAME_FLPTAL01: i32 = 20;
pub const FRAME_FLPTAL02: i32 = 21;
pub const FRAME_FLPTAL03: i32 = 22;
pub const FRAME_FLPTAL04: i32 = 23;
pub const FRAME_FLPTAL05: i32 = 24;
pub const FRAME_FLPTAL06: i32 = 25;
pub const FRAME_FLPTAL07: i32 = 26;
pub const FRAME_FLPTAL08: i32 = 27;
pub const FRAME_FLPTAL09: i32 = 28;
pub const FRAME_FLPTAL10: i32 = 29;
pub const FRAME_FLPTAL11: i32 = 30;
pub const FRAME_FLPTAL12: i32 = 31;
pub const FRAME_FLPTAL13: i32 = 32;
pub const FRAME_FLPTAL14: i32 = 33;
pub const FRAME_FLPTAL15: i32 = 34;
pub const FRAME_FLPTAL16: i32 = 35;
pub const FRAME_FLPTAL17: i32 = 36;
pub const FRAME_FLPTAL18: i32 = 37;
pub const FRAME_FLPTAL19: i32 = 38;
pub const FRAME_FLPTAL20: i32 = 39;
pub const FRAME_FLPTAL21: i32 = 40;
pub const FRAME_FLPHOR01: i32 = 41;
pub const FRAME_FLPHOR02: i32 = 42;
pub const FRAME_FLPHOR03: i32 = 43;
pub const FRAME_FLPHOR04: i32 = 44;
pub const FRAME_FLPHOR05: i32 = 45;
pub const FRAME_FLPHOR06: i32 = 46;
pub const FRAME_FLPHOR07: i32 = 47;
pub const FRAME_FLPHOR08: i32 = 48;
pub const FRAME_FLPHOR09: i32 = 49;
pub const FRAME_FLPHOR10: i32 = 50;
pub const FRAME_FLPHOR11: i32 = 51;
pub const FRAME_FLPHOR12: i32 = 52;
pub const FRAME_FLPHOR13: i32 = 53;
pub const FRAME_FLPHOR14: i32 = 54;
pub const FRAME_FLPHOR15: i32 = 55;
pub const FRAME_FLPHOR16: i32 = 56;
pub const FRAME_FLPHOR17: i32 = 57;
pub const FRAME_FLPHOR18: i32 = 58;
pub const FRAME_FLPHOR19: i32 = 59;
pub const FRAME_FLPHOR20: i32 = 60;
pub const FRAME_FLPHOR21: i32 = 61;
pub const FRAME_FLPHOR22: i32 = 62;
pub const FRAME_FLPHOR23: i32 = 63;
pub const FRAME_FLPHOR24: i32 = 64;
pub const FRAME_FLPVER01: i32 = 65;
pub const FRAME_FLPVER02: i32 = 66;
pub const FRAME_FLPVER03: i32 = 67;
pub const FRAME_FLPVER04: i32 = 68;
pub const FRAME_FLPVER05: i32 = 69;
pub const FRAME_FLPVER06: i32 = 70;
pub const FRAME_FLPVER07: i32 = 71;
pub const FRAME_FLPVER08: i32 = 72;
pub const FRAME_FLPVER09: i32 = 73;
pub const FRAME_FLPVER10: i32 = 74;
pub const FRAME_FLPVER11: i32 = 75;
pub const FRAME_FLPVER12: i32 = 76;
pub const FRAME_FLPVER13: i32 = 77;
pub const FRAME_FLPVER14: i32 = 78;
pub const FRAME_FLPVER15: i32 = 79;
pub const FRAME_FLPVER16: i32 = 80;
pub const FRAME_FLPVER17: i32 = 81;
pub const FRAME_FLPVER18: i32 = 82;
pub const FRAME_FLPVER19: i32 = 83;
pub const FRAME_FLPVER20: i32 = 84;
pub const FRAME_FLPVER21: i32 = 85;
pub const FRAME_FLPVER22: i32 = 86;
pub const FRAME_FLPVER23: i32 = 87;
pub const FRAME_FLPVER24: i32 = 88;
pub const FRAME_FLPVER25: i32 = 89;
pub const FRAME_FLPVER26: i32 = 90;
pub const FRAME_FLPVER27: i32 = 91;
pub const FRAME_FLPVER28: i32 = 92;
pub const FRAME_FLPVER29: i32 = 93;
pub const FRAME_FLPPN101: i32 = 94;
pub const FRAME_FLPPN102: i32 = 95;
pub const FRAME_FLPPN103: i32 = 96;
pub const FRAME_FLPPN104: i32 = 97;
pub const FRAME_FLPPN105: i32 = 98;
pub const FRAME_FLPPN201: i32 = 99;
pub const FRAME_FLPPN202: i32 = 100;
pub const FRAME_FLPPN203: i32 = 101;
pub const FRAME_FLPPN204: i32 = 102;
pub const FRAME_FLPPN205: i32 = 103;
pub const FRAME_FLPDTH01: i32 = 104;
pub const FRAME_FLPDTH02: i32 = 105;
pub const FRAME_FLPDTH03: i32 = 106;
pub const FRAME_FLPDTH04: i32 = 107;
pub const FRAME_FLPDTH05: i32 = 108;
pub const FRAME_FLPDTH06: i32 = 109;
pub const FRAME_FLPDTH07: i32 = 110;
pub const FRAME_FLPDTH08: i32 = 111;
pub const FRAME_FLPDTH09: i32 = 112;
pub const FRAME_FLPDTH10: i32 = 113;
pub const FRAME_FLPDTH11: i32 = 114;
pub const FRAME_FLPDTH12: i32 = 115;
pub const FRAME_FLPDTH13: i32 = 116;
pub const FRAME_FLPDTH14: i32 = 117;
pub const FRAME_FLPDTH15: i32 = 118;
pub const FRAME_FLPDTH16: i32 = 119;
pub const FRAME_FLPDTH17: i32 = 120;
pub const FRAME_FLPDTH18: i32 = 121;
pub const FRAME_FLPDTH19: i32 = 122;
pub const FRAME_FLPDTH20: i32 = 123;
pub const FRAME_FLPDTH21: i32 = 124;
pub const FRAME_FLPDTH22: i32 = 125;
pub const FRAME_FLPDTH23: i32 = 126;
pub const FRAME_FLPDTH24: i32 = 127;
pub const FRAME_FLPDTH25: i32 = 128;
pub const FRAME_FLPDTH26: i32 = 129;
pub const FRAME_FLPDTH27: i32 = 130;
pub const FRAME_FLPDTH28: i32 = 131;
pub const FRAME_FLPDTH29: i32 = 132;
pub const FRAME_FLPDTH30: i32 = 133;
pub const FRAME_FLPDTH31: i32 = 134;
pub const FRAME_FLPDTH32: i32 = 135;
pub const FRAME_FLPDTH33: i32 = 136;
pub const FRAME_FLPDTH34: i32 = 137;
pub const FRAME_FLPDTH35: i32 = 138;
pub const FRAME_FLPDTH36: i32 = 139;
pub const FRAME_FLPDTH37: i32 = 140;
pub const FRAME_FLPDTH38: i32 = 141;
pub const FRAME_FLPDTH39: i32 = 142;
pub const FRAME_FLPDTH40: i32 = 143;
pub const FRAME_FLPDTH41: i32 = 144;
pub const FRAME_FLPDTH42: i32 = 145;
pub const FRAME_FLPDTH43: i32 = 146;
pub const FRAME_FLPDTH44: i32 = 147;
pub const FRAME_FLPDTH45: i32 = 148;
pub const FRAME_FLPDTH46: i32 = 149;
pub const FRAME_FLPDTH47: i32 = 150;
pub const FRAME_FLPDTH48: i32 = 151;
pub const FRAME_FLPDTH49: i32 = 152;
pub const FRAME_FLPDTH50: i32 = 153;
pub const FRAME_FLPDTH51: i32 = 154;
pub const FRAME_FLPDTH52: i32 = 155;
pub const FRAME_FLPDTH53: i32 = 156;
pub const FRAME_FLPDTH54: i32 = 157;
pub const FRAME_FLPDTH55: i32 = 158;
pub const FRAME_FLPDTH56: i32 = 159;

pub const MODEL_SCALE: f32 = 1.000000;

// ============================================================
// Sound channel / attenuation constants (mirrors C defines)
// ============================================================

// CHAN_*, ATTN_* come from g_local::* re-export (myq2_common::q_shared)

// ============================================================

use crate::ai_wrappers::{ai_stand, ai_walk, ai_run, ai_charge, ai_move};

// ============================================================
// Sound indices (module-level state, replaces C statics)
// ============================================================

#[derive(Default)]
pub struct FlipperSounds {
    pub chomp: i32,
    pub attack: i32,
    pub pain1: i32,
    pub pain2: i32,
    pub death: i32,
    pub idle: i32,
    pub search: i32,
    pub sight: i32,
}

static SOUNDS: std::sync::OnceLock<FlipperSounds> = std::sync::OnceLock::new();


// ============================================================
// Move table indices (for monsterinfo.currentmove)
// ============================================================

pub const MOVE_STAND: usize = 0;
pub const MOVE_RUN_LOOP: usize = 1;
pub const MOVE_RUN_START: usize = 2;
pub const MOVE_WALK: usize = 3;
pub const MOVE_START_RUN: usize = 4;
pub const MOVE_PAIN1: usize = 5;
pub const MOVE_PAIN2: usize = 6;
pub const MOVE_ATTACK: usize = 7;
pub const MOVE_DEATH: usize = 8;

// ============================================================
// Constants
// ============================================================

const FLIPPER_RUN_SPEED: f32 = 24.0;

// ============================================================
// Stand animation
// ============================================================

static FLIPPER_FRAMES_STAND: [MFrame; 1] = [
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
];

pub static FLIPPER_MOVE_STAND: MMove = MMove {
    firstframe: FRAME_FLPHOR01,
    lastframe: FRAME_FLPHOR01,
    frames: &FLIPPER_FRAMES_STAND,
    endfunc: None,
};

pub fn flipper_stand(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_STAND);
}

// ============================================================
// Run animation
// ============================================================

static FLIPPER_FRAMES_RUN: [MFrame; 24] = [
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None }, // 6
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None }, // 10
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None }, // 20
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None },
    MFrame { ai_fn: ai_run, dist: FLIPPER_RUN_SPEED, think_fn: None }, // 29
];

pub static FLIPPER_MOVE_RUN_LOOP: MMove = MMove {
    firstframe: FRAME_FLPVER06,
    lastframe: FRAME_FLPVER29,
    frames: &FLIPPER_FRAMES_RUN,
    endfunc: None,
};

pub fn flipper_run_loop(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_RUN_LOOP);
}

static FLIPPER_FRAMES_RUN_START: [MFrame; 6] = [
    MFrame { ai_fn: ai_run, dist: 8.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 8.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 8.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 8.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 8.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 8.0, think_fn: None },
];

pub static FLIPPER_MOVE_RUN_START: MMove = MMove {
    firstframe: FRAME_FLPVER01,
    lastframe: FRAME_FLPVER06,
    frames: &FLIPPER_FRAMES_RUN_START,
    endfunc: Some(flipper_run_loop),
};

pub fn flipper_run(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_RUN_START);
}

// ============================================================
// Walk animation (Standard Swimming)
// ============================================================

static FLIPPER_FRAMES_WALK: [MFrame; 24] = [
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
];

pub static FLIPPER_MOVE_WALK: MMove = MMove {
    firstframe: FRAME_FLPHOR01,
    lastframe: FRAME_FLPHOR24,
    frames: &FLIPPER_FRAMES_WALK,
    endfunc: None,
};

pub fn flipper_walk(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_WALK);
}

// ============================================================
// Start run animation
// ============================================================

fn flipper_run_thinkfn(self_ent: &mut Edict, ctx: &mut GameContext) {
    flipper_run(self_ent, ctx);
}

static FLIPPER_FRAMES_START_RUN: [MFrame; 5] = [
    MFrame { ai_fn: ai_run, dist: 8.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 8.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 8.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 8.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 8.0, think_fn: Some(flipper_run_thinkfn) },
];

pub static FLIPPER_MOVE_START_RUN: MMove = MMove {
    firstframe: FRAME_FLPHOR01,
    lastframe: FRAME_FLPHOR05,
    frames: &FLIPPER_FRAMES_START_RUN,
    endfunc: None,
};

pub fn flipper_start_run(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_START_RUN);
}

// ============================================================
// Pain animations
// ============================================================

static FLIPPER_FRAMES_PAIN2: [MFrame; 5] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static FLIPPER_MOVE_PAIN2: MMove = MMove {
    firstframe: FRAME_FLPPN101,
    lastframe: FRAME_FLPPN105,
    frames: &FLIPPER_FRAMES_PAIN2,
    endfunc: Some(flipper_run),
};

static FLIPPER_FRAMES_PAIN1: [MFrame; 5] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static FLIPPER_MOVE_PAIN1: MMove = MMove {
    firstframe: FRAME_FLPPN201,
    lastframe: FRAME_FLPPN205,
    frames: &FLIPPER_FRAMES_PAIN1,
    endfunc: Some(flipper_run),
};

// ============================================================
// Attack animation
// ============================================================

fn flipper_bite(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let aim: [f32; 3] = [MELEE_DISTANCE, 0.0, 0.0];
    fire_hit(self_ent, &aim, 5, 0);
}

fn flipper_preattack(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let sound_chomp = SOUNDS.get().map_or(0, |s| s.chomp);
    gi_sound(self_ent, CHAN_WEAPON, sound_chomp, 1.0, ATTN_NORM, 0.0);
}

static FLIPPER_FRAMES_ATTACK: [MFrame; 20] = [
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(flipper_preattack) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(flipper_bite) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(flipper_bite) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
];

pub static FLIPPER_MOVE_ATTACK: MMove = MMove {
    firstframe: FRAME_FLPBIT01,
    lastframe: FRAME_FLPBIT20,
    frames: &FLIPPER_FRAMES_ATTACK,
    endfunc: Some(flipper_run),
};

pub fn flipper_melee(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_ATTACK);
}

// ============================================================
// Pain
// ============================================================

pub fn flipper_pain(self_ent: &mut Edict, _other_idx: usize, _kick: f32, _damage: i32, level: &LevelLocals, skill_value: f32) {
    if self_ent.health < (self_ent.max_health / 2) {
        self_ent.s.skinnum = 1;
    }

    if level.time < self_ent.pain_debounce_time {
        return;
    }

    self_ent.pain_debounce_time = level.time + 3.0;

    if skill_value == 3.0 {
        return; // no pain anims in nightmare
    }

    let n = (rand_i32() + 1) % 2;
    if n == 0 {
        let sound_pain1 = SOUNDS.get().map_or(0, |s| s.pain1);
        gi_sound(self_ent, CHAN_VOICE, sound_pain1, 1.0, ATTN_NORM, 0.0);
        self_ent.monsterinfo.currentmove = Some(MOVE_PAIN1);
    } else {
        let sound_pain2 = SOUNDS.get().map_or(0, |s| s.pain2);
        gi_sound(self_ent, CHAN_VOICE, sound_pain2, 1.0, ATTN_NORM, 0.0);
        self_ent.monsterinfo.currentmove = Some(MOVE_PAIN2);
    }
}

// ============================================================
// Death animation
// ============================================================

fn flipper_dead(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.mins = [-16.0, -16.0, -24.0];
    self_ent.maxs = [16.0, 16.0, -8.0];
    self_ent.movetype = MoveType::Toss;
    self_ent.svflags |= SVF_DEADMONSTER;
    self_ent.nextthink = 0.0;
    gi_linkentity(self_ent);
}

static FLIPPER_FRAMES_DEATH: [MFrame; 56] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static FLIPPER_MOVE_DEATH: MMove = MMove {
    firstframe: FRAME_FLPDTH01,
    lastframe: FRAME_FLPDTH56,
    frames: &FLIPPER_FRAMES_DEATH,
    endfunc: Some(flipper_dead),
};

// ============================================================
// Sight
// ============================================================

pub fn flipper_sight(self_ent: &mut Edict, _other: &mut Edict) {
    let sound_sight = SOUNDS.get().map_or(0, |s| s.sight);
    gi_sound(self_ent, CHAN_VOICE, sound_sight, 1.0, ATTN_NORM, 0.0);
}

// ============================================================
// Die
// ============================================================

pub fn flipper_die(self_ent: &mut Edict, _inflictor_idx: usize, _attacker_idx: usize, damage: i32, _point: [f32; 3]) {
    // check for gib
    if self_ent.health <= self_ent.gib_health {
        gi_sound(self_ent, CHAN_VOICE, gi_soundindex("misc/udeath.wav"), 1.0, ATTN_NORM, 0.0);
        for _ in 0..2 {
            throw_gib(self_ent, "models/objects/gibs/bone/tris.md2", damage, GIB_ORGANIC);
        }
        for _ in 0..2 {
            throw_gib(self_ent, "models/objects/gibs/sm_meat/tris.md2", damage, GIB_ORGANIC);
        }
        throw_head(self_ent, "models/objects/gibs/sm_meat/tris.md2", damage, GIB_ORGANIC);
        self_ent.deadflag = DEAD_DEAD;
        return;
    }

    if self_ent.deadflag == DEAD_DEAD {
        return;
    }

    // regular death
    let sound_death = SOUNDS.get().map_or(0, |s| s.death);
    gi_sound(self_ent, CHAN_VOICE, sound_death, 1.0, ATTN_NORM, 0.0);
    self_ent.deadflag = DEAD_DEAD;
    self_ent.takedamage = 1; // DAMAGE_YES
    self_ent.monsterinfo.currentmove = Some(MOVE_DEATH);
}

// ============================================================
// Spawn function
// ============================================================

/// QUAKED monster_flipper (1 .5 0) (-16 -16 -24) (16 16 32) Ambush Trigger_Spawn Sight
pub fn sp_monster_flipper(self_ent: &mut Edict, deathmatch_value: f32) {
    if deathmatch_value != 0.0 {
        g_free_edict(self_ent);
        return;
    }

    SOUNDS.get_or_init(|| FlipperSounds {
        pain1: gi_soundindex("flipper/flppain1.wav"),
        pain2: gi_soundindex("flipper/flppain2.wav"),
        death: gi_soundindex("flipper/flpdeth1.wav"),
        chomp: gi_soundindex("flipper/flpatck1.wav"),
        attack: gi_soundindex("flipper/flpatck2.wav"),
        idle: gi_soundindex("flipper/flpidle1.wav"),
        search: gi_soundindex("flipper/flpsrch1.wav"),
        sight: gi_soundindex("flipper/flpsght1.wav"),
    });

    self_ent.movetype = MoveType::Step;
    self_ent.solid = Solid::Bbox;
    self_ent.s.modelindex = gi_modelindex("models/monsters/flipper/tris.md2");
    self_ent.mins = [-16.0, -16.0, 0.0];
    self_ent.maxs = [16.0, 16.0, 32.0];

    self_ent.health = 50;
    self_ent.gib_health = -30;
    self_ent.mass = 100;

    self_ent.pain_fn = Some(crate::dispatch::PAIN_FLIPPER);
    self_ent.die_fn = Some(crate::dispatch::DIE_FLIPPER);

    self_ent.monsterinfo.stand_fn = Some(crate::dispatch::MSTAND_FLIPPER);
    self_ent.monsterinfo.walk_fn = Some(crate::dispatch::MWALK_FLIPPER);
    self_ent.monsterinfo.run_fn = Some(crate::dispatch::MRUN_FLIPPER);
    self_ent.monsterinfo.melee_fn = Some(crate::dispatch::MMELEE_FLIPPER);
    self_ent.monsterinfo.sight_fn = Some(crate::dispatch::MSIGHT_FLIPPER);

    gi_linkentity(self_ent);

    self_ent.monsterinfo.currentmove = Some(MOVE_STAND);
    self_ent.monsterinfo.scale = MODEL_SCALE;

    swimmonster_start(self_ent);
}
