// m_hover.rs — Hover monster
// Converted from: myq2-original/game/m_hover.c
// Frame definitions from: myq2-original/game/m_hover.h

use crate::g_local::*;
use crate::game::*;
use crate::entity_adapters::{
    gi_sound, gi_soundindex, gi_modelindex, gi_linkentity,
    g_free_edict, flymonster_start, throw_gib, throw_head,
    visible, monster_flash_offset, g_project_source,
    monster_fire_blaster,
};
use crate::game_import::skill_value;
use myq2_common::common::frand as random;

// ============================================================
// Frame definitions (from m_hover.h)
// This file generated by ModelGen - Do NOT Modify
// ============================================================

pub const FRAME_STAND01: i32 = 0;
pub const FRAME_STAND02: i32 = 1;
pub const FRAME_STAND03: i32 = 2;
pub const FRAME_STAND04: i32 = 3;
pub const FRAME_STAND05: i32 = 4;
pub const FRAME_STAND06: i32 = 5;
pub const FRAME_STAND07: i32 = 6;
pub const FRAME_STAND08: i32 = 7;
pub const FRAME_STAND09: i32 = 8;
pub const FRAME_STAND10: i32 = 9;
pub const FRAME_STAND11: i32 = 10;
pub const FRAME_STAND12: i32 = 11;
pub const FRAME_STAND13: i32 = 12;
pub const FRAME_STAND14: i32 = 13;
pub const FRAME_STAND15: i32 = 14;
pub const FRAME_STAND16: i32 = 15;
pub const FRAME_STAND17: i32 = 16;
pub const FRAME_STAND18: i32 = 17;
pub const FRAME_STAND19: i32 = 18;
pub const FRAME_STAND20: i32 = 19;
pub const FRAME_STAND21: i32 = 20;
pub const FRAME_STAND22: i32 = 21;
pub const FRAME_STAND23: i32 = 22;
pub const FRAME_STAND24: i32 = 23;
pub const FRAME_STAND25: i32 = 24;
pub const FRAME_STAND26: i32 = 25;
pub const FRAME_STAND27: i32 = 26;
pub const FRAME_STAND28: i32 = 27;
pub const FRAME_STAND29: i32 = 28;
pub const FRAME_STAND30: i32 = 29;
pub const FRAME_FORWRD01: i32 = 30;
pub const FRAME_FORWRD02: i32 = 31;
pub const FRAME_FORWRD03: i32 = 32;
pub const FRAME_FORWRD04: i32 = 33;
pub const FRAME_FORWRD05: i32 = 34;
pub const FRAME_FORWRD06: i32 = 35;
pub const FRAME_FORWRD07: i32 = 36;
pub const FRAME_FORWRD08: i32 = 37;
pub const FRAME_FORWRD09: i32 = 38;
pub const FRAME_FORWRD10: i32 = 39;
pub const FRAME_FORWRD11: i32 = 40;
pub const FRAME_FORWRD12: i32 = 41;
pub const FRAME_FORWRD13: i32 = 42;
pub const FRAME_FORWRD14: i32 = 43;
pub const FRAME_FORWRD15: i32 = 44;
pub const FRAME_FORWRD16: i32 = 45;
pub const FRAME_FORWRD17: i32 = 46;
pub const FRAME_FORWRD18: i32 = 47;
pub const FRAME_FORWRD19: i32 = 48;
pub const FRAME_FORWRD20: i32 = 49;
pub const FRAME_FORWRD21: i32 = 50;
pub const FRAME_FORWRD22: i32 = 51;
pub const FRAME_FORWRD23: i32 = 52;
pub const FRAME_FORWRD24: i32 = 53;
pub const FRAME_FORWRD25: i32 = 54;
pub const FRAME_FORWRD26: i32 = 55;
pub const FRAME_FORWRD27: i32 = 56;
pub const FRAME_FORWRD28: i32 = 57;
pub const FRAME_FORWRD29: i32 = 58;
pub const FRAME_FORWRD30: i32 = 59;
pub const FRAME_FORWRD31: i32 = 60;
pub const FRAME_FORWRD32: i32 = 61;
pub const FRAME_FORWRD33: i32 = 62;
pub const FRAME_FORWRD34: i32 = 63;
pub const FRAME_FORWRD35: i32 = 64;
pub const FRAME_STOP101: i32 = 65;
pub const FRAME_STOP102: i32 = 66;
pub const FRAME_STOP103: i32 = 67;
pub const FRAME_STOP104: i32 = 68;
pub const FRAME_STOP105: i32 = 69;
pub const FRAME_STOP106: i32 = 70;
pub const FRAME_STOP107: i32 = 71;
pub const FRAME_STOP108: i32 = 72;
pub const FRAME_STOP109: i32 = 73;
pub const FRAME_STOP201: i32 = 74;
pub const FRAME_STOP202: i32 = 75;
pub const FRAME_STOP203: i32 = 76;
pub const FRAME_STOP204: i32 = 77;
pub const FRAME_STOP205: i32 = 78;
pub const FRAME_STOP206: i32 = 79;
pub const FRAME_STOP207: i32 = 80;
pub const FRAME_STOP208: i32 = 81;
pub const FRAME_TAKEOF01: i32 = 82;
pub const FRAME_TAKEOF02: i32 = 83;
pub const FRAME_TAKEOF03: i32 = 84;
pub const FRAME_TAKEOF04: i32 = 85;
pub const FRAME_TAKEOF05: i32 = 86;
pub const FRAME_TAKEOF06: i32 = 87;
pub const FRAME_TAKEOF07: i32 = 88;
pub const FRAME_TAKEOF08: i32 = 89;
pub const FRAME_TAKEOF09: i32 = 90;
pub const FRAME_TAKEOF10: i32 = 91;
pub const FRAME_TAKEOF11: i32 = 92;
pub const FRAME_TAKEOF12: i32 = 93;
pub const FRAME_TAKEOF13: i32 = 94;
pub const FRAME_TAKEOF14: i32 = 95;
pub const FRAME_TAKEOF15: i32 = 96;
pub const FRAME_TAKEOF16: i32 = 97;
pub const FRAME_TAKEOF17: i32 = 98;
pub const FRAME_TAKEOF18: i32 = 99;
pub const FRAME_TAKEOF19: i32 = 100;
pub const FRAME_TAKEOF20: i32 = 101;
pub const FRAME_TAKEOF21: i32 = 102;
pub const FRAME_TAKEOF22: i32 = 103;
pub const FRAME_TAKEOF23: i32 = 104;
pub const FRAME_TAKEOF24: i32 = 105;
pub const FRAME_TAKEOF25: i32 = 106;
pub const FRAME_TAKEOF26: i32 = 107;
pub const FRAME_TAKEOF27: i32 = 108;
pub const FRAME_TAKEOF28: i32 = 109;
pub const FRAME_TAKEOF29: i32 = 110;
pub const FRAME_TAKEOF30: i32 = 111;
pub const FRAME_LAND01: i32 = 112;
pub const FRAME_PAIN101: i32 = 113;
pub const FRAME_PAIN102: i32 = 114;
pub const FRAME_PAIN103: i32 = 115;
pub const FRAME_PAIN104: i32 = 116;
pub const FRAME_PAIN105: i32 = 117;
pub const FRAME_PAIN106: i32 = 118;
pub const FRAME_PAIN107: i32 = 119;
pub const FRAME_PAIN108: i32 = 120;
pub const FRAME_PAIN109: i32 = 121;
pub const FRAME_PAIN110: i32 = 122;
pub const FRAME_PAIN111: i32 = 123;
pub const FRAME_PAIN112: i32 = 124;
pub const FRAME_PAIN113: i32 = 125;
pub const FRAME_PAIN114: i32 = 126;
pub const FRAME_PAIN115: i32 = 127;
pub const FRAME_PAIN116: i32 = 128;
pub const FRAME_PAIN117: i32 = 129;
pub const FRAME_PAIN118: i32 = 130;
pub const FRAME_PAIN119: i32 = 131;
pub const FRAME_PAIN120: i32 = 132;
pub const FRAME_PAIN121: i32 = 133;
pub const FRAME_PAIN122: i32 = 134;
pub const FRAME_PAIN123: i32 = 135;
pub const FRAME_PAIN124: i32 = 136;
pub const FRAME_PAIN125: i32 = 137;
pub const FRAME_PAIN126: i32 = 138;
pub const FRAME_PAIN127: i32 = 139;
pub const FRAME_PAIN128: i32 = 140;
pub const FRAME_PAIN201: i32 = 141;
pub const FRAME_PAIN202: i32 = 142;
pub const FRAME_PAIN203: i32 = 143;
pub const FRAME_PAIN204: i32 = 144;
pub const FRAME_PAIN205: i32 = 145;
pub const FRAME_PAIN206: i32 = 146;
pub const FRAME_PAIN207: i32 = 147;
pub const FRAME_PAIN208: i32 = 148;
pub const FRAME_PAIN209: i32 = 149;
pub const FRAME_PAIN210: i32 = 150;
pub const FRAME_PAIN211: i32 = 151;
pub const FRAME_PAIN212: i32 = 152;
pub const FRAME_PAIN301: i32 = 153;
pub const FRAME_PAIN302: i32 = 154;
pub const FRAME_PAIN303: i32 = 155;
pub const FRAME_PAIN304: i32 = 156;
pub const FRAME_PAIN305: i32 = 157;
pub const FRAME_PAIN306: i32 = 158;
pub const FRAME_PAIN307: i32 = 159;
pub const FRAME_PAIN308: i32 = 160;
pub const FRAME_PAIN309: i32 = 161;
pub const FRAME_DEATH101: i32 = 162;
pub const FRAME_DEATH102: i32 = 163;
pub const FRAME_DEATH103: i32 = 164;
pub const FRAME_DEATH104: i32 = 165;
pub const FRAME_DEATH105: i32 = 166;
pub const FRAME_DEATH106: i32 = 167;
pub const FRAME_DEATH107: i32 = 168;
pub const FRAME_DEATH108: i32 = 169;
pub const FRAME_DEATH109: i32 = 170;
pub const FRAME_DEATH110: i32 = 171;
pub const FRAME_DEATH111: i32 = 172;
pub const FRAME_BACKWD01: i32 = 173;
pub const FRAME_BACKWD02: i32 = 174;
pub const FRAME_BACKWD03: i32 = 175;
pub const FRAME_BACKWD04: i32 = 176;
pub const FRAME_BACKWD05: i32 = 177;
pub const FRAME_BACKWD06: i32 = 178;
pub const FRAME_BACKWD07: i32 = 179;
pub const FRAME_BACKWD08: i32 = 180;
pub const FRAME_BACKWD09: i32 = 181;
pub const FRAME_BACKWD10: i32 = 182;
pub const FRAME_BACKWD11: i32 = 183;
pub const FRAME_BACKWD12: i32 = 184;
pub const FRAME_BACKWD13: i32 = 185;
pub const FRAME_BACKWD14: i32 = 186;
pub const FRAME_BACKWD15: i32 = 187;
pub const FRAME_BACKWD16: i32 = 188;
pub const FRAME_BACKWD17: i32 = 189;
pub const FRAME_BACKWD18: i32 = 190;
pub const FRAME_BACKWD19: i32 = 191;
pub const FRAME_BACKWD20: i32 = 192;
pub const FRAME_BACKWD21: i32 = 193;
pub const FRAME_BACKWD22: i32 = 194;
pub const FRAME_BACKWD23: i32 = 195;
pub const FRAME_BACKWD24: i32 = 196;
pub const FRAME_ATTAK101: i32 = 197;
pub const FRAME_ATTAK102: i32 = 198;
pub const FRAME_ATTAK103: i32 = 199;
pub const FRAME_ATTAK104: i32 = 200;
pub const FRAME_ATTAK105: i32 = 201;
pub const FRAME_ATTAK106: i32 = 202;
pub const FRAME_ATTAK107: i32 = 203;
pub const FRAME_ATTAK108: i32 = 204;

pub const MODEL_SCALE: f32 = 1.000000;

// ============================================================

use crate::ai_wrappers::{ai_stand, ai_walk, ai_run, ai_charge, ai_move};

// ============================================================
// Sound indices (module-level state, replaces C statics)
// ============================================================

#[derive(Default)]
pub struct HoverSounds {
    pub pain1: i32,
    pub pain2: i32,
    pub death1: i32,
    pub death2: i32,
    pub sight: i32,
    pub search1: i32,
    pub search2: i32,
}

static SOUNDS: std::sync::OnceLock<HoverSounds> = std::sync::OnceLock::new();

// ============================================================
// Local helpers (not available in entity_adapters)
// ============================================================

use myq2_common::q_shared::angle_vectors;



use crate::game_import::deathmatch_value;

// ============================================================
// Constants
// ============================================================

// CHAN_*, ATTN_*, EF_* come from g_local::* re-export (myq2_common::q_shared)
// DAMAGE_YES, DAMAGE_NO come from g_local::*
const MZ2_HOVER_BLASTER_1: i32 = 85;

// ============================================================
// Move table indices (for monsterinfo.currentmove)
// ============================================================

pub const MOVE_STAND: usize = 0;
pub const MOVE_STOP1: usize = 1;
pub const MOVE_STOP2: usize = 2;
pub const MOVE_TAKEOFF: usize = 3;
pub const MOVE_PAIN3: usize = 4;
pub const MOVE_PAIN2: usize = 5;
pub const MOVE_PAIN1: usize = 6;
pub const MOVE_LAND: usize = 7;
pub const MOVE_FORWARD: usize = 8;
pub const MOVE_WALK: usize = 9;
pub const MOVE_RUN: usize = 10;
pub const MOVE_DEATH1: usize = 11;
pub const MOVE_BACKWARD: usize = 12;
pub const MOVE_START_ATTACK: usize = 13;
pub const MOVE_ATTACK1: usize = 14;
pub const MOVE_END_ATTACK: usize = 15;

// ============================================================
// Hover behavior functions
// ============================================================

pub fn hover_sight(self_ent: &mut Edict, _other: &mut Edict) {
    let sound_sight = SOUNDS.get().map_or(0, |s| s.sight);
    gi_sound(self_ent, CHAN_VOICE, sound_sight, 1.0, ATTN_NORM, 0.0);
}

pub fn hover_search(self_ent: &mut Edict) {
    if random() < 0.5 {
        let snd = SOUNDS.get().map_or(0, |s| s.search1);
        gi_sound(self_ent, CHAN_VOICE, snd, 1.0, ATTN_NORM, 0.0);
    } else {
        let snd = SOUNDS.get().map_or(0, |s| s.search2);
        gi_sound(self_ent, CHAN_VOICE, snd, 1.0, ATTN_NORM, 0.0);
    }
}

// ============================================================
// Stand animation
// ============================================================

static HOVER_FRAMES_STAND: [MFrame; 30] = [
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
];

pub static HOVER_MOVE_STAND: MMove = MMove {
    firstframe: FRAME_STAND01,
    lastframe: FRAME_STAND30,
    frames: &HOVER_FRAMES_STAND,
    endfunc: None,
};

// ============================================================
// Stop1 animation
// ============================================================

static HOVER_FRAMES_STOP1: [MFrame; 9] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static HOVER_MOVE_STOP1: MMove = MMove {
    firstframe: FRAME_STOP101,
    lastframe: FRAME_STOP109,
    frames: &HOVER_FRAMES_STOP1,
    endfunc: None,
};

// ============================================================
// Stop2 animation
// ============================================================

static HOVER_FRAMES_STOP2: [MFrame; 8] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static HOVER_MOVE_STOP2: MMove = MMove {
    firstframe: FRAME_STOP201,
    lastframe: FRAME_STOP208,
    frames: &HOVER_FRAMES_STOP2,
    endfunc: None,
};

// ============================================================
// Takeoff animation
// ============================================================

static HOVER_FRAMES_TAKEOFF: [MFrame; 30] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -6.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -9.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 3.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static HOVER_MOVE_TAKEOFF: MMove = MMove {
    firstframe: FRAME_TAKEOF01,
    lastframe: FRAME_TAKEOF30,
    frames: &HOVER_FRAMES_TAKEOFF,
    endfunc: None,
};

// ============================================================
// Pain3 animation
// ============================================================

static HOVER_FRAMES_PAIN3: [MFrame; 9] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static HOVER_MOVE_PAIN3: MMove = MMove {
    firstframe: FRAME_PAIN301,
    lastframe: FRAME_PAIN309,
    frames: &HOVER_FRAMES_PAIN3,
    endfunc: Some(hover_run),
};

// ============================================================
// Pain2 animation
// ============================================================

static HOVER_FRAMES_PAIN2: [MFrame; 12] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static HOVER_MOVE_PAIN2: MMove = MMove {
    firstframe: FRAME_PAIN201,
    lastframe: FRAME_PAIN212,
    frames: &HOVER_FRAMES_PAIN2,
    endfunc: Some(hover_run),
};

// ============================================================
// Pain1 animation
// ============================================================

static HOVER_FRAMES_PAIN1: [MFrame; 28] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -8.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -4.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -6.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -4.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -3.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 3.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 3.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 7.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 3.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 4.0, think_fn: None },
];

pub static HOVER_MOVE_PAIN1: MMove = MMove {
    firstframe: FRAME_PAIN101,
    lastframe: FRAME_PAIN128,
    frames: &HOVER_FRAMES_PAIN1,
    endfunc: Some(hover_run),
};

// ============================================================
// Land animation
// ============================================================

static HOVER_FRAMES_LAND: [MFrame; 1] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static HOVER_MOVE_LAND: MMove = MMove {
    firstframe: FRAME_LAND01,
    lastframe: FRAME_LAND01,
    frames: &HOVER_FRAMES_LAND,
    endfunc: None,
};

// ============================================================
// Forward animation
// ============================================================

static HOVER_FRAMES_FORWARD: [MFrame; 35] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static HOVER_MOVE_FORWARD: MMove = MMove {
    firstframe: FRAME_FORWRD01,
    lastframe: FRAME_FORWRD35,
    frames: &HOVER_FRAMES_FORWARD,
    endfunc: None,
};

// ============================================================
// Walk animation
// ============================================================

static HOVER_FRAMES_WALK: [MFrame; 35] = [
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 4.0, think_fn: None },
];

pub static HOVER_MOVE_WALK: MMove = MMove {
    firstframe: FRAME_FORWRD01,
    lastframe: FRAME_FORWRD35,
    frames: &HOVER_FRAMES_WALK,
    endfunc: None,
};

// ============================================================
// Run animation
// ============================================================

static HOVER_FRAMES_RUN: [MFrame; 35] = [
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
];

pub static HOVER_MOVE_RUN: MMove = MMove {
    firstframe: FRAME_FORWRD01,
    lastframe: FRAME_FORWRD35,
    frames: &HOVER_FRAMES_RUN,
    endfunc: None,
};

// ============================================================
// Death1 animation
// ============================================================

static HOVER_FRAMES_DEATH1: [MFrame; 11] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: -10.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 3.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 4.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 7.0, think_fn: None },
];

pub static HOVER_MOVE_DEATH1: MMove = MMove {
    firstframe: FRAME_DEATH101,
    lastframe: FRAME_DEATH111,
    frames: &HOVER_FRAMES_DEATH1,
    endfunc: Some(hover_dead),
};

// ============================================================
// Backward animation
// ============================================================

static HOVER_FRAMES_BACKWARD: [MFrame; 24] = [
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: None },
];

pub static HOVER_MOVE_BACKWARD: MMove = MMove {
    firstframe: FRAME_BACKWD01,
    lastframe: FRAME_BACKWD24,
    frames: &HOVER_FRAMES_BACKWARD,
    endfunc: None,
};

// ============================================================
// Start attack animation
// ============================================================

static HOVER_FRAMES_START_ATTACK: [MFrame; 3] = [
    MFrame { ai_fn: ai_charge, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 1.0, think_fn: None },
];

pub static HOVER_MOVE_START_ATTACK: MMove = MMove {
    firstframe: FRAME_ATTAK101,
    lastframe: FRAME_ATTAK103,
    frames: &HOVER_FRAMES_START_ATTACK,
    endfunc: Some(hover_attack),
};

// ============================================================
// Attack1 animation
// ============================================================

static HOVER_FRAMES_ATTACK1: [MFrame; 3] = [
    MFrame { ai_fn: ai_charge, dist: -10.0, think_fn: Some(hover_fire_blaster) },
    MFrame { ai_fn: ai_charge, dist: -10.0, think_fn: Some(hover_fire_blaster) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(hover_reattack) },
];

pub static HOVER_MOVE_ATTACK1: MMove = MMove {
    firstframe: FRAME_ATTAK104,
    lastframe: FRAME_ATTAK106,
    frames: &HOVER_FRAMES_ATTACK1,
    endfunc: None,
};

// ============================================================
// End attack animation
// ============================================================

static HOVER_FRAMES_END_ATTACK: [MFrame; 2] = [
    MFrame { ai_fn: ai_charge, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 1.0, think_fn: None },
];

pub static HOVER_MOVE_END_ATTACK: MMove = MMove {
    firstframe: FRAME_ATTAK107,
    lastframe: FRAME_ATTAK108,
    frames: &HOVER_FRAMES_END_ATTACK,
    endfunc: Some(hover_run),
};

// ============================================================
// Behavior functions
// ============================================================

fn hover_reattack(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let enemy_idx = self_ent.enemy;
    if enemy_idx > 0 && (enemy_idx as usize) < _ctx.edicts.len() {
        let enemy = &_ctx.edicts[enemy_idx as usize];
        if enemy.health > 0 && visible(self_ent, enemy) && random() <= 0.6 {
            self_ent.monsterinfo.currentmove = Some(MOVE_ATTACK1);
            return;
        }
    }
    self_ent.monsterinfo.currentmove = Some(MOVE_END_ATTACK);
}

fn hover_fire_blaster(self_ent: &mut Edict, ctx: &mut GameContext) {
    let mut start = [0.0_f32; 3];
    let mut forward = [0.0_f32; 3];
    let mut right = [0.0_f32; 3];
    let mut end = [0.0_f32; 3];
    let mut dir = [0.0_f32; 3];

    let effect = if self_ent.s.frame == FRAME_ATTAK104 {
        EF_HYPERBLASTER
    } else {
        0
    };

    angle_vectors(&self_ent.s.angles, Some(&mut forward), Some(&mut right), None);

    let offset = monster_flash_offset(MZ2_HOVER_BLASTER_1);
    g_project_source(&self_ent.s.origin, &offset, &forward, &right, &mut start);

    // VectorCopy(self->enemy->s.origin, end); end[2] += self->enemy->viewheight
    let enemy_idx = self_ent.enemy;
    if enemy_idx >= 0 {
        let enemy = &ctx.edicts[enemy_idx as usize];
        end = enemy.s.origin;
        end[2] += enemy.viewheight as f32;
    }

    // VectorSubtract(end, start, dir);
    dir[0] = end[0] - start[0];
    dir[1] = end[1] - start[1];
    dir[2] = end[2] - start[2];

    monster_fire_blaster(self_ent, start, dir, 1, 1000, MZ2_HOVER_BLASTER_1, effect as i32);
}

pub fn hover_stand(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_STAND);
}

pub fn hover_run(self_ent: &mut Edict, _ctx: &mut GameContext) {
    if self_ent.monsterinfo.aiflags.intersects(AI_STAND_GROUND) {
        self_ent.monsterinfo.currentmove = Some(MOVE_STAND);
    } else {
        self_ent.monsterinfo.currentmove = Some(MOVE_RUN);
    }
}

pub fn hover_walk(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_WALK);
}

pub fn hover_start_attack(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_START_ATTACK);
}

pub fn hover_attack(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_ATTACK1);
}

pub fn hover_pain(self_ent: &mut Edict, _other: &mut Edict, _kick: f32, damage: i32, ctx: &mut GameContext) {
    if self_ent.health < (self_ent.max_health / 2) {
        self_ent.s.skinnum = 1;
    }

    let level_time = ctx.level.time;

    if level_time < self_ent.pain_debounce_time {
        return;
    }

    self_ent.pain_debounce_time = level_time + 3.0;

    if skill_value() == 3.0 {
        return; // no pain anims in nightmare
    }

    if damage <= 25 {
        if random() < 0.5 {
            let snd = SOUNDS.get().map_or(0, |s| s.pain1);
            gi_sound(self_ent, CHAN_VOICE, snd, 1.0, ATTN_NORM, 0.0);
            self_ent.monsterinfo.currentmove = Some(MOVE_PAIN3);
        } else {
            let snd = SOUNDS.get().map_or(0, |s| s.pain2);
            gi_sound(self_ent, CHAN_VOICE, snd, 1.0, ATTN_NORM, 0.0);
            self_ent.monsterinfo.currentmove = Some(MOVE_PAIN2);
        }
    } else {
        let snd = SOUNDS.get().map_or(0, |s| s.pain1);
        gi_sound(self_ent, CHAN_VOICE, snd, 1.0, ATTN_NORM, 0.0);
        self_ent.monsterinfo.currentmove = Some(MOVE_PAIN1);
    }
}

pub fn hover_deadthink(self_ent: &mut Edict, ctx: &mut GameContext) {
    let level_time = ctx.level.time;

    if self_ent.groundentity < 0 && level_time < self_ent.timestamp {
        self_ent.nextthink = level_time + FRAMETIME;
        return;
    }
    let self_idx = self_ent.s.number as usize;
    crate::g_local::with_global_game_ctx(|ctx| {
        crate::g_misc::become_explosion1(ctx, self_idx);
    });
}

pub fn hover_dead(self_ent: &mut Edict, ctx: &mut GameContext) {
    self_ent.mins = [-16.0, -16.0, -24.0];
    self_ent.maxs = [16.0, 16.0, -8.0];
    self_ent.movetype = MoveType::Toss;
    self_ent.think_fn = Some(crate::dispatch::THINK_HOVER_DEADTHINK);
    let level_time = ctx.level.time;
    self_ent.nextthink = level_time + FRAMETIME;
    self_ent.timestamp = level_time + 15.0;
    gi_linkentity(self_ent);
}

pub fn hover_die(self_ent: &mut Edict, _inflictor: &mut Edict, _attacker: &mut Edict, damage: i32, _point: [f32; 3], _ctx: &mut GameContext) {
    // check for gib
    if self_ent.health <= self_ent.gib_health {
        gi_sound(self_ent, CHAN_VOICE, gi_soundindex("misc/udeath.wav"), 1.0, ATTN_NORM, 0.0);
        for _n in 0..2 {
            throw_gib(self_ent, "models/objects/gibs/bone/tris.md2", damage, GIB_ORGANIC);
        }
        for _n in 0..2 {
            throw_gib(self_ent, "models/objects/gibs/sm_meat/tris.md2", damage, GIB_ORGANIC);
        }
        throw_head(self_ent, "models/objects/gibs/sm_meat/tris.md2", damage, GIB_ORGANIC);
        self_ent.deadflag = DEAD_DEAD;
        return;
    }

    if self_ent.deadflag == DEAD_DEAD {
        return;
    }

    // regular death
    if random() < 0.5 {
        let snd = SOUNDS.get().map_or(0, |s| s.death1);
        gi_sound(self_ent, CHAN_VOICE, snd, 1.0, ATTN_NORM, 0.0);
    } else {
        let snd = SOUNDS.get().map_or(0, |s| s.death2);
        gi_sound(self_ent, CHAN_VOICE, snd, 1.0, ATTN_NORM, 0.0);
    }
    self_ent.deadflag = DEAD_DEAD;
    self_ent.takedamage = DAMAGE_YES;
    self_ent.monsterinfo.currentmove = Some(MOVE_DEATH1);
}

// ============================================================
// Spawn function
// ============================================================

/// QUAKED monster_hover (1 .5 0) (-16 -16 -24) (16 16 32) Ambush Trigger_Spawn Sight
pub fn sp_monster_hover(self_ent: &mut Edict, _ctx: &mut GameContext) {
    if deathmatch_value() != 0.0 {
        g_free_edict(self_ent);
        return;
    }

    SOUNDS.get_or_init(|| HoverSounds {
        pain1: gi_soundindex("hover/hovpain1.wav"),
        pain2: gi_soundindex("hover/hovpain2.wav"),
        death1: gi_soundindex("hover/hovdeth1.wav"),
        death2: gi_soundindex("hover/hovdeth2.wav"),
        sight: gi_soundindex("hover/hovsght1.wav"),
        search1: gi_soundindex("hover/hovsrch1.wav"),
        search2: gi_soundindex("hover/hovsrch2.wav"),
    });

    gi_soundindex("hover/hovatck1.wav");

    self_ent.s.sound = gi_soundindex("hover/hovidle1.wav");

    self_ent.movetype = MoveType::Step;
    self_ent.solid = Solid::Bbox;
    self_ent.s.modelindex = gi_modelindex("models/monsters/hover/tris.md2");
    self_ent.mins = [-24.0, -24.0, -24.0];
    self_ent.maxs = [24.0, 24.0, 32.0];

    self_ent.health = 240;
    self_ent.gib_health = -100;
    self_ent.mass = 150;

    self_ent.pain_fn = Some(crate::dispatch::PAIN_HOVER);
    self_ent.die_fn = Some(crate::dispatch::DIE_HOVER);

    self_ent.monsterinfo.stand_fn = Some(crate::dispatch::MSTAND_HOVER);
    self_ent.monsterinfo.walk_fn = Some(crate::dispatch::MWALK_HOVER);
    self_ent.monsterinfo.run_fn = Some(crate::dispatch::MRUN_HOVER);
    self_ent.monsterinfo.attack_fn = Some(crate::dispatch::MATTACK_HOVER);
    self_ent.monsterinfo.sight_fn = Some(crate::dispatch::MSIGHT_HOVER);
    self_ent.monsterinfo.search_fn = Some(crate::dispatch::MSEARCH_HOVER);

    gi_linkentity(self_ent);

    self_ent.monsterinfo.currentmove = Some(MOVE_STAND);
    self_ent.monsterinfo.scale = MODEL_SCALE;

    flymonster_start(self_ent);
}
