// m_soldier.rs — Soldier monster (light, normal, and SS variants)
// Converted from: myq2-original/game/m_soldier.c
// Frame definitions from: myq2-original/game/m_soldier.h

use crate::g_local::*;
use crate::game::*;
use crate::entity_adapters::{gi_sound, gi_soundindex, gi_modelindex, gi_linkentity, walkmonster_start};
use myq2_common::common::{frand as random, crand as crandom};

// ============================================================
// Frame definitions (from m_soldier.h)
// This file generated by ModelGen - Do NOT Modify
// ============================================================

pub const FRAME_ATTAK101: i32 = 0;
pub const FRAME_ATTAK102: i32 = 1;
pub const FRAME_ATTAK103: i32 = 2;
pub const FRAME_ATTAK104: i32 = 3;
pub const FRAME_ATTAK105: i32 = 4;
pub const FRAME_ATTAK106: i32 = 5;
pub const FRAME_ATTAK107: i32 = 6;
pub const FRAME_ATTAK108: i32 = 7;
pub const FRAME_ATTAK109: i32 = 8;
pub const FRAME_ATTAK110: i32 = 9;
pub const FRAME_ATTAK111: i32 = 10;
pub const FRAME_ATTAK112: i32 = 11;
pub const FRAME_ATTAK201: i32 = 12;
pub const FRAME_ATTAK202: i32 = 13;
pub const FRAME_ATTAK203: i32 = 14;
pub const FRAME_ATTAK204: i32 = 15;
pub const FRAME_ATTAK205: i32 = 16;
pub const FRAME_ATTAK206: i32 = 17;
pub const FRAME_ATTAK207: i32 = 18;
pub const FRAME_ATTAK208: i32 = 19;
pub const FRAME_ATTAK209: i32 = 20;
pub const FRAME_ATTAK210: i32 = 21;
pub const FRAME_ATTAK211: i32 = 22;
pub const FRAME_ATTAK212: i32 = 23;
pub const FRAME_ATTAK213: i32 = 24;
pub const FRAME_ATTAK214: i32 = 25;
pub const FRAME_ATTAK215: i32 = 26;
pub const FRAME_ATTAK216: i32 = 27;
pub const FRAME_ATTAK217: i32 = 28;
pub const FRAME_ATTAK218: i32 = 29;
pub const FRAME_ATTAK301: i32 = 30;
pub const FRAME_ATTAK302: i32 = 31;
pub const FRAME_ATTAK303: i32 = 32;
pub const FRAME_ATTAK304: i32 = 33;
pub const FRAME_ATTAK305: i32 = 34;
pub const FRAME_ATTAK306: i32 = 35;
pub const FRAME_ATTAK307: i32 = 36;
pub const FRAME_ATTAK308: i32 = 37;
pub const FRAME_ATTAK309: i32 = 38;
pub const FRAME_ATTAK401: i32 = 39;
pub const FRAME_ATTAK402: i32 = 40;
pub const FRAME_ATTAK403: i32 = 41;
pub const FRAME_ATTAK404: i32 = 42;
pub const FRAME_ATTAK405: i32 = 43;
pub const FRAME_ATTAK406: i32 = 44;
pub const FRAME_DUCK01: i32 = 45;
pub const FRAME_DUCK02: i32 = 46;
pub const FRAME_DUCK03: i32 = 47;
pub const FRAME_DUCK04: i32 = 48;
pub const FRAME_DUCK05: i32 = 49;
pub const FRAME_PAIN101: i32 = 50;
pub const FRAME_PAIN102: i32 = 51;
pub const FRAME_PAIN103: i32 = 52;
pub const FRAME_PAIN104: i32 = 53;
pub const FRAME_PAIN105: i32 = 54;
pub const FRAME_PAIN201: i32 = 55;
pub const FRAME_PAIN202: i32 = 56;
pub const FRAME_PAIN203: i32 = 57;
pub const FRAME_PAIN204: i32 = 58;
pub const FRAME_PAIN205: i32 = 59;
pub const FRAME_PAIN206: i32 = 60;
pub const FRAME_PAIN207: i32 = 61;
pub const FRAME_PAIN301: i32 = 62;
pub const FRAME_PAIN302: i32 = 63;
pub const FRAME_PAIN303: i32 = 64;
pub const FRAME_PAIN304: i32 = 65;
pub const FRAME_PAIN305: i32 = 66;
pub const FRAME_PAIN306: i32 = 67;
pub const FRAME_PAIN307: i32 = 68;
pub const FRAME_PAIN308: i32 = 69;
pub const FRAME_PAIN309: i32 = 70;
pub const FRAME_PAIN310: i32 = 71;
pub const FRAME_PAIN311: i32 = 72;
pub const FRAME_PAIN312: i32 = 73;
pub const FRAME_PAIN313: i32 = 74;
pub const FRAME_PAIN314: i32 = 75;
pub const FRAME_PAIN315: i32 = 76;
pub const FRAME_PAIN316: i32 = 77;
pub const FRAME_PAIN317: i32 = 78;
pub const FRAME_PAIN318: i32 = 79;
pub const FRAME_PAIN401: i32 = 80;
pub const FRAME_PAIN402: i32 = 81;
pub const FRAME_PAIN403: i32 = 82;
pub const FRAME_PAIN404: i32 = 83;
pub const FRAME_PAIN405: i32 = 84;
pub const FRAME_PAIN406: i32 = 85;
pub const FRAME_PAIN407: i32 = 86;
pub const FRAME_PAIN408: i32 = 87;
pub const FRAME_PAIN409: i32 = 88;
pub const FRAME_PAIN410: i32 = 89;
pub const FRAME_PAIN411: i32 = 90;
pub const FRAME_PAIN412: i32 = 91;
pub const FRAME_PAIN413: i32 = 92;
pub const FRAME_PAIN414: i32 = 93;
pub const FRAME_PAIN415: i32 = 94;
pub const FRAME_PAIN416: i32 = 95;
pub const FRAME_PAIN417: i32 = 96;
pub const FRAME_RUN01: i32 = 97;
pub const FRAME_RUN02: i32 = 98;
pub const FRAME_RUN03: i32 = 99;
pub const FRAME_RUN04: i32 = 100;
pub const FRAME_RUN05: i32 = 101;
pub const FRAME_RUN06: i32 = 102;
pub const FRAME_RUN07: i32 = 103;
pub const FRAME_RUN08: i32 = 104;
pub const FRAME_RUN09: i32 = 105;
pub const FRAME_RUN10: i32 = 106;
pub const FRAME_RUN11: i32 = 107;
pub const FRAME_RUN12: i32 = 108;
pub const FRAME_RUNS01: i32 = 109;
pub const FRAME_RUNS02: i32 = 110;
pub const FRAME_RUNS03: i32 = 111;
pub const FRAME_RUNS04: i32 = 112;
pub const FRAME_RUNS05: i32 = 113;
pub const FRAME_RUNS06: i32 = 114;
pub const FRAME_RUNS07: i32 = 115;
pub const FRAME_RUNS08: i32 = 116;
pub const FRAME_RUNS09: i32 = 117;
pub const FRAME_RUNS10: i32 = 118;
pub const FRAME_RUNS11: i32 = 119;
pub const FRAME_RUNS12: i32 = 120;
pub const FRAME_RUNS13: i32 = 121;
pub const FRAME_RUNS14: i32 = 122;
pub const FRAME_RUNS15: i32 = 123;
pub const FRAME_RUNS16: i32 = 124;
pub const FRAME_RUNS17: i32 = 125;
pub const FRAME_RUNS18: i32 = 126;
pub const FRAME_RUNT01: i32 = 127;
pub const FRAME_RUNT02: i32 = 128;
pub const FRAME_RUNT03: i32 = 129;
pub const FRAME_RUNT04: i32 = 130;
pub const FRAME_RUNT05: i32 = 131;
pub const FRAME_RUNT06: i32 = 132;
pub const FRAME_RUNT07: i32 = 133;
pub const FRAME_RUNT08: i32 = 134;
pub const FRAME_RUNT09: i32 = 135;
pub const FRAME_RUNT10: i32 = 136;
pub const FRAME_RUNT11: i32 = 137;
pub const FRAME_RUNT12: i32 = 138;
pub const FRAME_RUNT13: i32 = 139;
pub const FRAME_RUNT14: i32 = 140;
pub const FRAME_RUNT15: i32 = 141;
pub const FRAME_RUNT16: i32 = 142;
pub const FRAME_RUNT17: i32 = 143;
pub const FRAME_RUNT18: i32 = 144;
pub const FRAME_RUNT19: i32 = 145;
pub const FRAME_STAND101: i32 = 146;
pub const FRAME_STAND102: i32 = 147;
pub const FRAME_STAND103: i32 = 148;
pub const FRAME_STAND104: i32 = 149;
pub const FRAME_STAND105: i32 = 150;
pub const FRAME_STAND106: i32 = 151;
pub const FRAME_STAND107: i32 = 152;
pub const FRAME_STAND108: i32 = 153;
pub const FRAME_STAND109: i32 = 154;
pub const FRAME_STAND110: i32 = 155;
pub const FRAME_STAND111: i32 = 156;
pub const FRAME_STAND112: i32 = 157;
pub const FRAME_STAND113: i32 = 158;
pub const FRAME_STAND114: i32 = 159;
pub const FRAME_STAND115: i32 = 160;
pub const FRAME_STAND116: i32 = 161;
pub const FRAME_STAND117: i32 = 162;
pub const FRAME_STAND118: i32 = 163;
pub const FRAME_STAND119: i32 = 164;
pub const FRAME_STAND120: i32 = 165;
pub const FRAME_STAND121: i32 = 166;
pub const FRAME_STAND122: i32 = 167;
pub const FRAME_STAND123: i32 = 168;
pub const FRAME_STAND124: i32 = 169;
pub const FRAME_STAND125: i32 = 170;
pub const FRAME_STAND126: i32 = 171;
pub const FRAME_STAND127: i32 = 172;
pub const FRAME_STAND128: i32 = 173;
pub const FRAME_STAND129: i32 = 174;
pub const FRAME_STAND130: i32 = 175;
pub const FRAME_STAND301: i32 = 176;
pub const FRAME_STAND302: i32 = 177;
pub const FRAME_STAND303: i32 = 178;
pub const FRAME_STAND304: i32 = 179;
pub const FRAME_STAND305: i32 = 180;
pub const FRAME_STAND306: i32 = 181;
pub const FRAME_STAND307: i32 = 182;
pub const FRAME_STAND308: i32 = 183;
pub const FRAME_STAND309: i32 = 184;
pub const FRAME_STAND310: i32 = 185;
pub const FRAME_STAND311: i32 = 186;
pub const FRAME_STAND312: i32 = 187;
pub const FRAME_STAND313: i32 = 188;
pub const FRAME_STAND314: i32 = 189;
pub const FRAME_STAND315: i32 = 190;
pub const FRAME_STAND316: i32 = 191;
pub const FRAME_STAND317: i32 = 192;
pub const FRAME_STAND318: i32 = 193;
pub const FRAME_STAND319: i32 = 194;
pub const FRAME_STAND320: i32 = 195;
pub const FRAME_STAND321: i32 = 196;
pub const FRAME_STAND322: i32 = 197;
pub const FRAME_STAND323: i32 = 198;
pub const FRAME_STAND324: i32 = 199;
pub const FRAME_STAND325: i32 = 200;
pub const FRAME_STAND326: i32 = 201;
pub const FRAME_STAND327: i32 = 202;
pub const FRAME_STAND328: i32 = 203;
pub const FRAME_STAND329: i32 = 204;
pub const FRAME_STAND330: i32 = 205;
pub const FRAME_STAND331: i32 = 206;
pub const FRAME_STAND332: i32 = 207;
pub const FRAME_STAND333: i32 = 208;
pub const FRAME_STAND334: i32 = 209;
pub const FRAME_STAND335: i32 = 210;
pub const FRAME_STAND336: i32 = 211;
pub const FRAME_STAND337: i32 = 212;
pub const FRAME_STAND338: i32 = 213;
pub const FRAME_STAND339: i32 = 214;
pub const FRAME_WALK101: i32 = 215;
pub const FRAME_WALK102: i32 = 216;
pub const FRAME_WALK103: i32 = 217;
pub const FRAME_WALK104: i32 = 218;
pub const FRAME_WALK105: i32 = 219;
pub const FRAME_WALK106: i32 = 220;
pub const FRAME_WALK107: i32 = 221;
pub const FRAME_WALK108: i32 = 222;
pub const FRAME_WALK109: i32 = 223;
pub const FRAME_WALK110: i32 = 224;
pub const FRAME_WALK111: i32 = 225;
pub const FRAME_WALK112: i32 = 226;
pub const FRAME_WALK113: i32 = 227;
pub const FRAME_WALK114: i32 = 228;
pub const FRAME_WALK115: i32 = 229;
pub const FRAME_WALK116: i32 = 230;
pub const FRAME_WALK117: i32 = 231;
pub const FRAME_WALK118: i32 = 232;
pub const FRAME_WALK119: i32 = 233;
pub const FRAME_WALK120: i32 = 234;
pub const FRAME_WALK121: i32 = 235;
pub const FRAME_WALK122: i32 = 236;
pub const FRAME_WALK123: i32 = 237;
pub const FRAME_WALK124: i32 = 238;
pub const FRAME_WALK125: i32 = 239;
pub const FRAME_WALK126: i32 = 240;
pub const FRAME_WALK127: i32 = 241;
pub const FRAME_WALK128: i32 = 242;
pub const FRAME_WALK129: i32 = 243;
pub const FRAME_WALK130: i32 = 244;
pub const FRAME_WALK131: i32 = 245;
pub const FRAME_WALK132: i32 = 246;
pub const FRAME_WALK133: i32 = 247;
pub const FRAME_WALK201: i32 = 248;
pub const FRAME_WALK202: i32 = 249;
pub const FRAME_WALK203: i32 = 250;
pub const FRAME_WALK204: i32 = 251;
pub const FRAME_WALK205: i32 = 252;
pub const FRAME_WALK206: i32 = 253;
pub const FRAME_WALK207: i32 = 254;
pub const FRAME_WALK208: i32 = 255;
pub const FRAME_WALK209: i32 = 256;
pub const FRAME_WALK210: i32 = 257;
pub const FRAME_WALK211: i32 = 258;
pub const FRAME_WALK212: i32 = 259;
pub const FRAME_WALK213: i32 = 260;
pub const FRAME_WALK214: i32 = 261;
pub const FRAME_WALK215: i32 = 262;
pub const FRAME_WALK216: i32 = 263;
pub const FRAME_WALK217: i32 = 264;
pub const FRAME_WALK218: i32 = 265;
pub const FRAME_WALK219: i32 = 266;
pub const FRAME_WALK220: i32 = 267;
pub const FRAME_WALK221: i32 = 268;
pub const FRAME_WALK222: i32 = 269;
pub const FRAME_WALK223: i32 = 270;
pub const FRAME_WALK224: i32 = 271;
pub const FRAME_DEATH101: i32 = 272;
pub const FRAME_DEATH102: i32 = 273;
pub const FRAME_DEATH103: i32 = 274;
pub const FRAME_DEATH104: i32 = 275;
pub const FRAME_DEATH105: i32 = 276;
pub const FRAME_DEATH106: i32 = 277;
pub const FRAME_DEATH107: i32 = 278;
pub const FRAME_DEATH108: i32 = 279;
pub const FRAME_DEATH109: i32 = 280;
pub const FRAME_DEATH110: i32 = 281;
pub const FRAME_DEATH111: i32 = 282;
pub const FRAME_DEATH112: i32 = 283;
pub const FRAME_DEATH113: i32 = 284;
pub const FRAME_DEATH114: i32 = 285;
pub const FRAME_DEATH115: i32 = 286;
pub const FRAME_DEATH116: i32 = 287;
pub const FRAME_DEATH117: i32 = 288;
pub const FRAME_DEATH118: i32 = 289;
pub const FRAME_DEATH119: i32 = 290;
pub const FRAME_DEATH120: i32 = 291;
pub const FRAME_DEATH121: i32 = 292;
pub const FRAME_DEATH122: i32 = 293;
pub const FRAME_DEATH123: i32 = 294;
pub const FRAME_DEATH124: i32 = 295;
pub const FRAME_DEATH125: i32 = 296;
pub const FRAME_DEATH126: i32 = 297;
pub const FRAME_DEATH127: i32 = 298;
pub const FRAME_DEATH128: i32 = 299;
pub const FRAME_DEATH129: i32 = 300;
pub const FRAME_DEATH130: i32 = 301;
pub const FRAME_DEATH131: i32 = 302;
pub const FRAME_DEATH132: i32 = 303;
pub const FRAME_DEATH133: i32 = 304;
pub const FRAME_DEATH134: i32 = 305;
pub const FRAME_DEATH135: i32 = 306;
pub const FRAME_DEATH136: i32 = 307;
pub const FRAME_DEATH201: i32 = 308;
pub const FRAME_DEATH202: i32 = 309;
pub const FRAME_DEATH203: i32 = 310;
pub const FRAME_DEATH204: i32 = 311;
pub const FRAME_DEATH205: i32 = 312;
pub const FRAME_DEATH206: i32 = 313;
pub const FRAME_DEATH207: i32 = 314;
pub const FRAME_DEATH208: i32 = 315;
pub const FRAME_DEATH209: i32 = 316;
pub const FRAME_DEATH210: i32 = 317;
pub const FRAME_DEATH211: i32 = 318;
pub const FRAME_DEATH212: i32 = 319;
pub const FRAME_DEATH213: i32 = 320;
pub const FRAME_DEATH214: i32 = 321;
pub const FRAME_DEATH215: i32 = 322;
pub const FRAME_DEATH216: i32 = 323;
pub const FRAME_DEATH217: i32 = 324;
pub const FRAME_DEATH218: i32 = 325;
pub const FRAME_DEATH219: i32 = 326;
pub const FRAME_DEATH220: i32 = 327;
pub const FRAME_DEATH221: i32 = 328;
pub const FRAME_DEATH222: i32 = 329;
pub const FRAME_DEATH223: i32 = 330;
pub const FRAME_DEATH224: i32 = 331;
pub const FRAME_DEATH225: i32 = 332;
pub const FRAME_DEATH226: i32 = 333;
pub const FRAME_DEATH227: i32 = 334;
pub const FRAME_DEATH228: i32 = 335;
pub const FRAME_DEATH229: i32 = 336;
pub const FRAME_DEATH230: i32 = 337;
pub const FRAME_DEATH231: i32 = 338;
pub const FRAME_DEATH232: i32 = 339;
pub const FRAME_DEATH233: i32 = 340;
pub const FRAME_DEATH234: i32 = 341;
pub const FRAME_DEATH235: i32 = 342;
pub const FRAME_DEATH301: i32 = 343;
pub const FRAME_DEATH302: i32 = 344;
pub const FRAME_DEATH303: i32 = 345;
pub const FRAME_DEATH304: i32 = 346;
pub const FRAME_DEATH305: i32 = 347;
pub const FRAME_DEATH306: i32 = 348;
pub const FRAME_DEATH307: i32 = 349;
pub const FRAME_DEATH308: i32 = 350;
pub const FRAME_DEATH309: i32 = 351;
pub const FRAME_DEATH310: i32 = 352;
pub const FRAME_DEATH311: i32 = 353;
pub const FRAME_DEATH312: i32 = 354;
pub const FRAME_DEATH313: i32 = 355;
pub const FRAME_DEATH314: i32 = 356;
pub const FRAME_DEATH315: i32 = 357;
pub const FRAME_DEATH316: i32 = 358;
pub const FRAME_DEATH317: i32 = 359;
pub const FRAME_DEATH318: i32 = 360;
pub const FRAME_DEATH319: i32 = 361;
pub const FRAME_DEATH320: i32 = 362;
pub const FRAME_DEATH321: i32 = 363;
pub const FRAME_DEATH322: i32 = 364;
pub const FRAME_DEATH323: i32 = 365;
pub const FRAME_DEATH324: i32 = 366;
pub const FRAME_DEATH325: i32 = 367;
pub const FRAME_DEATH326: i32 = 368;
pub const FRAME_DEATH327: i32 = 369;
pub const FRAME_DEATH328: i32 = 370;
pub const FRAME_DEATH329: i32 = 371;
pub const FRAME_DEATH330: i32 = 372;
pub const FRAME_DEATH331: i32 = 373;
pub const FRAME_DEATH332: i32 = 374;
pub const FRAME_DEATH333: i32 = 375;
pub const FRAME_DEATH334: i32 = 376;
pub const FRAME_DEATH335: i32 = 377;
pub const FRAME_DEATH336: i32 = 378;
pub const FRAME_DEATH337: i32 = 379;
pub const FRAME_DEATH338: i32 = 380;
pub const FRAME_DEATH339: i32 = 381;
pub const FRAME_DEATH340: i32 = 382;
pub const FRAME_DEATH341: i32 = 383;
pub const FRAME_DEATH342: i32 = 384;
pub const FRAME_DEATH343: i32 = 385;
pub const FRAME_DEATH344: i32 = 386;
pub const FRAME_DEATH345: i32 = 387;
pub const FRAME_DEATH401: i32 = 388;
pub const FRAME_DEATH402: i32 = 389;
pub const FRAME_DEATH403: i32 = 390;
pub const FRAME_DEATH404: i32 = 391;
pub const FRAME_DEATH405: i32 = 392;
pub const FRAME_DEATH406: i32 = 393;
pub const FRAME_DEATH407: i32 = 394;
pub const FRAME_DEATH408: i32 = 395;
pub const FRAME_DEATH409: i32 = 396;
pub const FRAME_DEATH410: i32 = 397;
pub const FRAME_DEATH411: i32 = 398;
pub const FRAME_DEATH412: i32 = 399;
pub const FRAME_DEATH413: i32 = 400;
pub const FRAME_DEATH414: i32 = 401;
pub const FRAME_DEATH415: i32 = 402;
pub const FRAME_DEATH416: i32 = 403;
pub const FRAME_DEATH417: i32 = 404;
pub const FRAME_DEATH418: i32 = 405;
pub const FRAME_DEATH419: i32 = 406;
pub const FRAME_DEATH420: i32 = 407;
pub const FRAME_DEATH421: i32 = 408;
pub const FRAME_DEATH422: i32 = 409;
pub const FRAME_DEATH423: i32 = 410;
pub const FRAME_DEATH424: i32 = 411;
pub const FRAME_DEATH425: i32 = 412;
pub const FRAME_DEATH426: i32 = 413;
pub const FRAME_DEATH427: i32 = 414;
pub const FRAME_DEATH428: i32 = 415;
pub const FRAME_DEATH429: i32 = 416;
pub const FRAME_DEATH430: i32 = 417;
pub const FRAME_DEATH431: i32 = 418;
pub const FRAME_DEATH432: i32 = 419;
pub const FRAME_DEATH433: i32 = 420;
pub const FRAME_DEATH434: i32 = 421;
pub const FRAME_DEATH435: i32 = 422;
pub const FRAME_DEATH436: i32 = 423;
pub const FRAME_DEATH437: i32 = 424;
pub const FRAME_DEATH438: i32 = 425;
pub const FRAME_DEATH439: i32 = 426;
pub const FRAME_DEATH440: i32 = 427;
pub const FRAME_DEATH441: i32 = 428;
pub const FRAME_DEATH442: i32 = 429;
pub const FRAME_DEATH443: i32 = 430;
pub const FRAME_DEATH444: i32 = 431;
pub const FRAME_DEATH445: i32 = 432;
pub const FRAME_DEATH446: i32 = 433;
pub const FRAME_DEATH447: i32 = 434;
pub const FRAME_DEATH448: i32 = 435;
pub const FRAME_DEATH449: i32 = 436;
pub const FRAME_DEATH450: i32 = 437;
pub const FRAME_DEATH451: i32 = 438;
pub const FRAME_DEATH452: i32 = 439;
pub const FRAME_DEATH453: i32 = 440;
pub const FRAME_DEATH501: i32 = 441;
pub const FRAME_DEATH502: i32 = 442;
pub const FRAME_DEATH503: i32 = 443;
pub const FRAME_DEATH504: i32 = 444;
pub const FRAME_DEATH505: i32 = 445;
pub const FRAME_DEATH506: i32 = 446;
pub const FRAME_DEATH507: i32 = 447;
pub const FRAME_DEATH508: i32 = 448;
pub const FRAME_DEATH509: i32 = 449;
pub const FRAME_DEATH510: i32 = 450;
pub const FRAME_DEATH511: i32 = 451;
pub const FRAME_DEATH512: i32 = 452;
pub const FRAME_DEATH513: i32 = 453;
pub const FRAME_DEATH514: i32 = 454;
pub const FRAME_DEATH515: i32 = 455;
pub const FRAME_DEATH516: i32 = 456;
pub const FRAME_DEATH517: i32 = 457;
pub const FRAME_DEATH518: i32 = 458;
pub const FRAME_DEATH519: i32 = 459;
pub const FRAME_DEATH520: i32 = 460;
pub const FRAME_DEATH521: i32 = 461;
pub const FRAME_DEATH522: i32 = 462;
pub const FRAME_DEATH523: i32 = 463;
pub const FRAME_DEATH524: i32 = 464;
pub const FRAME_DEATH601: i32 = 465;
pub const FRAME_DEATH602: i32 = 466;
pub const FRAME_DEATH603: i32 = 467;
pub const FRAME_DEATH604: i32 = 468;
pub const FRAME_DEATH605: i32 = 469;
pub const FRAME_DEATH606: i32 = 470;
pub const FRAME_DEATH607: i32 = 471;
pub const FRAME_DEATH608: i32 = 472;
pub const FRAME_DEATH609: i32 = 473;
pub const FRAME_DEATH610: i32 = 474;

pub const MODEL_SCALE: f32 = 1.2;

// ============================================================
// Sound indices (module-level state, replaces C statics)
// ============================================================

#[derive(Default)]
pub struct SoldierSounds {
    pub idle: i32,
    pub sight1: i32,
    pub sight2: i32,
    pub pain_light: i32,
    pub pain: i32,
    pub pain_ss: i32,
    pub death_light: i32,
    pub death: i32,
    pub death_ss: i32,
    pub cock: i32,
}

static SOUNDS: std::sync::OnceLock<SoldierSounds> = std::sync::OnceLock::new();


use crate::ai_wrappers::{ai_stand, ai_walk, ai_run, ai_charge, ai_move};

// ============================================================
// Behavior functions
// ============================================================

pub fn soldier_idle(self_ent: &mut Edict, _ctx: &mut GameContext) {
    if random() > 0.8 {
        let sound_idle = SOUNDS.get().map_or(0, |s| s.idle);
        gi_sound(self_ent, 2, sound_idle, 1.0, 2.0, 0.0);
    }
}

pub fn soldier_cock(self_ent: &mut Edict, _ctx: &mut GameContext) {
    let sound_cock = SOUNDS.get().map_or(0, |s| s.cock);
    if self_ent.s.frame >= FRAME_STAND301 && self_ent.s.frame <= FRAME_STAND339 {
        gi_sound(self_ent, 1, sound_cock, 1.0, 1.0, 0.0);
    } else {
        gi_sound(self_ent, 1, sound_cock, 1.0, 1.0, 0.0);
    }
}

// ============================================================
// Stand animation
// ============================================================

// Move indices
pub const MOVE_STAND1: usize = 0;
pub const MOVE_STAND3: usize = 1;
pub const MOVE_WALK1: usize = 2;
pub const MOVE_WALK2: usize = 3;
pub const MOVE_RUN: usize = 4;
pub const MOVE_START_RUN: usize = 5;
pub const MOVE_ATTACK1: usize = 6;
pub const MOVE_ATTACK2: usize = 7;
pub const MOVE_ATTACK3: usize = 8;
pub const MOVE_ATTACK4: usize = 9;
pub const MOVE_ATTACK6: usize = 10;
pub const MOVE_DUCK: usize = 11;
pub const MOVE_PAIN1: usize = 12;
pub const MOVE_PAIN2: usize = 13;
pub const MOVE_PAIN3: usize = 14;
pub const MOVE_PAIN4: usize = 15;
pub const MOVE_DEATH1: usize = 16;
pub const MOVE_DEATH2: usize = 17;
pub const MOVE_DEATH3: usize = 18;
pub const MOVE_DEATH4: usize = 19;
pub const MOVE_DEATH5: usize = 20;
pub const MOVE_DEATH6: usize = 21;

// AI_*, DAMAGE_* constants come from g_local::*

static SOLDIER_FRAMES_STAND1: [MFrame; 30] = [
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: Some(soldier_idle) },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
];

pub static SOLDIER_MOVE_STAND1: MMove = MMove {
    firstframe: FRAME_STAND101,
    lastframe: FRAME_STAND130,
    frames: &SOLDIER_FRAMES_STAND1,
    endfunc: None,
};

static SOLDIER_FRAMES_STAND3: [MFrame; 39] = [
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: Some(soldier_cock) },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_stand, dist: 0.0, think_fn: None },
];

pub static SOLDIER_MOVE_STAND3: MMove = MMove {
    firstframe: FRAME_STAND301,
    lastframe: FRAME_STAND339,
    frames: &SOLDIER_FRAMES_STAND3,
    endfunc: None,
};

pub fn soldier_stand(self_ent: &mut Edict, _ctx: &mut GameContext) {
    if (self_ent.s.frame >= FRAME_STAND301) && (self_ent.s.frame <= FRAME_STAND339) {
        self_ent.monsterinfo.currentmove = Some(MOVE_STAND3);
    } else {
        self_ent.monsterinfo.currentmove = Some(MOVE_STAND1);
    }
}

// ============================================================
// Run animation (placeholder — minimal frames)
// ============================================================

static SOLDIER_FRAMES_RUN: [MFrame; 12] = [
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 11.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 11.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 16.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 15.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 11.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 11.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 16.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 10.0, think_fn: None },
    MFrame { ai_fn: ai_run, dist: 15.0, think_fn: None },
];

pub static SOLDIER_MOVE_RUN: MMove = MMove {
    firstframe: FRAME_RUN01,
    lastframe: FRAME_RUN12,
    frames: &SOLDIER_FRAMES_RUN,
    endfunc: None,
};

pub fn soldier_run(self_ent: &mut Edict, _ctx: &mut GameContext) {
    if self_ent.monsterinfo.aiflags.intersects(AI_STAND_GROUND) {
        self_ent.monsterinfo.currentmove = Some(MOVE_STAND1);
    } else {
        self_ent.monsterinfo.currentmove = Some(MOVE_RUN);
    }
}

// ============================================================
// Walk animation (placeholder — minimal frames)
// ============================================================

static SOLDIER_FRAMES_WALK1: [MFrame; 33] = [
    MFrame { ai_fn: ai_walk, dist: 3.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 6.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 2.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 6.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 5.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 3.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: -1.0, think_fn: Some(soldier_cock) },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_walk, dist: 0.0, think_fn: None },
];

pub static SOLDIER_MOVE_WALK1: MMove = MMove {
    firstframe: FRAME_WALK101,
    lastframe: FRAME_WALK133,
    frames: &SOLDIER_FRAMES_WALK1,
    endfunc: None,
};

pub fn soldier_walk(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.currentmove = Some(MOVE_WALK1);
}

// ============================================================
// Pain
// ============================================================

pub fn soldier_pain(self_ent: &mut Edict, _other: &mut Edict, _kick: f32, _damage: i32, ctx: &mut GameContext) {
    if self_ent.health < (self_ent.max_health / 2) {
        self_ent.s.skinnum |= 1;
    }

    if ctx.level.time < self_ent.pain_debounce_time {
        return;
    }

    self_ent.pain_debounce_time = ctx.level.time + 3.0;
}

// ============================================================
// Death
// ============================================================

pub fn soldier_die(self_ent: &mut Edict, _inflictor: &mut Edict, _attacker: &mut Edict, _damage: i32, _point: [f32; 3], _ctx: &mut GameContext) {
    // Check for gib
    if self_ent.health <= self_ent.gib_health {
        gi_sound(self_ent, CHAN_VOICE, gi_soundindex("misc/udeath.wav"), 1.0, ATTN_NORM as f32, 0.0);
        let self_idx = self_ent.s.number as usize;
        let damage = _damage;
        crate::g_local::with_global_game_ctx(|ctx| {
            for _ in 0..3 {
                crate::g_misc::throw_gib(ctx, self_idx, "models/objects/gibs/sm_meat/tris.md2", damage, GIB_ORGANIC);
            }
            crate::g_misc::throw_gib(ctx, self_idx, "models/objects/gibs/chest/tris.md2", damage, GIB_ORGANIC);
            crate::g_misc::throw_head(ctx, self_idx, "models/objects/gibs/head2/tris.md2", damage, GIB_ORGANIC);
        });
        self_ent.deadflag = DEAD_DEAD;
        return;
    }

    if self_ent.deadflag == DEAD_DEAD {
        return;
    }

    // Regular death
    self_ent.deadflag = DEAD_DEAD;
    self_ent.takedamage = DAMAGE_YES;
    self_ent.s.skinnum |= 1;

    if self_ent.s.skinnum == 1 {
        gi_sound(self_ent, CHAN_VOICE, SOUNDS.get().map_or(0, |s| s.death_light), 1.0, ATTN_NORM as f32, 0.0);
    } else if self_ent.s.skinnum == 3 {
        gi_sound(self_ent, CHAN_VOICE, SOUNDS.get().map_or(0, |s| s.death), 1.0, ATTN_NORM as f32, 0.0);
    } else {
        gi_sound(self_ent, CHAN_VOICE, SOUNDS.get().map_or(0, |s| s.death_ss), 1.0, ATTN_NORM as f32, 0.0);
    }

    if (self_ent.s.origin[2] + self_ent.viewheight as f32 - _point[2]).abs() <= 4.0 {
        // Head shot
        self_ent.monsterinfo.currentmove = Some(MOVE_DEATH3);
        return;
    }

    let n = rand::random::<u32>() % 5;
    match n {
        0 => self_ent.monsterinfo.currentmove = Some(MOVE_DEATH1),
        1 => self_ent.monsterinfo.currentmove = Some(MOVE_DEATH2),
        2 => self_ent.monsterinfo.currentmove = Some(MOVE_DEATH4),
        3 => self_ent.monsterinfo.currentmove = Some(MOVE_DEATH5),
        _ => self_ent.monsterinfo.currentmove = Some(MOVE_DEATH6),
    }
}

// ============================================================
// Dodge
// ============================================================

static SOLDIER_FRAMES_DUCK: [MFrame; 5] = [
    MFrame { ai_fn: ai_move, dist: 5.0, think_fn: Some(soldier_duck_down) },
    MFrame { ai_fn: ai_move, dist: -1.0, think_fn: Some(soldier_duck_hold) },
    MFrame { ai_fn: ai_move, dist: 1.0, think_fn: None },
    MFrame { ai_fn: ai_move, dist: 0.0, think_fn: Some(soldier_duck_up) },
    MFrame { ai_fn: ai_move, dist: 5.0, think_fn: None },
];

pub static SOLDIER_MOVE_DUCK: MMove = MMove {
    firstframe: FRAME_DUCK01,
    lastframe: FRAME_DUCK05,
    frames: &SOLDIER_FRAMES_DUCK,
    endfunc: None,
};

static SOLDIER_FRAMES_ATTACK3: [MFrame; 9] = [
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(soldier_fire3) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(soldier_attack3_refire) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(soldier_duck_up) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
];

pub static SOLDIER_MOVE_ATTACK3: MMove = MMove {
    firstframe: FRAME_ATTAK301,
    lastframe: FRAME_ATTAK309,
    frames: &SOLDIER_FRAMES_ATTACK3,
    endfunc: None,
};

pub fn soldier_duck_down(self_ent: &mut Edict, ctx: &mut GameContext) {
    if self_ent.monsterinfo.aiflags.intersects(AI_DUCKED) {
        return;
    }
    self_ent.monsterinfo.aiflags |= AI_DUCKED;
    self_ent.maxs[2] -= 32.0;
    self_ent.takedamage = DAMAGE_YES;
    self_ent.monsterinfo.pausetime = ctx.level.time + 1.0;
    gi_linkentity(self_ent);
}

pub fn soldier_duck_up(self_ent: &mut Edict, _ctx: &mut GameContext) {
    self_ent.monsterinfo.aiflags &= !AI_DUCKED;
    self_ent.maxs[2] += 32.0;
    self_ent.takedamage = DAMAGE_AIM;
    gi_linkentity(self_ent);
}

pub fn soldier_duck_hold(self_ent: &mut Edict, ctx: &mut GameContext) {
    if ctx.level.time >= self_ent.monsterinfo.pausetime {
        self_ent.monsterinfo.aiflags &= !AI_HOLD_FRAME;
    } else {
        self_ent.monsterinfo.aiflags |= AI_HOLD_FRAME;
    }
}

pub fn soldier_fire3(self_ent: &mut Edict, ctx: &mut GameContext) {
    soldier_duck_down(self_ent, ctx);
    soldier_fire(self_ent, 2, ctx);
}

pub fn soldier_attack3_refire(self_ent: &mut Edict, ctx: &mut GameContext) {
    if (ctx.level.time + 0.4) < self_ent.monsterinfo.pausetime {
        self_ent.monsterinfo.nextframe = FRAME_ATTAK303;
    }
}

static BLASTER_FLASH: [i32; 8] = [39, 40, 83, 86, 89, 92, 95, 98];
static SHOTGUN_FLASH: [i32; 8] = [41, 42, 84, 87, 90, 93, 96, 99];
static MACHINEGUN_FLASH: [i32; 8] = [43, 44, 85, 88, 91, 94, 97, 100];

pub fn soldier_fire(self_ent: &mut Edict, flash_number: i32, ctx: &mut GameContext) {
    let flash_index = if self_ent.s.skinnum < 2 {
        BLASTER_FLASH[flash_number as usize]
    } else if self_ent.s.skinnum < 4 {
        SHOTGUN_FLASH[flash_number as usize]
    } else {
        MACHINEGUN_FLASH[flash_number as usize]
    };

    let mut forward = [0.0_f32; 3];
    let mut right = [0.0_f32; 3];
    angle_vectors(&self_ent.s.angles, Some(&mut forward), Some(&mut right), None);
    let offset = crate::m_flash::MONSTER_FLASH_OFFSET[flash_index as usize];
    let start = crate::g_utils::g_project_source(&self_ent.s.origin, &offset, &forward, &right);

    let mut aim;
    if flash_number == 5 || flash_number == 6 {
        aim = forward;
    } else {
        let enemy_idx = self_ent.enemy;
        let mut end = [0.0_f32; 3];
        if enemy_idx > 0 && (enemy_idx as usize) < ctx.edicts.len() {
            let enemy = &ctx.edicts[enemy_idx as usize];
            end = enemy.s.origin;
            end[2] += enemy.viewheight as f32;
        }
        aim = vector_subtract(&end, &start);
        let mut dir = [0.0_f32; 3];
        crate::g_utils::vectoangles(&aim, &mut dir);
        let mut up = [0.0_f32; 3];
        angle_vectors(&dir, Some(&mut forward), Some(&mut right), Some(&mut up));

        let r = crandom() * 1000.0;
        let u = crandom() * 500.0;
        end = vector_ma(&start, 8192.0, &forward);
        end = vector_ma(&end, r, &right);
        end = vector_ma(&end, u, &up);

        aim = vector_subtract(&end, &start);
        vector_normalize(&mut aim);
    }

    let self_idx = self_ent.s.number;
    if self_ent.s.skinnum <= 1 {
        crate::g_monster::monster_fire_blaster(ctx, self_idx, start, aim, 5, 600, flash_index, EF_BLASTER as i32);
    } else if self_ent.s.skinnum <= 3 {
        crate::g_monster::monster_fire_shotgun(ctx, self_idx, start, aim, 2, 1, DEFAULT_SHOTGUN_HSPREAD, DEFAULT_SHOTGUN_VSPREAD, DEFAULT_SHOTGUN_COUNT, flash_index);
    } else {
        let self_ent = &mut ctx.edicts[self_idx as usize];
        if !self_ent.monsterinfo.aiflags.intersects(AI_HOLD_FRAME) {
            self_ent.monsterinfo.pausetime = ctx.level.time + (3 + (rand::random::<u32>() % 8)) as f32 * FRAMETIME;
        }
        crate::g_monster::monster_fire_bullet(ctx, self_idx, start, aim, 2, 4, DEFAULT_BULLET_HSPREAD, DEFAULT_BULLET_VSPREAD, flash_index);
        let self_ent = &mut ctx.edicts[self_idx as usize];
        if ctx.level.time >= self_ent.monsterinfo.pausetime {
            self_ent.monsterinfo.aiflags &= !AI_HOLD_FRAME;
        } else {
            self_ent.monsterinfo.aiflags |= AI_HOLD_FRAME;
        }
    }
}

pub fn soldier_dodge(self_ent: &mut Edict, attacker_idx: i32, eta: f32, ctx: &mut GameContext) {
    let r = random();
    if r > 0.25 {
        return;
    }

    if self_ent.enemy < 0 {
        self_ent.enemy = attacker_idx;
    }

    let skill_value = ctx.skill;

    if skill_value == 0.0 {
        self_ent.monsterinfo.currentmove = Some(MOVE_DUCK);
        return;
    }

    self_ent.monsterinfo.pausetime = ctx.level.time + eta + 0.3;
    let r = random();

    if skill_value == 1.0 {
        if r > 0.33 {
            self_ent.monsterinfo.currentmove = Some(MOVE_DUCK);
        } else {
            self_ent.monsterinfo.currentmove = Some(MOVE_ATTACK3);
        }
        return;
    }

    if skill_value >= 2.0 {
        if r > 0.66 {
            self_ent.monsterinfo.currentmove = Some(MOVE_DUCK);
        } else {
            self_ent.monsterinfo.currentmove = Some(MOVE_ATTACK3);
        }
        return;
    }

    self_ent.monsterinfo.currentmove = Some(MOVE_ATTACK3);
}

// ============================================================
// Attack
// ============================================================

static SOLDIER_FRAMES_ATTACK1: [MFrame; 12] = [
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(soldier_fire1) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(soldier_attack1_refire1) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(soldier_cock) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(soldier_attack1_refire2) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
];

pub static SOLDIER_MOVE_ATTACK1: MMove = MMove {
    firstframe: FRAME_ATTAK101,
    lastframe: FRAME_ATTAK112,
    frames: &SOLDIER_FRAMES_ATTACK1,
    endfunc: None,
};

static SOLDIER_FRAMES_ATTACK2: [MFrame; 18] = [
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(soldier_fire2) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(soldier_attack2_refire1) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(soldier_cock) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(soldier_attack2_refire2) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
];

pub static SOLDIER_MOVE_ATTACK2: MMove = MMove {
    firstframe: FRAME_ATTAK201,
    lastframe: FRAME_ATTAK218,
    frames: &SOLDIER_FRAMES_ATTACK2,
    endfunc: None,
};

static SOLDIER_FRAMES_ATTACK4: [MFrame; 6] = [
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: Some(soldier_fire4) },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
    MFrame { ai_fn: ai_charge, dist: 0.0, think_fn: None },
];

pub static SOLDIER_MOVE_ATTACK4: MMove = MMove {
    firstframe: FRAME_ATTAK401,
    lastframe: FRAME_ATTAK406,
    frames: &SOLDIER_FRAMES_ATTACK4,
    endfunc: None,
};

pub fn soldier_fire1(self_ent: &mut Edict, ctx: &mut GameContext) {
    soldier_fire(self_ent, 0, ctx);
}

pub fn soldier_fire2(self_ent: &mut Edict, ctx: &mut GameContext) {
    soldier_fire(self_ent, 1, ctx);
}

pub fn soldier_fire4(self_ent: &mut Edict, ctx: &mut GameContext) {
    soldier_fire(self_ent, 3, ctx);
}

pub fn soldier_attack1_refire1(self_ent: &mut Edict, ctx: &mut GameContext) {
    if self_ent.s.skinnum > 1 {
        return;
    }
    let enemy_idx = self_ent.enemy;
    if enemy_idx > 0 && (enemy_idx as usize) < ctx.edicts.len() {
        if ctx.edicts[enemy_idx as usize].health <= 0 {
            return;
        }
        if (ctx.skill >= 3.0 && random() < 0.5) || crate::g_ai::range(self_ent, &ctx.edicts[enemy_idx as usize]) == RANGE_MELEE {
            self_ent.monsterinfo.nextframe = FRAME_ATTAK102;
        } else {
            self_ent.monsterinfo.nextframe = FRAME_ATTAK110;
        }
    }
}

pub fn soldier_attack1_refire2(self_ent: &mut Edict, ctx: &mut GameContext) {
    if self_ent.s.skinnum < 2 {
        return;
    }
    let enemy_idx = self_ent.enemy;
    if enemy_idx > 0 && (enemy_idx as usize) < ctx.edicts.len() {
        if ctx.edicts[enemy_idx as usize].health <= 0 {
            return;
        }
        if (ctx.skill >= 3.0 && random() < 0.5) || crate::g_ai::range(self_ent, &ctx.edicts[enemy_idx as usize]) == RANGE_MELEE {
            self_ent.monsterinfo.nextframe = FRAME_ATTAK102;
        }
    }
}

pub fn soldier_attack2_refire1(self_ent: &mut Edict, ctx: &mut GameContext) {
    if self_ent.s.skinnum > 1 {
        return;
    }
    let enemy_idx = self_ent.enemy;
    if enemy_idx > 0 && (enemy_idx as usize) < ctx.edicts.len() {
        if ctx.edicts[enemy_idx as usize].health <= 0 {
            return;
        }
        if (ctx.skill >= 3.0 && random() < 0.5) || crate::g_ai::range(self_ent, &ctx.edicts[enemy_idx as usize]) == RANGE_MELEE {
            self_ent.monsterinfo.nextframe = FRAME_ATTAK204;
        } else {
            self_ent.monsterinfo.nextframe = FRAME_ATTAK216;
        }
    }
}

pub fn soldier_attack2_refire2(self_ent: &mut Edict, ctx: &mut GameContext) {
    if self_ent.s.skinnum < 2 {
        return;
    }
    let enemy_idx = self_ent.enemy;
    if enemy_idx > 0 && (enemy_idx as usize) < ctx.edicts.len() {
        if ctx.edicts[enemy_idx as usize].health <= 0 {
            return;
        }
        if (ctx.skill >= 3.0 && random() < 0.5) || crate::g_ai::range(self_ent, &ctx.edicts[enemy_idx as usize]) == RANGE_MELEE {
            self_ent.monsterinfo.nextframe = FRAME_ATTAK204;
        }
    }
}

pub fn soldier_attack(self_ent: &mut Edict, _ctx: &mut GameContext) {
    if self_ent.s.skinnum < 4 {
        if random() < 0.5 {
            self_ent.monsterinfo.currentmove = Some(MOVE_ATTACK1);
        } else {
            self_ent.monsterinfo.currentmove = Some(MOVE_ATTACK2);
        }
    } else {
        self_ent.monsterinfo.currentmove = Some(MOVE_ATTACK4);
    }
}

// ============================================================
// Sight
// ============================================================

pub fn soldier_sight(self_ent: &mut Edict, _other: &mut Edict) {
    if random() < 0.5 {
        let s = SOUNDS.get().map_or(0, |s| s.sight1);
        gi_sound(self_ent, 2, s, 1.0, 1.0, 0.0);
    } else {
        let s = SOUNDS.get().map_or(0, |s| s.sight2);
        gi_sound(self_ent, 2, s, 1.0, 1.0, 0.0);
    }

    let enemy_idx = self_ent.enemy;
    let should_attack = crate::g_local::with_global_game_ctx(|ctx| {
        if ctx.skill > 0.0 && enemy_idx > 0 && (enemy_idx as usize) < ctx.edicts.len() {
            crate::g_ai::range(self_ent, &ctx.edicts[enemy_idx as usize]) >= RANGE_MID
        } else {
            false
        }
    }).unwrap_or(false);

    if should_attack && random() > 0.5 {
        self_ent.monsterinfo.currentmove = Some(MOVE_ATTACK6);
    }
}

// ============================================================
// Spawn functions
// ============================================================

fn soldier_precache(_self_ent: &mut Edict) {
    SOUNDS.get_or_init(|| SoldierSounds {
        pain_light: gi_soundindex("soldier/solpain2.wav"),
        pain: gi_soundindex("soldier/solpain1.wav"),
        pain_ss: gi_soundindex("soldier/solpain3.wav"),
        death_light: gi_soundindex("soldier/soldeth2.wav"),
        death: gi_soundindex("soldier/soldeth1.wav"),
        death_ss: gi_soundindex("soldier/soldeth3.wav"),
        sight1: gi_soundindex("soldier/solsght1.wav"),
        sight2: gi_soundindex("soldier/solsrch1.wav"),
        cock: gi_soundindex("infantry/infatck3.wav"),
        idle: gi_soundindex("soldier/solidle1.wav"),
    });
}

fn soldier_common_spawn(self_ent: &mut Edict, _ctx: &mut GameContext) {
    soldier_precache(self_ent);

    self_ent.s.modelindex = gi_modelindex("models/monsters/soldier/tris.md2");
    self_ent.mins = [-16.0, -16.0, -24.0];
    self_ent.maxs = [16.0, 16.0, 32.0];
    self_ent.movetype = MoveType::Step;
    self_ent.solid = Solid::Bbox;

    self_ent.mass = 100;

    self_ent.pain_fn = Some(crate::dispatch::PAIN_SOLDIER);
    self_ent.die_fn = Some(crate::dispatch::DIE_SOLDIER);

    self_ent.monsterinfo.stand_fn = Some(crate::dispatch::MSTAND_SOLDIER);
    self_ent.monsterinfo.walk_fn = Some(crate::dispatch::MWALK_SOLDIER);
    self_ent.monsterinfo.run_fn = Some(crate::dispatch::MRUN_SOLDIER);
    self_ent.monsterinfo.dodge_fn = Some(crate::dispatch::MDODGE_SOLDIER);
    self_ent.monsterinfo.attack_fn = Some(crate::dispatch::MATTACK_SOLDIER);
    self_ent.monsterinfo.melee_fn = None;
    self_ent.monsterinfo.sight_fn = Some(crate::dispatch::MSIGHT_SOLDIER);
    self_ent.monsterinfo.idle_fn = Some(crate::dispatch::MIDLE_SOLDIER);
    self_ent.monsterinfo.search_fn = None;   // NULL in original C code

    self_ent.monsterinfo.currentmove = Some(MOVE_STAND1);
    self_ent.monsterinfo.scale = MODEL_SCALE;

    gi_linkentity(self_ent);

    walkmonster_start(self_ent);
}

/// QUAKED monster_soldier_light (1 .5 0) (-16 -16 -24) (16 16 32) Ambush Trigger_Spawn Sight
pub fn sp_monster_soldier_light(self_ent: &mut Edict, ctx: &mut GameContext) {
    if ctx.deathmatch != 0.0 {
        let self_idx = self_ent.s.number as usize;
        crate::g_local::with_global_game_ctx(|gctx| {
            crate::g_utils::g_free_edict(gctx, self_idx);
        });
        return;
    }

    self_ent.health = 20;
    self_ent.gib_health = -30;

    soldier_common_spawn(self_ent, ctx);
}

/// QUAKED monster_soldier (1 .5 0) (-16 -16 -24) (16 16 32) Ambush Trigger_Spawn Sight
pub fn sp_monster_soldier(self_ent: &mut Edict, ctx: &mut GameContext) {
    if ctx.deathmatch != 0.0 {
        let self_idx = self_ent.s.number as usize;
        crate::g_local::with_global_game_ctx(|gctx| {
            crate::g_utils::g_free_edict(gctx, self_idx);
        });
        return;
    }

    self_ent.health = 30;
    self_ent.gib_health = -30;

    soldier_common_spawn(self_ent, ctx);
    self_ent.s.skinnum = 2;
}

/// QUAKED monster_soldier_ss (1 .5 0) (-16 -16 -24) (16 16 32) Ambush Trigger_Spawn Sight
pub fn sp_monster_soldier_ss(self_ent: &mut Edict, ctx: &mut GameContext) {
    if ctx.deathmatch != 0.0 {
        let self_idx = self_ent.s.number as usize;
        crate::g_local::with_global_game_ctx(|gctx| {
            crate::g_utils::g_free_edict(gctx, self_idx);
        });
        return;
    }

    self_ent.health = 40;
    self_ent.gib_health = -30;

    soldier_common_spawn(self_ent, ctx);
    self_ent.s.skinnum = 4;
}
